import type { Action, AttackAction, MatchState, MoveAction, Side } from '../model/index.js';
import type { ISeededRng } from '../rng/index.js';
import { coordKey } from '../rules/index.js';
import { legalActions, type EngineProviders } from '../engine/game-engine.js';
import type { IAiPolicy } from './policy.js';
import { livingEnemies, nearestEnemyDistance, scoreAttack, tokenHp } from './eval.js';

/**
 * A 1-ply lethal-first policy (v1 decision 4). Each call it prefers, in order:
 *  1. the attack dealing the most `resolveDamage` (a would-be lethal blow — damage ≥ the
 *     target's current hp — outranks all non-lethal attacks);
 *  2. otherwise the move that most reduces Chebyshev distance to the nearest living enemy;
 *  3. otherwise `end-turn`.
 * Fully deterministic: ties break by tokenId then target-id / destination key, and the rng
 * is never consulted (scoring is rng-free). With the dual-budget reducer, the sim loop
 * re-invokes this until end-turn, so a token can move into range then attack the same turn.
 */
export class GreedyPolicy implements IAiPolicy {
  readonly name = 'greedy';

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: chooseAction — (no summary)
  // @ai-hash: 2e3118c1
  // ── END AI-METHOD ──
  chooseAction(state: MatchState, side: Side, p: EngineProviders, _rng: ISeededRng): Action {
    const acts = legalActions(state, side, p);

    // 1. Best attack (lethal-first, deterministic tie-break).
    const attacks = acts.filter((a): a is AttackAction => a.type === 'attack');
    if (attacks.length > 0) {
      const scored = attacks.map((a) => {
        const dmg = scoreAttack(state, a.tokenId, a.targetId, p.data);
        const target = state.tokens.find((t) => t.instanceId === a.targetId);
        const lethal = target ? dmg >= tokenHp(target) : false;
        return { a, score: (lethal ? 1e6 : 0) + dmg };
      });
      scored.sort(
        (x, y) =>
          y.score - x.score ||
          x.a.tokenId.localeCompare(y.a.tokenId) ||
          x.a.targetId.localeCompare(y.a.targetId),
      );
      return scored[0].a;
    }

    // 2. Best advance toward the nearest enemy.
    const enemies = livingEnemies(state, side);
    const moves = acts.filter((a): a is MoveAction => a.type === 'move');
    if (moves.length > 0 && enemies.length > 0) {
      const scored = moves.map((m) => ({ m, d: nearestEnemyDistance(m.to, enemies) }));
      scored.sort(
        (x, y) =>
          x.d - y.d ||
          x.m.tokenId.localeCompare(y.m.tokenId) ||
          coordKey(x.m.to).localeCompare(coordKey(y.m.to)),
      );
      return scored[0].m;
    }

    // 3. Nothing useful — end the turn.
    return { type: 'end-turn', side };
  }
}
