import { createGameDataProvider, createGameModeProvider } from '../data/index.js';
import type { Board, Coord, MatchState, Tile, Unit } from '../model/index.js';
import { createRng } from '../rng/index.js';
import { chebyshev } from '../rules/index.js';
import type { EngineProviders } from '../engine/game-engine.js';
import { scoreAttack } from './eval.js';
import { GreedyPolicy } from './greedy-policy.js';

const providers: EngineProviders = {
  data: createGameDataProvider(),
  modes: createGameModeProvider(),
};

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: board — (no summary)
// @ai-hash: dec4a33d
// ── END AI-METHOD ──
function board(w: number, h: number): Board {
  const tiles: Tile[][] = [];
  for (let y = 0; y < h; y++) {
    const row: Tile[] = [];
    for (let x = 0; x < w; x++) row.push({ terrain: 'Field', feature: null });
    tiles.push(row);
  }
  return { width: w, height: h, tiles };
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: unit — (no summary)
// @ai-hash: 78205a01
// ── END AI-METHOD ──
function unit(instanceId: string, templateId: string, pos: Coord, side: number): Unit {
  return {
    kind: 'unit',
    instanceId,
    templateId,
    side,
    pos,
    hp: 999,
    statuses: [],
    hasMoved: false,
    hasActed: false,
  };
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: state — (no summary)
// @ai-hash: bec456df
// ── END AI-METHOD ──
function state(tokens: Unit[]): MatchState {
  return {
    modeId: 'skirmish',
    board: board(10, 10),
    armies: [],
    tokens,
    turn: 1,
    activeSide: 0,
    moon: { gameHour: 0, sky: { Black: 'HalfMoon', Red: 'HalfMoon', White: 'HalfMoon' } },
    rngState: 1,
    status: 'in-progress',
  };
}

const greedy = new GreedyPolicy();
const rng = () => createRng(1);

describe('GreedyPolicy', () => {
  it('attacks an in-range enemy rather than moving', () => {
    const s = state([
      unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0),
      unit('d', 'Human:Warrior', { x: 6, y: 5 }, 1),
    ]);
    const action = greedy.chooseAction(s, 0, providers, rng());
    expect(action.type).toBe('attack');
    if (action.type === 'attack') expect(action.targetId).toBe('d');
  });

  it('chooses the higher-damage target when two are reachable', () => {
    const s = state([
      unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0),
      unit('warr', 'Human:Warrior', { x: 6, y: 5 }, 1),
      unit('mage', 'Human:Mage', { x: 5, y: 6 }, 1),
    ]);
    // Establish which target actually takes more damage, then assert Greedy picks it.
    const dmgWarr = scoreAttack(s, 'a', 'warr', providers.data);
    const dmgMage = scoreAttack(s, 'a', 'mage', providers.data);
    expect(dmgWarr).not.toBe(dmgMage); // the two matchups must differ for this test to mean anything
    const higher = dmgMage > dmgWarr ? 'mage' : 'warr';

    const action = greedy.chooseAction(s, 0, providers, rng());
    expect(action.type).toBe('attack');
    if (action.type === 'attack') expect(action.targetId).toBe(higher);
  });

  it('advances toward the nearest enemy when none is in range', () => {
    const s = state([
      unit('a', 'Human:Warrior', { x: 0, y: 0 }, 0),
      unit('d', 'Human:Warrior', { x: 9, y: 9 }, 1),
    ]);
    const before = chebyshev({ x: 0, y: 0 }, { x: 9, y: 9 });
    const action = greedy.chooseAction(s, 0, providers, rng());
    expect(action.type).toBe('move');
    if (action.type === 'move') {
      expect(chebyshev(action.to, { x: 9, y: 9 })).toBeLessThan(before);
    }
  });

  it('ends the turn when there are no living enemies', () => {
    const s = state([unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0)]);
    const action = greedy.chooseAction(s, 0, providers, rng());
    expect(action.type).toBe('end-turn');
  });

  it('prefers a lethal blow over a higher-raw-damage non-lethal one', () => {
    const s = state([
      // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
      // @ai-method: unit — (no summary)
      // @ai-hash: 5c500216
      // ── END AI-METHOD ──
      unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0),
      // 'weak' is nearly dead: even small damage is lethal and must be preferred.
      { ...unit('weak', 'Human:Warrior', { x: 6, y: 5 }, 1), hp: 1 },
      unit('tough', 'Human:Mage', { x: 5, y: 6 }, 1),
    ]);
    const action = greedy.chooseAction(s, 0, providers, rng());
    expect(action.type).toBe('attack');
    if (action.type === 'attack') expect(action.targetId).toBe('weak');
  });
});
