import { createGameDataProvider, createGameModeProvider } from '../data/index.js';
import type { Board, Coord, MatchState, Tile, Unit } from '../model/index.js';
import { createRng } from '../rng/index.js';
import type { EngineProviders } from '../engine/game-engine.js';
import { RandomPolicy } from './random-policy.js';

const providers: EngineProviders = {
  data: createGameDataProvider(),
  modes: createGameModeProvider(),
};

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: board — (no summary)
// @ai-hash: dec4a33d
// ── END AI-METHOD ──
function board(w: number, h: number): Board {
  const tiles: Tile[][] = [];
  for (let y = 0; y < h; y++) {
    const row: Tile[] = [];
    for (let x = 0; x < w; x++) row.push({ terrain: 'Field', feature: null });
    tiles.push(row);
  }
  return { width: w, height: h, tiles };
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: unit — (no summary)
// @ai-hash: 78205a01
// ── END AI-METHOD ──
function unit(instanceId: string, templateId: string, pos: Coord, side: number): Unit {
  return {
    kind: 'unit',
    instanceId,
    templateId,
    side,
    pos,
    hp: 999,
    statuses: [],
    hasMoved: false,
    hasActed: false,
  };
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: state — (no summary)
// @ai-hash: bec456df
// ── END AI-METHOD ──
function state(tokens: Unit[]): MatchState {
  return {
    modeId: 'skirmish',
    board: board(10, 10),
    armies: [],
    tokens,
    turn: 1,
    activeSide: 0,
    moon: { gameHour: 0, sky: { Black: 'HalfMoon', Red: 'HalfMoon', White: 'HalfMoon' } },
    rngState: 1,
    status: 'in-progress',
  };
}

const random = new RandomPolicy();

describe('RandomPolicy', () => {
  const twoUnits = () =>
    state([
      unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0),
      unit('d', 'Human:Warrior', { x: 6, y: 5 }, 1),
    ]);

  it('is deterministic under a fixed seed', () => {
    const s = twoUnits();
    const a1 = random.chooseAction(s, 0, providers, createRng(42));
    const a2 = random.chooseAction(s, 0, providers, createRng(42));
    expect(a2).toEqual(a1);
  });

  it('never ends the turn while a real action is available', () => {
    const s = twoUnits();
    for (let seed = 0; seed < 25; seed++) {
      const action = random.chooseAction(s, 0, providers, createRng(seed));
      expect(action.type).not.toBe('end-turn');
    }
  });

  it('ends the turn when the side has no legal non-end-turn action', () => {
    // A lone token with both budgets spent has only end-turn available.
    const spent: Unit = { ...unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0), hasMoved: true, hasActed: true };
    const action = random.chooseAction(state([spent]), 0, providers, createRng(1));
    expect(action.type).toBe('end-turn');
  });
});
