import type { Action, MatchState, Side } from '../model/index.js';
import type { ISeededRng } from '../rng/index.js';
import { legalActions, type EngineProviders } from '../engine/game-engine.js';
import type { IAiPolicy } from './policy.js';

/**
 * Picks uniformly at random among the NON-end-turn actions when any exist, else ends the
 * turn (v1 decision 4). This bias toward doing something keeps random matches lively while
 * staying fully stochastic and seed-reproducible (all randomness via `rng.pick`).
 */
export class RandomPolicy implements IAiPolicy {
  readonly name = 'random';

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: chooseAction — (no summary)
  // @ai-hash: bee7350b
  // ── END AI-METHOD ──
  chooseAction(state: MatchState, side: Side, p: EngineProviders, rng: ISeededRng): Action {
    const acts = legalActions(state, side, p);
    const nonEnd = acts.filter((a) => a.type !== 'end-turn');
    return nonEnd.length > 0 ? rng.pick(nonEnd) : { type: 'end-turn', side };
  }
}
