// services/services-server/src/expressService.ts
import express, { Application } from 'express';
import * as http from 'node:http';
import * as https from 'node:https';
import * as fs from 'node:fs';

import cors, { CorsOptions } from 'cors';
import helmet, { HelmetOptions } from 'helmet';

export interface ExpressServiceConfig {
  /** Logical service name, used for logging */
  name: string;
  /** Port to listen on */
  port: number;
  /** Host / bind address (default: 0.0.0.0) */
  host?: string;

  /** Enable HTTPS / SSL if true */
  enableSsl?: boolean;
  /** Path to SSL key (PEM) */
  sslKeyPath?: string;
  /** Path to SSL cert (PEM) */
  sslCertPath?: string;
  /** Optional CA bundle */
  sslCaPath?: string;

  /** CORS origin policy. Use parseCorsOrigin() to build from env. Default: localhost only. */
  corsOrigin?: CorsOptions['origin'];

  /** See Express docs: trust proxies */
  trustProxy?: boolean | number | string;

  /** Enable request logging hook */
  enableRequestLogging?: boolean;

  /**
   * Override Helmet options. The default CSP is `default-src 'none'` which is
   * correct for JSON-only API services. Override here if the service serves HTML.
   */
  helmetOptions?: HelmetOptions;
}

export type RouteRegistrar = (app: Application) => void;

export interface IExpressService {
  readonly app: Application;
  start(): Promise<http.Server | https.Server>;
  stop(): Promise<void>;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: parseCorsOrigin — Parses CORS origin configuration strings into validation functions for origin checking.
// @ai-hash: 56a7f990
// ── END AI-METHOD ──
/**
 * Parses the CORS_ORIGIN environment variable into a cors-compatible origin value.
 *
 * Accepted formats:
 *   (unset)                      → localhost only (http/https, any port)
 *   *                            → reflect all origins (open/self-hosted; not for production with credentials)
 *   https://a.example.com        → single exact origin
 *   https://a.com,https://b.com  → comma-separated exact origins
 *
 * Requests with no Origin header (server-to-server) are always allowed through
 * regardless of this setting, since they cannot exploit CORS.
 */
export function parseCorsOrigin(raw: string | undefined): CorsOptions['origin'] {
  if (!raw) {
    // Secure default: allow localhost at any port for easy dev/self-host setup
    return /^https?:\/\/localhost(:\d+)?$/;
  }

  if (raw === '*') {
    // Explicit wildcard — caller accepts the risk
    return true;
  }

  const allowed = new Set(
    raw
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean),
  );

  return (origin, callback) => {
    // No Origin header → server-to-server call; not subject to CORS
    if (!origin) return callback(null, true);
    callback(null, allowed.has(origin));
  };
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: getConfigFromEnv — Retrieves and parses environment variables to configure service settings for Express.js application.
// @ai-hash: 6022c22f
// ── END AI-METHOD ──
/**
 * Loads a standardized configuration for an Express service from environment
 * variables. Centralized so apps don't duplicate config logic.
 *
 * Each service sets its name, but env determines:
 *  - PORT                (default 31000)
 *  - SSL_ENABLED         ("true" / "false")
 *  - SSL_KEY_PATH
 *  - SSL_CERT_PATH
 *  - SSL_CA_PATH
 *  - CORS_ORIGIN         (see parseCorsOrigin for accepted formats)
 *  - TRUST_PROXY
 *  - REQUEST_LOGGING     ("true" / "false")
 */
export function getConfigFromEnv(serviceName: string): ExpressServiceConfig {
  const port = Number(process.env.PORT);
  const enableSsl = process.env.SSL_ENABLED === 'true';

  return {
    name: serviceName,
    port,
    host: process.env.HOST ?? '0.0.0.0',

    enableSsl,
    sslKeyPath: process.env.SSL_KEY_PATH,
    sslCertPath: process.env.SSL_CERT_PATH,
    sslCaPath: process.env.SSL_CA_PATH,

    corsOrigin: parseCorsOrigin(process.env.CORS_ORIGIN),
    trustProxy:
      process.env.TRUST_PROXY === undefined
        ? undefined
        : process.env.TRUST_PROXY === 'true' || process.env.TRUST_PROXY === '1',

    enableRequestLogging: process.env.REQUEST_LOGGING === 'true',
  };
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: createExpressService — Creates and configures an Express service with security headers, CORS, body parsing, and SSL support.
// @ai-hash: 9d769f15
// ── END AI-METHOD ──
/**
 * Creates a hardened Express service with OWASP/Troy Hunt best-practice defaults.
 */
export function createExpressService(config: ExpressServiceConfig, registerRoutes: RouteRegistrar): IExpressService {
  const app = express();

  // disable express signature
  app.disable('x-powered-by');

  // HTTP Security headers
  app.use(
    helmet({
      // default-src 'none' is correct for JSON-only API endpoints; callers that
      // serve HTML should pass helmetOptions with an appropriate CSP policy.
      contentSecurityPolicy: { directives: { defaultSrc: ["'none'"] } },
      crossOriginEmbedderPolicy: false,
      ...config.helmetOptions,
    }),
  );

  // CORS
  app.use(
    cors({
      origin: config.corsOrigin ?? /^https?:\/\/localhost(:\d+)?$/,
      credentials: true,
    }),
  );

  // Body parsing
  app.use(express.json({ limit: '1mb' }));
  app.use(express.urlencoded({ extended: true }));

  // Trust proxies
  if (config.trustProxy !== undefined) {
    app.set('trust proxy', config.trustProxy);
  }

  // App-specific route registration
  registerRoutes(app);

  // Server lifecycle
  let server: http.Server | https.Server | null = null;

  async function start(): Promise<http.Server | https.Server> {
    if (server) return server;

    const host = config.host ?? '0.0.0.0';

    if (config.enableSsl) {
      const key = fs.readFileSync(config.sslKeyPath!);
      const cert = fs.readFileSync(config.sslCertPath!);
      const ca = config.sslCaPath ? fs.readFileSync(config.sslCaPath) : undefined;

      const options: https.ServerOptions = { key, cert };
      if (ca) options.ca = ca;

      server = https.createServer(options, app);
    } else {
      server = http.createServer(app);
    }

    await new Promise<void>((resolve, reject) => {
      server!.once('error', reject);
      server!.listen(config.port, host, () => {
        server!.off('error', reject);
        resolve();
      });
    });

    return server!;
  }

  async function stop(): Promise<void> {
    if (!server) return;
    await new Promise<void>((resolve, reject) => {
      server!.close((err) => (err ? reject(err) : resolve()));
    });
    server = null;
  }

  return { app, start, stop };
}
