// services\services-server\src\mud-client-service.ts
import { v4 } from 'uuid';
import {
  IMudClientApp,
  IMudClientService,
  ITelnetClient,
  MudClientAppProps,
  MudClientServiceProps,
} from '@shatteredarchive/types-server';
import { TelnetClient } from './telnet-client-service.js';

export class MudClientApp implements IMudClientApp {
  private config: MudClientAppProps;
  private sessionId: string;
  private mudClient: IMudClientService;

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: constructor — Initializes client with configuration, generates unique session ID, and creates MUD service connection.
  // @ai-hash: 89a91fb8
  // ── END AI-METHOD ──
  constructor(props: MudClientAppProps) {
    this.config = props;
    this.sessionId = v4();
    this.mudClient = new MudClientService({
      host: props.host,
      port: props.port,
    });
  }

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: Config — Returns the current configuration object instance.
  // @ai-hash: 8dfbeedc
  // ── END AI-METHOD ──
  public get Config() {
    return this.config;
  }

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: SessionId — Returns the unique identifier for the current user session.
  // @ai-hash: ee80a9ac
  // ── END AI-METHOD ──
  public get SessionId() {
    return this.sessionId;
  }

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: MudClient — Returns the underlying MudClient instance for external access.
  // @ai-hash: bb72acaa
  // ── END AI-METHOD ──
  public get MudClient() {
    return this.mudClient;
  }
}

export class MudClientService implements IMudClientService {
  config: MudClientServiceProps;
  telnetClient: ITelnetClient;

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: constructor — Initializes telnet client with provided connection properties and default settings.
  // @ai-hash: 2e2dda86
  // ── END AI-METHOD ──
  constructor(props: MudClientServiceProps) {
    this.config = props;
    this.telnetClient = new TelnetClient({
      host: props.host,
      port: props.port,
      sendRate: 100,
      treatGoAheadAsNewline: true,
      promptFlushDelayMs: 120,
    });
  }

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: Config — Returns the current configuration object instance.
  // @ai-hash: 8dfbeedc
  // ── END AI-METHOD ──
  public get Config() {
    return this.config;
  }

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: TelnetClient — Returns the underlying Telnet client instance for network communication.
  // @ai-hash: 8157053a
  // ── END AI-METHOD ──
  public get TelnetClient() {
    return this.telnetClient;
  }
}
