// apps/game-client/src/components/CommandInput.tsx
import React, { useEffect, useRef, useState } from 'react';
import styles from '../styles/CommandInput.module.scss';
import { useGameCommand } from '../hooks/useGameCommand';
import { CommandInputProps } from '../types/chat-types/command-input-props';
import { DispatchEvent } from '../features/event-emitter/event-dispatcher';

export const CommandInput: React.FC<CommandInputProps> = ({
  sendRaw,
  isConnected,

  onOpenAutoLeveling,

  autoLevelMode,
  autoLevelRunState,
  onSightseeRescan,
}) => {
  const inputRef = useRef<HTMLInputElement | null>(null);
  const panelRef = useRef<HTMLDivElement | null>(null);

  const { inputValue, setInputValue, handleKeyDown } = useGameCommand({
    sendRaw,
    isConnected,
    inputRef,
  });

  const status = autoLevelRunState?.status ?? 'idle';
  const isRunning = status === 'running';
  const isPaused = status === 'paused';
  const isIdle = status === 'idle' || status === 'stopping';
  const sightseeStep = (autoLevelRunState as any)?.step ?? '';
  const isSightseeWaiting = isRunning && sightseeStep.startsWith('sightsee:waiting');
  const isSightseePrevAvailable = isRunning && sightseeStep === 'sightsee:waiting';

  const modeActive = !!autoLevelMode && autoLevelMode !== 'disabled';

  const [panelOpen, setPanelOpen] = useState(false);

  // Close panel on outside click
  useEffect(() => {
    if (!panelOpen) return;
    // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
    // @ai-method: handler — Closes panel when clicking outside its content area.
    // @ai-hash: 1e495540
    // ── END AI-METHOD ──
    const handler = (e: MouseEvent) => {
      if (panelRef.current && !panelRef.current.contains(e.target as Node)) {
        setPanelOpen(false);
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [panelOpen]);

  // Close panel when engine goes idle (run finished)
  useEffect(() => {
    if (isIdle) setPanelOpen(false);
  }, [isIdle]);

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: statusText — Returns formatted status text based on auto-level run state conditions.
  // @ai-hash: 8164f2ce
  // ── END AI-METHOD ──
  const statusText = () => {
    const s = autoLevelRunState?.status ?? 'idle';
    const round = (autoLevelRunState as any)?.round;
    const step = (autoLevelRunState as any)?.step ?? '';
    if (s === 'idle' || s === 'stopping') return 'Not running';
    if (s === 'waiting') return 'Waiting for next round';
    if (s === 'paused') return `Paused${round ? ` (round ${round})` : ''}`;
    if (s === 'error') return `Error: ${(autoLevelRunState as any).message}`;
    if (s === 'running') {
      if (step === 'sightsee:waiting') return `Ready — waiting for next step${round ? ` (round ${round})` : ''}`;
      if (step.includes('fight')) return `Fighting${round ? ` (round ${round})` : ''}`;
      if (step.includes('move')) return `Moving${round ? ` (round ${round})` : ''}`;
      return `Running${round ? ` (round ${round})` : ''}`;
    }
    return s;
  };

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: dispatch — Dispatches an event and closes the panel when called.
  // @ai-hash: fabc7a45
  // ── END AI-METHOD ──
  const dispatch = (event: string) => {
    DispatchEvent(event as any, {});
    setPanelOpen(false);
  };

  return (
    <div className={styles.commandInputBar}>
      <input
        ref={inputRef}
        id="game-command-input"
        className={styles.commandInput}
        type="text"
        // Mobile soft keyboards default to sentence-case; MUD commands are
        // case-sensitive, so let the user's keyboard decide the first letter's
        // case rather than auto-capitalizing / auto-correcting it.
        autoCapitalize="none"
        autoCorrect="off"
        autoComplete="off"
        //spellCheck={false}
        value={inputValue}
        onChange={(e) => setInputValue(e.target.value)}
        onKeyDown={handleKeyDown}
        placeholder={!isConnected ? 'Connect to a server to begin' : 'Type commands…'}
        disabled={!isConnected}
      />

      {modeActive ? (
        <div ref={panelRef} className={styles.autoLevelWrap}>
          <button
            type="button"
            className={`${styles.autoLevelButton} ${isRunning ? styles.autoLevelButtonActive : isPaused ? styles.autoLevelButtonPaused : ''}`}
            onMouseDown={(e) => e.preventDefault()}
            onClick={() => setPanelOpen((o) => !o)}
            disabled={!isConnected}
            aria-label="Auto leveling controls"
            title="Auto leveling controls"
          >
            ⚔️
          </button>

          {panelOpen ? (
            <div className={styles.autoLevelPanel}>
              <div className={styles.autoLevelPanelStatus}>{statusText()}</div>

              <div className={styles.autoLevelPanelRow}>
                {isIdle ? (
                  <button
                    className={styles.autoLevelPanelBtn}
                    onClick={() => dispatch('shatteredarchive:autoleveling-start')}
                    disabled={!isConnected}
                  >
                    ▶ Start
                  </button>
                ) : null}

                {isRunning ? (
                  <button
                    className={styles.autoLevelPanelBtn}
                    onClick={() => dispatch('shatteredarchive:autoleveling-pause')}
                  >
                    ⏸ Pause
                  </button>
                ) : null}

                {isPaused ? (
                  <button
                    className={styles.autoLevelPanelBtn}
                    onClick={() => dispatch('shatteredarchive:autoleveling-resume')}
                  >
                    ▶ Resume
                  </button>
                ) : null}

                {!isIdle ? (
                  <button
                    className={`${styles.autoLevelPanelBtn} ${styles.autoLevelPanelBtnStop}`}
                    onClick={() => dispatch('shatteredarchive:autoleveling-stop')}
                  >
                    ⏹ Stop
                  </button>
                ) : null}
              </div>

              {autoLevelMode === 'sightsee' && isRunning ? (
                <div className={styles.autoLevelPanelRow}>
                  <button
                    className={styles.autoLevelPanelBtn}
                    onClick={() => {
                      DispatchEvent('shatteredarchive:autoleveling-move-prev' as any, {});
                    }}
                    disabled={!isSightseePrevAvailable}
                    title={isSightseePrevAvailable ? 'Go back one room' : 'Nothing to go back to'}
                  >
                    ← Prev
                  </button>
                  <button
                    className={styles.autoLevelPanelBtn}
                    onClick={() => {
                      DispatchEvent('shatteredarchive:autoleveling-move-next' as any, {});
                    }}
                    disabled={!isSightseeWaiting}
                    title="Advance to next room"
                  >
                    Next →
                  </button>
                  <button
                    className={styles.autoLevelPanelBtn}
                    onClick={() => onSightseeRescan?.()}
                    disabled={!isSightseeWaiting}
                    title="Re-fire look/scan commands to refresh the room description"
                  >
                    🔍 Look
                  </button>
                </div>
              ) : null}

              {onOpenAutoLeveling ? (
                <div className={styles.autoLevelPanelRow}>
                  <button
                    className={styles.autoLevelPanelBtn}
                    onClick={() => {
                      setPanelOpen(false);
                      onOpenAutoLeveling();
                    }}
                  >
                    ⚙ Settings
                  </button>
                </div>
              ) : null}
            </div>
          ) : null}
        </div>
      ) : onOpenAutoLeveling ? (
        <button
          type="button"
          className={styles.autoConfigButton}
          onMouseDown={(e) => e.preventDefault()}
          onClick={() => onOpenAutoLeveling?.()}
          disabled={!isConnected}
          aria-label="Configure auto leveling"
          title="Configure auto leveling"
        >
          ⚙️
        </button>
      ) : null}

      {/* Show gear separately when mode active (it's inside the panel already) */}

      {/*
        Inert placeholder for the voice-dictation plugin. Hidden by default
        (see .micSlotHidden); the plugin unhides it by setting an inline
        display style directly on this element (an inline style always beats
        the .micSlotHidden class rule) and wires its own click handler +
        speech recognition directly against it (no React state here — see
        features/plugins/core-plugins/voice-dictation.plugin.ts).
      */}
      <button
        type="button"
        id="voice-dictation-mic-slot"
        className={`${styles.micButton} ${styles.micSlotHidden}`}
        disabled
        aria-hidden="true"
        tabIndex={-1}
      >
        🎤
      </button>
    </div>
  );
};

export default CommandInput;
