// apps\game-client\src\components\MainMenuBar.tsx
import React from 'react';
import styles from '../styles/MainMenuBar.module.scss';
import { useMainMenuBar } from '../hooks/useMainMenuBar';
import GraphicsSettingsModal from './GraphicsSettingsModal';
import AudioSettingsModal from './AudioSettingsModal';
import AccessibilitySettingsModal from './AccessibilitySettingsModal';

interface MainMenuBarProps {
  onOpenCustomStyles: () => void;
  onOpenScriptSandbox: () => void;
  onOpenConnect: () => void;
  onOpenPlugins: () => void;
  onOpenLibrary: () => void;
  onOpenEquipment: () => void;
  onOpenAutoLeveling: () => void;
  onOpenIdentifyObject: () => void;
  onOpenCreatureLore: () => void;
  onOpenScriptingHelp: () => void;
}

export const MainMenuBar: React.FC<MainMenuBarProps> = ({
  onOpenCustomStyles,
  onOpenScriptSandbox,
  onOpenConnect,
  onOpenPlugins,
  onOpenLibrary,
  onOpenEquipment,
  onOpenAutoLeveling,
  onOpenIdentifyObject,
  onOpenCreatureLore,
  onOpenScriptingHelp,
}) => {
  const {
    openRootMenu,
    isGameSettingsOpen,
    toggleRootMenu,
    toggleGameSettings,
    closeAllMenus,

    isGraphicsModalOpen,
    openGraphicsModal,
    closeGraphicsModal,

    isAudioModalOpen,
    openAudioModal,
    closeAudioModal,

    isAccessibilityModalOpen,
    openAccessibilityModal,
    closeAccessibilityModal,
  } = useMainMenuBar();

  const rootRef = React.useRef<HTMLDivElement | null>(null);

  React.useEffect(() => {
    // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
    // @ai-method: handleWindowClick — Closes all menus when clicking outside the root element.
    // @ai-hash: 9c5ad7b3
    // ── END AI-METHOD ──
    const handleWindowClick = (ev: MouseEvent) => {
      const root = rootRef.current;
      if (!root) return;
      if (ev.target instanceof Node && root.contains(ev.target)) return;
      closeAllMenus();
    };

    window.addEventListener('click', handleWindowClick);
    return () => window.removeEventListener('click', handleWindowClick);
  }, [closeAllMenus]);

  return (
    <>
      <div ref={rootRef} className={styles.menuBar}>
        {/* File */}
        <div className={`${styles.menuItem} ${styles.menuItemHasSubmenu}`} onClick={() => toggleRootMenu('File')}>
          File
          <div className={`${styles.subMenu} ${openRootMenu === 'File' ? styles.subMenuOpen : ''}`}>
            <div
              className={styles.subMenuItem}
              onClick={(e) => {
                e.stopPropagation();
                closeAllMenus();
                onOpenConnect();
              }}
            >
              Connect…
            </div>
          </div>
        </div>

        {/* Game */}
        <div className={`${styles.menuItem} ${styles.menuItemHasSubmenu}`} onClick={() => toggleRootMenu('Game')}>
          Game
          <div className={`${styles.subMenu} ${openRootMenu === 'Game' ? styles.subMenuOpen : ''}`}>
            <div className={`${styles.subMenuItem} ${styles.subMenuItemHasSubmenu}`} onClick={toggleGameSettings}>
              Settings
              <div className={`${styles.subMenuLevel2} ${isGameSettingsOpen ? styles.subMenuOpen : ''}`}>
                <div className={styles.subMenuItem} onClick={openAudioModal}>
                  Audio…
                </div>

                <div className={styles.subMenuItem} onClick={openAccessibilityModal}>
                  Accessibility…
                </div>
              </div>
            </div>

            <div
              className={styles.subMenuItem}
              onClick={(e) => {
                e.stopPropagation();
                closeAllMenus();
                onOpenScriptSandbox();
              }}
            >
              Script Sandbox…
            </div>

            <div
              className={styles.subMenuItem}
              onClick={(e) => {
                e.stopPropagation();
                closeAllMenus();
                onOpenCustomStyles();
              }}
            >
              Custom Styles…
            </div>

            <div
              className={styles.subMenuItem}
              onClick={(e) => {
                e.stopPropagation();
                closeAllMenus();
                onOpenLibrary();
              }}
            >
              Library (Notes & Books)…
            </div>
            <div
              className={styles.subMenuItem}
              onClick={(e) => {
                e.stopPropagation();
                closeAllMenus();
                onOpenEquipment();
              }}
            >
              Equipment…
            </div>

            <div
              className={styles.subMenuItem}
              onClick={(e) => {
                e.stopPropagation();
                closeAllMenus();
                onOpenAutoLeveling();
              }}
            >
              Autopilot…
            </div>
          </div>
        </div>

        {/* Plugins */}
        <div className={`${styles.menuItem} ${styles.menuItemHasSubmenu}`} onClick={() => toggleRootMenu('Plugins')}>
          Plugins
          <div className={`${styles.subMenu} ${openRootMenu === 'Plugins' ? styles.subMenuOpen : ''}`}>
            <div
              className={styles.subMenuItem}
              onClick={(e) => {
                e.stopPropagation();
                closeAllMenus();
                onOpenPlugins();
              }}
            >
              Manage Plugins…
            </div>
          </div>
        </div>

        {/* ✅ NEW: Contribute */}
        <div className={`${styles.menuItem} ${styles.menuItemHasSubmenu}`} onClick={() => toggleRootMenu('Contribute')}>
          Contribute
          <div className={`${styles.subMenu} ${openRootMenu === 'Contribute' ? styles.subMenuOpen : ''}`}>
            <div
              className={styles.subMenuItem}
              onClick={(e) => {
                e.stopPropagation();
                closeAllMenus();
                onOpenIdentifyObject();
              }}
            >
              Identify Object…
            </div>

            <div
              className={styles.subMenuItem}
              onClick={(e) => {
                e.stopPropagation();
                closeAllMenus();
                onOpenCreatureLore();
              }}
            >
              Creature Lore…
            </div>
          </div>
        </div>

        {/* External */}
        <div className={`${styles.menuItem} ${styles.menuItemHasSubmenu}`} onClick={() => toggleRootMenu('External')}>
          External
          <div className={`${styles.subMenu} ${openRootMenu === 'External' ? styles.subMenuOpen : ''}`}>
            <a
              className={`${styles.subMenuItem} ${styles.subMenuLink}`}
              href="https://shatteredarchive.com/"
              target="_blank"
              rel="noopener noreferrer"
              onClick={(e) => e.stopPropagation()}
            >
              Open Shattered Archive
            </a>
            <a
              className={`${styles.subMenuItem} ${styles.subMenuLink}`}
              href="https://github.com/TournyMasterBot/Shattered-Archive"
              target="_blank"
              rel="noopener noreferrer"
              onClick={(e) => e.stopPropagation()}
            >
              Github
            </a>
          </div>
        </div>

        {/* Help */}
        <div className={`${styles.menuItem} ${styles.menuItemHasSubmenu}`} onClick={() => toggleRootMenu('Help')}>
          Help
          <div className={`${styles.subMenu} ${openRootMenu === 'Help' ? styles.subMenuOpen : ''}`}>
            <div
              className={styles.subMenuItem}
              onClick={(e) => {
                e.stopPropagation();
                closeAllMenus();
                onOpenScriptingHelp();
              }}
            >
              Scripting…
            </div>
            <a
              className={`${styles.subMenuItem} ${styles.subMenuLink}`}
              href="https://github.com/sponsors/TournyMasterBot"
              target="_blank"
              rel="noopener noreferrer"
              onClick={(e) => e.stopPropagation()}
            >
              Sponsor
            </a>
            <a
              className={`${styles.subMenuItem} ${styles.subMenuLink}`}
              href="https://github.com/TournyMasterBot/Shattered-Archive/issues"
              target="_blank"
              rel="noopener noreferrer"
              onClick={(e) => e.stopPropagation()}
            >
              Report Bug
            </a>
            <a
              className={`${styles.subMenuItem} ${styles.subMenuLink}`}
              href="https://github.com/TournyMasterBot/Shattered-Archive/issues"
              target="_blank"
              rel="noopener noreferrer"
              onClick={(e) => e.stopPropagation()}
            >
              Request Feature
            </a>
          </div>
        </div>
      </div>

      {/* Render modal outside the menu DOM so it isn't clipped */}
      <GraphicsSettingsModal isOpen={isGraphicsModalOpen} onClose={closeGraphicsModal} />
      <AudioSettingsModal isOpen={isAudioModalOpen} onClose={closeAudioModal} />
      <AccessibilitySettingsModal isOpen={isAccessibilityModalOpen} onClose={closeAccessibilityModal} />
    </>
  );
};
