// apps/game-client/src/components/RoomHeader.tsx
import React from 'react';
import styles from '../styles/LayoutShell.module.scss';
import { useRoomHeader } from '../hooks/useRoomHeader';

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: RoomHeader — Displays room name and flags in a styled header component.
// @ai-hash: 51ca31bf
// ── END AI-METHOD ──
export const RoomHeader: React.FC = () => {
  const { roomName, roomFlags } = useRoomHeader();

  return (
    <div className={styles.roomHeader}>
      <div className={styles.roomTitle}>{roomName || ''}</div>
      <div className={styles.roomSubtitle}>{roomFlags}</div>
    </div>
  );
};

export default RoomHeader;
