import type {
  Action,
  AttackAction,
  AbilityAction,
  BoardToken,
  Coord,
  EndTurnAction,
  MatchState,
  MoveAction,
  SetStanceAction,
  Side,
} from '../model/index.js';
import type { ISeededRng } from '../rng/index.js';
import type { IGameDataProvider, IGameModeProvider } from '../data/index.js';
import { isStanceLegalFor, resolveAbilityMechanics } from '../data/index.js';
import {
  applyAbility,
  applyAttack,
  chebyshev,
  coordEquals,
  evaluateVictory,
  legalMoves,
  legalTargets,
  nextActiveSide,
  templateForMember,
  type AbilitySpec,
  type CombatHooks,
} from '../rules/index.js';

/**
 * The provider bundle the reducer needs. `data` + `modes` are the Phase-1/2 providers;
 * the two optional hooks are the v1 seams for content that is NOT part of the action
 * economy (see plan p3, decisions 3 + 6):
 *  - `abilityResolver` turns an `abilityKey` into a castable `AbilitySpec` (no catalog in
 *    v1, so abilities are a no-op unless a resolver is supplied);
 *  - `triggers` fires once AFTER each applied non-end-turn action for passive/aura/banter
 *    effects — coarse (per-action), distinct from the fine per-hit combat reactions that
 *    live in the damage layer.
 *  - `combatHooks` are those FINE per-hit reactions (dodge/parry/block, typed shields, thorns);
 *    absent ⇒ Phase-2b damage unchanged. `combatRng` supplies the SERVER-ONLY salted, step-counted
 *    stream those hooks roll against — when present the reducer sources the hooks' rng from it (per
 *    action) instead of the public `MatchState.rngState`, so a client cannot predict avoidance.
 *    Only the server supplies these (see the combat-reactions plan); pure engine/sim use omits them.
 */
export interface EngineProviders {
  readonly data: IGameDataProvider;
  readonly modes: IGameModeProvider;
  readonly abilityResolver?: (key: string) => AbilitySpec | undefined;
  readonly triggers?: (
    state: MatchState,
    ev: { readonly type: 'post-action'; readonly action: Action },
  ) => MatchState;
  readonly combatHooks?: CombatHooks;
  readonly combatRng?: (state: MatchState, action: Action) => ISeededRng;
}

/**
 * The rng the combat hooks roll against for THIS action: the server-only salted `combatRng`
 * stream when supplied, else the public `rng` (fine for pure engine tests). Only consulted when
 * `combatHooks` is present, so the default (hooks absent) path never touches it.
 */
function combatRngFor(
  state: MatchState,
  action: Action,
  rng: ISeededRng,
  p: EngineProviders,
): ISeededRng {
  return p.combatRng ? p.combatRng(state, action) : rng;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: isLiving — (no summary)
// @ai-hash: ec0ca154
// ── END AI-METHOD ──
/** A living token = unit with hp > 0 / squadron with hpPool > 0. */
function isLiving(t: BoardToken): boolean {
  return t.kind === 'unit' ? t.hp > 0 : t.hpPool > 0;
}

/**
 * One-unit-per-turn lock: once the active side has activated a token this turn
 * (`activatedTokenId`), every OTHER token is locked out until the turn passes.
 */
function isLockedOut(state: MatchState, tokenId: string): boolean {
  return state.activatedTokenId !== undefined && state.activatedTokenId !== tokenId;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: moveToken — (no summary)
// @ai-hash: 6c3db95a
// ── END AI-METHOD ──
/** Move a token to a new tile, consuming its MOVE budget (leaves hasActed alone). */
const moveToken = (t: BoardToken, to: Coord): BoardToken =>
  t.kind === 'unit'
    ? { ...t, pos: to, hasMoved: true }
    : { ...t, pos: to, hasMoved: true };

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: resetFlags — (no summary)
// @ai-hash: 13253d5e
// ── END AI-METHOD ──
/** Clear BOTH per-turn budgets on a token (used when a side's turn begins). */
const resetFlags = (t: BoardToken): BoardToken =>
  t.kind === 'unit'
    ? { ...t, hasMoved: false, hasActed: false }
    : { ...t, hasMoved: false, hasActed: false };

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: finalize — (no summary)
// @ai-hash: d58e1dbf
// ── END AI-METHOD ──
/**
 * Persist the RNG state and re-check victory. Called after every applied action
 * (including end-turn — victory is re-checked every action per plan decision 2).
 */
function finalize(state: MatchState, rng: ISeededRng, p: EngineProviders): MatchState {
  const withRng: MatchState = { ...state, rngState: rng.state() };
  const victory = evaluateVictory(withRng, p.modes.mode(withRng.modeId), p.data);
  if (victory.decided) {
    return { ...withRng, status: 'decided', winner: victory.winner };
  }
  return withRng;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: afterAction — (no summary)
// @ai-hash: b487d19e
// ── END AI-METHOD ──
/** Run the passive/aura trigger hook (if any), then finalize. For real actions only. */
function afterAction(
  state: MatchState,
  action: Action,
  rng: ISeededRng,
  p: EngineProviders,
): MatchState {
  const triggered = p.triggers ? p.triggers(state, { type: 'post-action', action }) : state;
  return finalize(triggered, rng, p);
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: applyMove — (no summary)
// @ai-hash: 901ec49e
// ── END AI-METHOD ──
function applyMove(
  state: MatchState,
  action: MoveAction,
  rng: ISeededRng,
  p: EngineProviders,
): MatchState {
  const token = state.tokens.find((t) => t.instanceId === action.tokenId);
  if (!token) return state;
  if (token.side !== state.activeSide) return state;
  if (!isLiving(token)) return state;
  if (isLockedOut(state, action.tokenId)) return state; // one-unit-per-turn lock
  if (token.hasMoved) return state;
  if (!legalMoves(state, action.tokenId, p.data).some((c) => coordEquals(c, action.to))) {
    return state;
  }
  const tokens = state.tokens.map((t) =>
    t.instanceId === action.tokenId ? moveToken(t, action.to) : t,
  );
  return afterAction({ ...state, tokens, activatedTokenId: action.tokenId }, action, rng, p);
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: applyAttackAction — (no summary)
// @ai-hash: 88d6d453
// ── END AI-METHOD ──
function applyAttackAction(
  state: MatchState,
  action: AttackAction,
  rng: ISeededRng,
  p: EngineProviders,
): MatchState {
  const token = state.tokens.find((t) => t.instanceId === action.tokenId);
  if (!token) return state;
  if (token.side !== state.activeSide) return state;
  if (!isLiving(token)) return state;
  if (isLockedOut(state, action.tokenId)) return state; // one-unit-per-turn lock
  if (token.hasActed) return state;
  // applyAttack validates legalTargets + resolves damage + sets hasActed (preserving
  // hasMoved since it only spreads the token). Illegal target → same ref → no-op.
  // Opt-in per-hit reactions: pass combatHooks + the server-only salted stream when supplied.
  const hookRng = p.combatHooks ? combatRngFor(state, action, rng, p) : rng;
  const next = applyAttack(state, action.tokenId, action.targetId, p.data, hookRng, p.combatHooks);
  if (next === state) return state;
  return afterAction({ ...next, activatedTokenId: action.tokenId }, action, rng, p);
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: applyAbilityAction — (no summary)
// @ai-hash: 658308be
// ── END AI-METHOD ──
function applyAbilityAction(
  state: MatchState,
  action: AbilityAction,
  rng: ISeededRng,
  p: EngineProviders,
): MatchState {
  const token = state.tokens.find((t) => t.instanceId === action.tokenId);
  if (!token) return state;
  if (token.side !== state.activeSide) return state;
  if (!isLiving(token)) return state;
  if (isLockedOut(state, action.tokenId)) return state; // one-unit-per-turn lock
  if (token.hasActed) return state;
  // v1: abilities are a no-op unless a resolver maps the key AND a token target is given.
  if (!p.abilityResolver || typeof action.target !== 'string') return state;
  const spec = p.abilityResolver(action.abilityKey);
  if (!spec) return state;
  const hookRng = p.combatHooks ? combatRngFor(state, action, rng, p) : rng;
  const next = applyAbility(state, action.tokenId, action.target, spec, p.data, hookRng, p.combatHooks);
  if (next === state) return state;
  return afterAction({ ...next, activatedTokenId: action.tokenId }, action, rng, p);
}

/**
 * Set a unit's combat stance — a FREE minor action. Unlike move/attack/ability it does NOT
 * consume `hasMoved`/`hasActed`, does NOT set `activatedTokenId`, and is EXEMPT from the
 * one-unit-per-turn lock: a player may re-stance any/all of their own living units, then still
 * activate one to move + attack. Only the ACTIVE side's own living UNIT tokens (squadrons are
 * stanceless), and only stances legal for the unit's class (Brewmaster stances gated to Brewmasters).
 */
function applySetStance(
  state: MatchState,
  action: SetStanceAction,
  rng: ISeededRng,
  p: EngineProviders,
): MatchState {
  const token = state.tokens.find((t) => t.instanceId === action.tokenId);
  if (!token) return state;
  if (token.kind !== 'unit') return state; // stances are per-unit
  if (token.side !== state.activeSide) return state; // your own units, on your turn only
  if (!isLiving(token)) return state;
  const classKey = token.templateId.split(':')[1] ?? '';
  if (!isStanceLegalFor(action.stance, classKey)) return state;
  if (token.stance === action.stance) return state; // no-op change
  const tokens = state.tokens.map((t) =>
    t.instanceId === action.tokenId && t.kind === 'unit' ? { ...t, stance: action.stance } : t,
  );
  // Free minor action: no activatedTokenId, no trigger hook — just persist + re-check victory.
  return finalize({ ...state, tokens }, rng, p);
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: applyEndTurn — (no summary)
// @ai-hash: 3474a324
// ── END AI-METHOD ──
function applyEndTurn(
  state: MatchState,
  action: EndTurnAction,
  rng: ISeededRng,
  p: EngineProviders,
): MatchState {
  if (action.side !== state.activeSide) return state;
  const next = nextActiveSide(state);
  // Fresh budgets for the incoming side's living tokens.
  const tokens = state.tokens.map((t) =>
    t.side === next && isLiving(t) ? resetFlags(t) : t,
  );
  // A full round completes when play wraps back to the lowest living side.
  const livingSides = new Set<Side>();
  for (const t of tokens) if (isLiving(t)) livingSides.add(t.side);
  const wrapped = livingSides.size > 0 && next === Math.min(...livingSides);
  const advanced: MatchState = {
    ...state,
    tokens,
    activeSide: next,
    activatedTokenId: undefined, // the new side hasn't activated a unit yet
    turn: wrapped ? state.turn + 1 : state.turn,
  };
  // No trigger hook on end-turn (it is not a "post-action" event); victory still re-checked.
  return finalize(advanced, rng, p);
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: applyAction — (no summary)
// @ai-hash: fd3258a8
// ── END AI-METHOD ──
/**
 * The deterministic reducer: apply one `Action` to a `MatchState` and return the NEW
 * state. Pure — never mutates the input, no wall-clock, no I/O; all randomness comes
 * from `rng` and is captured back into `rngState`. Illegal actions (wrong side, spent
 * budget, illegal destination/target, unknown ability) return the input unchanged.
 * See plan p3, decisions 1–6 for the turn semantics.
 */
export function applyAction(
  state: MatchState,
  action: Action,
  rng: ISeededRng,
  p: EngineProviders,
): MatchState {
  if (state.status === 'decided') return state;
  switch (action.type) {
    case 'move':
      return applyMove(state, action, rng, p);
    case 'attack':
      return applyAttackAction(state, action, rng, p);
    case 'ability':
      return applyAbilityAction(state, action, rng, p);
    case 'set-stance':
      return applySetStance(state, action, rng, p);
    case 'end-turn':
      return applyEndTurn(state, action, rng, p);
    default:
      return state;
  }
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: legalActions — (no summary)
// @ai-hash: d2782b74
// ── END AI-METHOD ──
/**
 * The action space for `side`: for each living token, a `move` to every legal
 * destination (if it still has its MOVE) and an `attack` on every legal target (if it
 * still has its ACTION). `end-turn` is always appended last. Abilities are omitted in
 * v1 (no catalog). This is what AI policies and the UI enumerate.
 *
 * One-unit-per-turn: once the active side has activated a token (`state.activatedTokenId`),
 * only that token's actions are listed — every other unit is locked until the turn passes.
 */
export function legalActions(state: MatchState, side: Side, p: EngineProviders): Action[] {
  const actions: Action[] = [];
  for (const token of state.tokens) {
    if (token.side !== side) continue;
    if (!isLiving(token)) continue;
    // One-unit-per-turn: once the active side has activated a unit, only it may act.
    if (side === state.activeSide && isLockedOut(state, token.instanceId)) continue;
    if (!token.hasMoved) {
      for (const to of legalMoves(state, token.instanceId, p.data)) {
        actions.push({ type: 'move', tokenId: token.instanceId, to });
      }
    }
    if (!token.hasActed) {
      for (const targetId of legalTargets(state, token.instanceId, p.data)) {
        actions.push({ type: 'attack', tokenId: token.instanceId, targetId });
      }
    }
  }
  actions.push({ type: 'end-turn', side });
  return actions;
}

/**
 * The castable ABILITY actions for a single token — a UI-facing enumeration. Like `set-stance`,
 * abilities are reducer-accepted but deliberately NOT part of `legalActions`' AI/sim action space
 * in v1 (so seeded sims/AI stay unchanged); the client lists them separately to drive a cast panel.
 *
 * For a living token on the ACTIVE side that still has its ACTION and isn't locked out, returns one
 * `AbilityAction` per (authored active ability the token's template grants) × (valid recipient):
 * a 'self' ability targets the caster; an 'ally' ability targets every living friendly token
 * (including the caster — a cleric may cure itself); an 'enemy' (offensive) ability targets every
 * living enemy within its effective reach — the ability's own `range` if authored, else the
 * caster's weapon range (Chebyshev tiles) — so an out-of-range foe is not offered.
 */
export function legalAbilityActions(
  state: MatchState,
  tokenId: string,
  p: EngineProviders,
): AbilityAction[] {
  const token = state.tokens.find((t) => t.instanceId === tokenId);
  if (!token || token.side !== state.activeSide) return [];
  if (!isLiving(token) || isLockedOut(state, tokenId) || token.hasActed) return [];

  const templateId = token.kind === 'unit' ? token.templateId : token.members[0].templateId;
  const template = templateForMember(templateId, p.data);
  const abilities = template.abilities;
  const friendly = state.tokens.filter((t) => t.side === token.side && isLiving(t));
  const enemies = state.tokens.filter((t) => t.side !== token.side && isLiving(t));

  const actions: AbilityAction[] = [];
  for (const key of abilities) {
    const m = resolveAbilityMechanics(key);
    if (m.status !== 'authored' || m.usage !== 'active') continue;
    if (m.targeting === 'self') {
      actions.push({ type: 'ability', tokenId, abilityKey: key, target: tokenId });
    } else if (m.targeting === 'ally') {
      for (const ally of friendly) {
        actions.push({ type: 'ability', tokenId, abilityKey: key, target: ally.instanceId });
      }
    } else {
      // 'enemy': one action per LIVING enemy within the ability's effective reach —
      // its own `range` if authored, else the caster's weapon range (Chebyshev tiles).
      const reach = m.range ?? template.attack.range;
      for (const enemy of enemies) {
        if (chebyshev(token.pos, enemy.pos) <= reach) {
          actions.push({ type: 'ability', tokenId, abilityKey: key, target: enemy.instanceId });
        }
      }
    }
  }
  return actions;
}

/** Thin OO facade over the pure functions, carrying the provider bundle. */
export interface IGameEngine {
  apply(state: MatchState, action: Action, rng: ISeededRng): MatchState;
  legalActions(state: MatchState, side: Side): Action[];
}

/** Convenience wrapper so callers can bind the providers once. */
export class GameEngine implements IGameEngine {
  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: constructor — (no summary)
  // @ai-hash: 5823a661
  // ── END AI-METHOD ──
  constructor(private readonly providers: EngineProviders) {}

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: apply — (no summary)
  // @ai-hash: ace1cd90
  // ── END AI-METHOD ──
  apply(state: MatchState, action: Action, rng: ISeededRng): MatchState {
    return applyAction(state, action, rng, this.providers);
  }

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: legalActions — (no summary)
  // @ai-hash: 460ceda0
  // ── END AI-METHOD ──
  legalActions(state: MatchState, side: Side): Action[] {
    return legalActions(state, side, this.providers);
  }
}
