import { createGameDataProvider, createGameModeProvider } from '../data/index.js';
import type { Board, Coord, MatchState, Tile, Unit } from '../model/index.js';
import { createRng, type ISeededRng } from '../rng/index.js';
import { defaultCombatHooks, legalMoves } from '../rules/index.js';
import { applyAction, legalActions, legalAbilityActions, type EngineProviders } from './game-engine.js';

const providers: EngineProviders = {
  data: createGameDataProvider(),
  modes: createGameModeProvider(),
};

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: board — (no summary)
// @ai-hash: dec4a33d
// ── END AI-METHOD ──
function board(w: number, h: number): Board {
  const tiles: Tile[][] = [];
  for (let y = 0; y < h; y++) {
    const row: Tile[] = [];
    for (let x = 0; x < w; x++) row.push({ terrain: 'Field', feature: null });
    tiles.push(row);
  }
  return { width: w, height: h, tiles };
}

function unit(
  instanceId: string,
  templateId: string,
  pos: Coord,
  side: number,
  over: Partial<Unit> = {},
): Unit {
  return {
    kind: 'unit',
    instanceId,
    templateId,
    side,
    pos,
    hp: 999,
    statuses: [],
    hasMoved: false,
    hasActed: false,
    ...over,
  };
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: state — (no summary)
// @ai-hash: 191e186a
// ── END AI-METHOD ──
function state(tokens: Unit[], over: Partial<MatchState> = {}): MatchState {
  return {
    modeId: 'skirmish', // victory: 'rout'
    board: board(10, 10),
    armies: [],
    tokens,
    turn: 1,
    activeSide: 0,
    moon: { gameHour: 0, sky: { Black: 'HalfMoon', Red: 'HalfMoon', White: 'HalfMoon' } },
    rngState: 1,
    status: 'in-progress',
    ...over,
  };
}

const rng = () => createRng(1);

describe('applyAction — move', () => {
  it('rejects an illegal (out-of-range) move, returning the input unchanged', () => {
    const s = state([unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0)]);
    const next = applyAction(s, { type: 'move', tokenId: 'a', to: { x: 0, y: 0 } }, rng(), providers);
    expect(next).toBe(s);
  });

  it('a legal move sets pos + hasMoved but leaves hasActed false (action still available)', () => {
    const s = state([unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0)]);
    const dest = { x: 6, y: 5 };
    expect(legalMoves(s, 'a', providers.data).some((c) => c.x === dest.x && c.y === dest.y)).toBe(true);

    const next = applyAction(s, { type: 'move', tokenId: 'a', to: dest }, rng(), providers);
    const a = next.tokens.find((t) => t.instanceId === 'a') as Unit;
    expect(a.pos).toEqual(dest);
    expect(a.hasMoved).toBe(true);
    expect(a.hasActed).toBe(false);
  });

  it('does not mutate the input state (purity)', () => {
    const s = state([unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0)]);
    applyAction(s, { type: 'move', tokenId: 'a', to: { x: 6, y: 5 } }, rng(), providers);
    const a = s.tokens.find((t) => t.instanceId === 'a') as Unit;
    expect(a.pos).toEqual({ x: 5, y: 5 });
    expect(a.hasMoved).toBe(false);
  });
});

describe('applyAction — dual budget (move AND action in one turn)', () => {
  it('a token can move THEN attack in the same turn (both flags set)', () => {
    const s = state([
      unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0),
      unit('d', 'Human:Warrior', { x: 7, y: 5 }, 1),
    ]);
    const s1 = applyAction(s, { type: 'move', tokenId: 'a', to: { x: 6, y: 5 } }, rng(), providers);
    const s2 = applyAction(s1, { type: 'attack', tokenId: 'a', targetId: 'd' }, rng(), providers);

    const a = s2.tokens.find((t) => t.instanceId === 'a') as Unit;
    const d = s2.tokens.find((t) => t.instanceId === 'd') as Unit;
    expect(a.pos).toEqual({ x: 6, y: 5 });
    expect(a.hasMoved).toBe(true);
    expect(a.hasActed).toBe(true);
    expect(d.hp).toBeLessThan(999);
  });
});

describe('applyAction — one unit per turn', () => {
  it('locks every other unit once the side activates one', () => {
    const s = state([
      unit('a', 'Human:Warrior', { x: 5, y: 9 }, 0),
      unit('b', 'Human:Warrior', { x: 7, y: 9 }, 0),
    ]);
    const afterA = applyAction(s, { type: 'move', tokenId: 'a', to: { x: 5, y: 7 } }, rng(), providers);
    expect(afterA).not.toBe(s);
    expect(afterA.activatedTokenId).toBe('a');

    // 'b' is locked: its move is a no-op and it exposes no legal actions.
    const tryB = applyAction(afterA, { type: 'move', tokenId: 'b', to: { x: 7, y: 7 } }, rng(), providers);
    expect(tryB).toBe(afterA);
    const acts = legalActions(afterA, 0, providers);
    expect(acts.some((x) => 'tokenId' in x && x.tokenId === 'b')).toBe(false);
    expect(acts.some((x) => x.type === 'end-turn')).toBe(true);
  });

  it('lets the activated unit both move and attack (but not other units)', () => {
    const s = state([
      unit('a', 'Human:Warrior', { x: 5, y: 9 }, 0),
      unit('b', 'Human:Warrior', { x: 7, y: 9 }, 0),
      unit('e', 'Human:Warrior', { x: 5, y: 8 }, 1),
    ]);
    const afterAtk = applyAction(s, { type: 'attack', tokenId: 'a', targetId: 'e' }, rng(), providers);
    expect(afterAtk.activatedTokenId).toBe('a');

    const afterMove = applyAction(afterAtk, { type: 'move', tokenId: 'a', to: { x: 4, y: 9 } }, rng(), providers);
    expect(afterMove).not.toBe(afterAtk); // same unit may still move after attacking

    const tryB = applyAction(afterMove, { type: 'move', tokenId: 'b', to: { x: 7, y: 7 } }, rng(), providers);
    expect(tryB).toBe(afterMove); // other unit stays locked
  });

  it('clears the lock when the turn passes', () => {
    const s = state([
      unit('a', 'Human:Warrior', { x: 5, y: 9 }, 0),
      unit('d', 'Human:Warrior', { x: 5, y: 0 }, 1),
    ]);
    const afterA = applyAction(s, { type: 'move', tokenId: 'a', to: { x: 5, y: 7 } }, rng(), providers);
    const afterEnd = applyAction(afterA, { type: 'end-turn', side: 0 }, rng(), providers);
    expect(afterEnd.activeSide).toBe(1);
    expect(afterEnd.activatedTokenId).toBeUndefined();
    expect(legalActions(afterEnd, 1, providers).some((x) => 'tokenId' in x && x.tokenId === 'd')).toBe(true);
  });
});

describe('legalActions — independent budgets', () => {
  it('offers a moved-but-not-acted token attacks (but no moves)', () => {
    const s = state([
      unit('b', 'Human:Warrior', { x: 5, y: 5 }, 0, { hasMoved: true }),
      unit('d', 'Human:Warrior', { x: 6, y: 5 }, 1),
    ]);
    const acts = legalActions(s, 0, providers);
    const forB = acts.filter((a) => a.type !== 'end-turn' && 'tokenId' in a && a.tokenId === 'b');
    expect(forB.some((a) => a.type === 'attack')).toBe(true);
    expect(forB.some((a) => a.type === 'move')).toBe(false);
  });

  it('offers an acted-but-not-moved token moves (but no attacks)', () => {
    const s = state([
      unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0, { hasActed: true }),
      unit('d', 'Human:Warrior', { x: 6, y: 5 }, 1),
    ]);
    const acts = legalActions(s, 0, providers);
    const forA = acts.filter((a) => a.type !== 'end-turn' && 'tokenId' in a && a.tokenId === 'a');
    expect(forA.some((a) => a.type === 'move')).toBe(true);
    expect(forA.some((a) => a.type === 'attack')).toBe(false);
  });

  it('always appends a single end-turn action', () => {
    const s = state([unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0)]);
    const acts = legalActions(s, 0, providers);
    expect(acts.filter((a) => a.type === 'end-turn')).toHaveLength(1);
  });

  it('never enumerates ability actions (UI-driven, like set-stance)', () => {
    const s = state([unit('cl', 'Human:Cleric', { x: 5, y: 5 }, 0)]);
    expect(legalActions(s, 0, providers).some((a) => a.type === 'ability')).toBe(false);
  });
});

describe('legalAbilityActions (UI-facing ability enumeration)', () => {
  it('offers a Cleric its cure on every living ally — including itself — but never an enemy', () => {
    const s = state([
      unit('cl', 'Human:Cleric', { x: 5, y: 5 }, 0),
      unit('al', 'Human:Warrior', { x: 6, y: 5 }, 0),
      unit('en', 'Human:Warrior', { x: 7, y: 5 }, 1),
    ]);
    const cure = legalAbilityActions(s, 'cl', providers).filter((a) => a.abilityKey === 'CureLight');
    const targets = new Set(cure.map((a) => a.target));
    expect(targets.has('cl')).toBe(true); // a cleric may cure itself
    expect(targets.has('al')).toBe(true); // and any ally
    expect(targets.has('en')).toBe(false); // never an enemy
  });

  it('is empty once the unit has taken its action', () => {
    const s = state([unit('cl', 'Human:Cleric', { x: 5, y: 5 }, 0, { hasActed: true })]);
    expect(legalAbilityActions(s, 'cl', providers)).toEqual([]);
  });

  it('is empty for a locked-out unit (one-unit-per-turn)', () => {
    const s = state(
      [unit('cl', 'Human:Cleric', { x: 5, y: 5 }, 0), unit('al', 'Human:Cleric', { x: 6, y: 5 }, 0)],
      { activatedTokenId: 'al' },
    );
    expect(legalAbilityActions(s, 'cl', providers)).toEqual([]);
  });
});

describe('applyAction — attack', () => {
  it('reduces the target hp through the reducer and marks the attacker acted', () => {
    const s = state([
      unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0),
      unit('d', 'Human:Warrior', { x: 6, y: 5 }, 1),
    ]);
    const next = applyAction(s, { type: 'attack', tokenId: 'a', targetId: 'd' }, rng(), providers);
    const a = next.tokens.find((t) => t.instanceId === 'a') as Unit;
    const d = next.tokens.find((t) => t.instanceId === 'd') as Unit;
    expect(d.hp).toBeLessThan(999);
    expect(a.hasActed).toBe(true);
  });

  it('a killing blow flips status to decided with the surviving side as winner', () => {
    const s = state([
      unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0),
      unit('d', 'Human:Warrior', { x: 6, y: 5 }, 1, { hp: 1 }),
    ]);
    const next = applyAction(s, { type: 'attack', tokenId: 'a', targetId: 'd' }, rng(), providers);
    const d = next.tokens.find((t) => t.instanceId === 'd') as Unit;
    expect(d.hp).toBe(0);
    expect(next.status).toBe('decided');
    expect(next.winner).toBe(0);
  });
});

describe('applyAction — end-turn', () => {
  it('advances activeSide and resets BOTH flags on the incoming side only', () => {
    const s = state([
      unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0, { hasMoved: true, hasActed: true }),
      unit('d', 'Human:Warrior', { x: 8, y: 8 }, 1, { hasMoved: true, hasActed: true }),
    ]);
    const next = applyAction(s, { type: 'end-turn', side: 0 }, rng(), providers);
    const a = next.tokens.find((t) => t.instanceId === 'a') as Unit;
    const d = next.tokens.find((t) => t.instanceId === 'd') as Unit;
    expect(next.activeSide).toBe(1);
    expect(d.hasMoved).toBe(false);
    expect(d.hasActed).toBe(false);
    // Outgoing side's flags are untouched.
    expect(a.hasMoved).toBe(true);
    expect(a.hasActed).toBe(true);
  });

  it('rejects an end-turn from a non-active side', () => {
    const s = state([
      unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0),
      unit('d', 'Human:Warrior', { x: 8, y: 8 }, 1),
    ]);
    expect(applyAction(s, { type: 'end-turn', side: 1 }, rng(), providers)).toBe(s);
  });

  it('increments the turn counter only when play wraps back to the lowest side', () => {
    const s = state([
      unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0),
      unit('d', 'Human:Warrior', { x: 8, y: 8 }, 1),
    ]);
    const afterS0 = applyAction(s, { type: 'end-turn', side: 0 }, rng(), providers);
    expect(afterS0.activeSide).toBe(1);
    expect(afterS0.turn).toBe(1); // no wrap yet
    const afterS1 = applyAction(afterS0, { type: 'end-turn', side: 1 }, rng(), providers);
    expect(afterS1.activeSide).toBe(0);
    expect(afterS1.turn).toBe(2); // full round completed
  });
});

describe('applyAction — triggers hook', () => {
  it('fires once per non-end-turn action and never on end-turn', () => {
    let fired = 0;
    const p: EngineProviders = {
      ...providers,
      triggers: (st) => {
        fired += 1;
        return st;
      },
    };
    const s = state([
      unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0),
      unit('d', 'Human:Warrior', { x: 7, y: 5 }, 1),
    ]);
    const s1 = applyAction(s, { type: 'move', tokenId: 'a', to: { x: 6, y: 5 } }, rng(), p);
    const s2 = applyAction(s1, { type: 'attack', tokenId: 'a', targetId: 'd' }, rng(), p);
    applyAction(s2, { type: 'end-turn', side: 0 }, rng(), p);
    expect(fired).toBe(2);
  });
});

describe('applyAction — opt-in combatHooks (server-only salted defense RNG)', () => {
  const nextRng = (v: number): ISeededRng => ({
    next: () => v,
    int: () => 0,
    pick: <T>(a: readonly T[]): T => a[0],
    state: () => 0,
    clone(): ISeededRng {
      return this;
    },
  });
  const attack = { type: 'attack', tokenId: 'a', targetId: 'd' } as const;
  const hp = (st: MatchState, id: string): number => (st.tokens.find((t) => t.instanceId === id) as Unit).hp;

  it('a defender that dodges (salted roll) takes no damage, but the attacker still acted', () => {
    const s = state([
      unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0),
      unit('d', 'Human:Warrior', { x: 6, y: 5 }, 1),
    ]);
    const p: EngineProviders = { ...providers, combatHooks: defaultCombatHooks, combatRng: () => nextRng(0) };
    const next = applyAction(s, attack, rng(), p);
    expect(hp(next, 'd')).toBe(999); // avoided
    expect((next.tokens.find((t) => t.instanceId === 'a') as Unit).hasActed).toBe(true);
  });

  it('a thorns defender damages the attacker on a landed hit', () => {
    const s = state([
      unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0),
      unit('d', 'Human:Warrior', { x: 6, y: 5 }, 1, { statuses: [{ key: 'thorns', remaining: -1 }] }),
    ]);
    const p: EngineProviders = { ...providers, combatHooks: defaultCombatHooks, combatRng: () => nextRng(0.99) };
    const next = applyAction(s, attack, rng(), p);
    expect(hp(next, 'd')).toBeLessThan(999); // hit landed
    expect(hp(next, 'a')).toBeLessThan(999); // thorns reflected
  });

  it('with hooks present but no auras + no avoidance, damage matches the default (no-hooks) path', () => {
    const s = state([
      unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0),
      unit('d', 'Human:Warrior', { x: 6, y: 5 }, 1),
    ]);
    const plain = applyAction(s, attack, rng(), providers);
    const p: EngineProviders = { ...providers, combatHooks: defaultCombatHooks, combatRng: () => nextRng(0.99) };
    const hooked = applyAction(s, attack, rng(), p);
    expect(hp(hooked, 'd')).toBe(hp(plain, 'd')); // same damage
    expect(hp(hooked, 'a')).toBe(999); // attacker unharmed
  });
});

describe('applyAction — set-stance (free minor action)', () => {
  const stanceOf = (st: MatchState, id: string): string | undefined =>
    (st.tokens.find((t) => t.instanceId === id) as Unit).stance;

  it('sets a unit stance without consuming move/action or locking the side', () => {
    const s = state([
      unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0),
      unit('b', 'Human:Warrior', { x: 7, y: 5 }, 0),
      unit('e', 'Human:Warrior', { x: 9, y: 9 }, 1), // keep the match live (no rout)
    ]);
    const s1 = applyAction(s, { type: 'set-stance', tokenId: 'a', stance: 'offensive' }, rng(), providers);
    expect(s1).not.toBe(s);
    const a = s1.tokens.find((t) => t.instanceId === 'a') as Unit;
    expect(a.stance).toBe('offensive');
    // No economy spent, no activation lock.
    expect(a.hasMoved).toBe(false);
    expect(a.hasActed).toBe(false);
    expect(s1.activatedTokenId).toBeUndefined();

    // A SECOND unit can still be re-stanced (not locked out) …
    const s2 = applyAction(s1, { type: 'set-stance', tokenId: 'b', stance: 'defensive' }, rng(), providers);
    expect(stanceOf(s2, 'b')).toBe('defensive');
    // … and 'a' can then still move (its budget was untouched).
    const s3 = applyAction(s2, { type: 'move', tokenId: 'a', to: { x: 6, y: 5 } }, rng(), providers);
    expect(s3).not.toBe(s2);
    expect((s3.tokens.find((t) => t.instanceId === 'a') as Unit).hasMoved).toBe(true);
  });

  it('is omitted from legalActions (AI/UI-driven, not enumerated)', () => {
    const s = state([unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0)]);
    expect(legalActions(s, 0, providers).some((x) => x.type === 'set-stance')).toBe(false);
  });

  it('rejects setting a stance on an opponent (or off-turn) unit', () => {
    const s = state([
      unit('a', 'Human:Warrior', { x: 5, y: 5 }, 0),
      unit('e', 'Human:Warrior', { x: 6, y: 5 }, 1),
    ]);
    // side 1's unit while side 0 is active → unchanged.
    expect(applyAction(s, { type: 'set-stance', tokenId: 'e', stance: 'offensive' }, rng(), providers)).toBe(s);
  });

  it('gates Brewmaster stances to Brewmasters', () => {
    const s = state([
      unit('w', 'Human:Warrior', { x: 5, y: 5 }, 0),
      unit('m', 'Human:Brewmaster', { x: 7, y: 5 }, 0),
    ]);
    // A Warrior cannot adopt Drunken Monkey → unchanged.
    expect(applyAction(s, { type: 'set-stance', tokenId: 'w', stance: 'drunken-monkey' }, rng(), providers)).toBe(s);
    // A Brewmaster can.
    const ok = applyAction(s, { type: 'set-stance', tokenId: 'm', stance: 'drunken-monkey' }, rng(), providers);
    expect(stanceOf(ok, 'm')).toBe('drunken-monkey');
  });
});
