packages:
  - apps/*
  - sdks/*
  - utils/*
  - types/*
  - services/*

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - unrs-resolver

overrides:
  esbuild: '0.28.1'
