import React from 'react';

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: App — Renders a welcome heading message for the web client application.
// @ai-hash: a83b8524
// ── END AI-METHOD ──
export function App() {
  return <h1>Hello from web-client</h1>;
}
