server_tokens off;

root /var/www/shatteredarchive-dev;
index index.html;

gzip on;
gzip_disable "msie6";
gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

location / {
    try_files $uri $uri/ =404;
}

location ~ /\. {
    deny all;
}
