// apps\web-server\src\index.ts
import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';

import type { ServerHealth } from '@shatteredarchive/types-server';
import { getConfigFromEnv, createExpressService } from '@shatteredarchive/services-server';

/* ---------------- env loading ---------------- */

// IMPORTANT: do not crash if .env is missing; allow offline-only mode.
const baseEnvFile = path.resolve(process.cwd(), '.env');
if (fs.existsSync(baseEnvFile)) {
  dotenv.config({ path: baseEnvFile, override: true });
} else {
  console.warn(`[web-server] No base .env found at ${baseEnvFile} (continuing)`);
}

// environment-specific overrides (optional)
const env = process.env.ENVIRONMENT ?? 'dev';
const envFile = path.resolve(process.cwd(), `.env.${env}`);
if (fs.existsSync(envFile)) {
  dotenv.config({ path: envFile, override: true });
  console.log(`[web-server] Loaded environment overrides from ${envFile}`);
} else {
  console.warn(`[web-server] No environment override file found at ${envFile}, using base .env only`);
}

const serverPort = process.env.PORT;
if (!serverPort) {
  throw new Error('Fatal exception : environment variable PORT is not defined');
}

console.log(`[web-server] Loaded environment (env=${env})`);

// Load standardized config for this service
const webConfig = getConfigFromEnv('web-server');

// Upstream base is OPTIONAL now: offline fallback still works without it.
const SHATTEREDARCHIVE_BASE = process.env.SHATTEREDARCHIVE_BASE;
if (!SHATTEREDARCHIVE_BASE) {
  console.warn('[web-server] SHATTEREDARCHIVE_BASE is not defined. Upstream fetch disabled; offline only.');
}

/* ---------------- upstream helpers ---------------- */

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: buildUpstreamUrl — Constructs a complete upstream URL by combining a base URL with a path while ensuring proper formatting.
// @ai-hash: 61a92976
// ── END AI-METHOD ──
function buildUpstreamUrl(p: string): string | null {
  if (!SHATTEREDARCHIVE_BASE) return null;
  const base = SHATTEREDARCHIVE_BASE.replace(/\/+$/, '');
  const pathPart = p.replace(/^\/+/, '');
  return `${base}/${pathPart}`;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: fetchJsonWithTimeout — Fetches JSON data with configurable timeout and returns structured success/error response.
// @ai-hash: a6201af0
// ── END AI-METHOD ──
async function fetchJsonWithTimeout(url: string, ms = 10_000) {
  const ac = new AbortController();
  const t = setTimeout(() => ac.abort(), ms);
  try {
    const r = await fetch(url, {
      method: 'GET',
      headers: { Accept: 'application/json' },
      signal: ac.signal,
    });

    if (!r.ok) {
      const text = await r.text().catch(() => '');
      return { ok: false as const, status: r.status, text };
    }

    const json = await r.json();
    return { ok: true as const, status: r.status, json };
  } catch (e: any) {
    return { ok: false as const, status: 0, text: String(e?.message ?? e ?? 'fetch failed') };
  } finally {
    clearTimeout(t);
  }
}

/* ---------------- In-memory cache (process lifetime) ---------------- */

type CacheEntry = { expiresAt: number; value: unknown };

const MAPS_TTL_MS = 30 * 24 * 60 * 60 * 1000; // 30 days
const mapsCache = new Map<string, CacheEntry>();

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: getCached — Returns cached value if unexpired, otherwise deletes and returns null.
// @ai-hash: 440833f4
// ── END AI-METHOD ──
function getCached(key: string): unknown | null {
  const entry = mapsCache.get(key);
  if (!entry) return null;
  if (Date.now() >= entry.expiresAt) {
    mapsCache.delete(key);
    return null;
  }
  return entry.value;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: setCached — Sets a cached value with expiration time in milliseconds.
// @ai-hash: 41aecd33
// ── END AI-METHOD ──
function setCached(key: string, value: unknown, ttlMs: number) {
  mapsCache.set(key, { value, expiresAt: Date.now() + ttlMs });
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: maxAgeSeconds — Converts milliseconds to seconds by flooring the division by 1000.
// @ai-hash: 0eb262a4
// ── END AI-METHOD ──
function maxAgeSeconds(ms: number): number {
  return Math.floor(ms / 1000);
}

/* ---------------- Offline fallback ----------------
   Files (source):
   - src/offline/continents/continent-names.json -> { continentNames: string[] }
   - src/offline/continents/<Continent>/areas.json -> { areaNames: string[] }
---------------------------------------------------- */
// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: isSafeFolderName — Validates if a string is a safe folder name with length and character restrictions.
// @ai-hash: 634492d0
// ── END AI-METHOD ──
function isSafeFolderName(s: string): boolean {
  const v = String(s ?? '').trim();
  if (!v) return false;
  if (v.length > 20) return false;
  return /^[A-Za-z0-9 _-]+$/.test(v) && !v.includes('..');
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: tryFindOfflineRoot — Attempts to locate an offline root directory by checking multiple candidate paths.
// @ai-hash: 7a3f651c
// ── END AI-METHOD ──
function tryFindOfflineRoot(): string | null {
  // Prefer a location relative to THIS FILE (reliable under ts-node/esm)
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = path.dirname(__filename);

  const candidates = [
    path.resolve(__dirname, 'offline'), // src/offline when running src/index.ts
    path.resolve(__dirname, '../offline'), // if index ends up elsewhere
    path.resolve(process.cwd(), 'src', 'offline'),
    path.resolve(process.cwd(), 'dist', 'src', 'offline'),
    path.resolve(process.cwd(), 'offline'),
    path.resolve(process.cwd(), 'dist', 'offline'),
  ];

  for (const c of candidates) {
    try {
      if (fs.existsSync(c) && fs.statSync(c).isDirectory()) return c;
    } catch {
      // ignore
    }
  }
  return null;
}

const offlineRoot = tryFindOfflineRoot();
if (!offlineRoot) {
  console.warn('[web-server] Offline root not found. Offline fallback will be unavailable.');
} else {
  console.log(`[web-server] Offline root detected at ${offlineRoot}`);
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: safeJsonParseFile — Parses JSON file content safely, returning null on file missing, read, or parse errors.
// @ai-hash: 3ccd18a6
// ── END AI-METHOD ──
function safeJsonParseFile(filePath: string): any | null {
  try {
    if (!fs.existsSync(filePath)) return null;
    const raw = fs.readFileSync(filePath, 'utf8');
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

let offlineContinentNamesCache: string[] | null = null;

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: loadOfflineContinentNames — Loads and caches offline continent names, returning null on failure.
// @ai-hash: a6625f39
// ── END AI-METHOD ──
function loadOfflineContinentNames(): string[] | null {
  if (!offlineRoot) return null;
  if (offlineContinentNamesCache) return offlineContinentNamesCache;

  const p = path.resolve(offlineRoot, 'continents', 'continent-names.json');
  const j = safeJsonParseFile(p);
  const arr = j?.continentNames;

  if (Array.isArray(arr) && arr.every((x: any) => typeof x === 'string')) {
    offlineContinentNamesCache = arr;
    return arr;
  }
  return null;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: loadOfflineAreaNames — Loads offline area names for a given continent, returning null if not found or invalid.
// @ai-hash: f4304807
// ── END AI-METHOD ──
function loadOfflineAreaNames(continentRaw: string): string[] | null {
  if (!offlineRoot) return null;

  const continents = loadOfflineContinentNames();
  const wanted = String(continentRaw ?? '').trim();
  if (!wanted) return null;

  // Use continentNames as canonical folder match (case-insensitive)
  const matched = continents?.find((c) => c.toLowerCase() === wanted.toLowerCase()) ?? wanted;
  if (!isSafeFolderName(matched)) return null;

  const p = path.resolve(offlineRoot, 'continents', matched, 'areas.json');
  const j = safeJsonParseFile(p);

  const arr = j?.areaNames;
  if (Array.isArray(arr) && arr.every((x: any) => typeof x === 'string')) {
    return arr;
  }

  return null;
}

/* ---------------- Optional basePath compatibility ---------------- */

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: getMaybeBasePath — Returns normalized base path string from configuration object or empty string if invalid.
// @ai-hash: 0dc9e627
// ── END AI-METHOD ──
function getMaybeBasePath(cfg: unknown): string {
  const c: any = cfg as any;
  const bp = c?.basePath ?? c?.base_path ?? c?.apiBasePath ?? c?.api_base_path ?? '';
  if (!bp) return '';
  if (typeof bp !== 'string') return '';
  const trimmed = bp.trim();
  if (!trimmed || trimmed === '/') return '';
  return trimmed.startsWith('/') ? trimmed : `/${trimmed}`;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: registerGet — Registers GET route with optional base path prefix handling.
// @ai-hash: 1c485439
// ── END AI-METHOD ──
function registerGet(app: any, basePath: string, route: string, handler: (req: any, res: any) => any) {
  app.get(route, handler);
  if (basePath) {
    const full = `${basePath}${route.startsWith('/') ? route : `/${route}`}`;
    app.get(full, handler);
  }
}

/* ---------------- Service ---------------- */

const service = createExpressService(webConfig, (app) => {
  const basePath = getMaybeBasePath(webConfig);
  console.log(`[web-server] Route basePath: ${basePath || '(none)'}`);

  app.get('/', (_req, res) => {
    res.json({ message: 'Hello from web-server' });
  });

  app.get('/health', (_req, res) => {
    const health: ServerHealth = {
      status: 'ok',
      uptimeSeconds: process.uptime(),
    };
    res.json(health);
  });

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: handleContinentNames — Returns cached, upstream, or offline continent names with appropriate headers and caching.
  // @ai-hash: dcca7363
  // ── END AI-METHOD ──
  // GET /maps/continent/names -> { continentNames: string[] }
  const handleContinentNames = async (req: any, res: any) => {
    const key = req.path;
    const cached = getCached(key);
    if (cached !== null) {
      res.setHeader('X-Maps-Source', 'cache');
      res.setHeader('Content-Type', 'application/json');
      res.setHeader('Cache-Control', `public, max-age=${maxAgeSeconds(MAPS_TTL_MS)}`);
      return res.status(200).json(cached);
    }

    // upstream first (if configured)
    const upstreamUrl = buildUpstreamUrl(`maps/continent/names`);
    if (upstreamUrl) {
      const result = await fetchJsonWithTimeout(upstreamUrl, 10_000);
      if (result.ok && result.json) {
        setCached(key, result.json, MAPS_TTL_MS);
        res.setHeader('X-Maps-Source', 'upstream');
        res.setHeader('Content-Type', 'application/json');
        res.setHeader('Cache-Control', `public, max-age=${maxAgeSeconds(MAPS_TTL_MS)}`);
        return res.status(200).json(result.json);
      }
    }

    // offline fallback
    const offline = loadOfflineContinentNames();
    if (offline) {
      const payload = { continentNames: offline };
      setCached(key, payload, MAPS_TTL_MS);
      res.setHeader('X-Maps-Source', 'offline');
      res.setHeader('Content-Type', 'application/json');
      res.setHeader('Cache-Control', `public, max-age=${maxAgeSeconds(MAPS_TTL_MS)}`);
      return res.status(200).json(payload);
    }

    return res.status(502).json({
      error: 'Offline fallback unavailable (and upstream disabled or failed)',
    });
  };

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: handleAreaNamesByContinent — Handles continent-based area name lookups with cache, upstream, and offline fallbacks.
  // @ai-hash: 7530ae73
  // ── END AI-METHOD ──
  // GET /maps/continent/:continent/get-area-names -> { areaNames: string[] }
  const handleAreaNamesByContinent = async (req: any, res: any) => {
    const continent = String(req.params?.continent ?? '').trim();

    // allow spaces for "NE Ocean" etc
    if (!/^[A-Za-z0-9 _-]+$/.test(continent)) {
      return res.status(400).json({ error: 'Invalid continent' });
    }

    if (continent.length > 20) return res.status(400).json({ error: 'Invalid continent' });

    const key = req.path;
    const cached = getCached(key);
    if (cached !== null) {
      res.setHeader('X-Maps-Source', 'cache');
      res.setHeader('Content-Type', 'application/json');
      res.setHeader('Cache-Control', `public, max-age=${maxAgeSeconds(MAPS_TTL_MS)}`);
      return res.status(200).json(cached);
    }

    // upstream first (if configured)
    const upstreamUrl = buildUpstreamUrl(`maps/continent/${encodeURIComponent(continent)}/get-area-names`);
    if (upstreamUrl) {
      const result = await fetchJsonWithTimeout(upstreamUrl, 10_000);
      if (result.ok && result.json) {
        setCached(key, result.json, MAPS_TTL_MS);
        res.setHeader('X-Maps-Source', 'upstream');
        res.setHeader('Content-Type', 'application/json');
        res.setHeader('Cache-Control', `public, max-age=${maxAgeSeconds(MAPS_TTL_MS)}`);
        return res.status(200).json(result.json);
      }
    }

    // offline fallback (folder match driven by continentNames)
    const offlineAreas = loadOfflineAreaNames(continent);
    if (offlineAreas) {
      const payload = { areaNames: offlineAreas };
      setCached(key, payload, MAPS_TTL_MS);
      res.setHeader('X-Maps-Source', 'offline');
      res.setHeader('Content-Type', 'application/json');
      res.setHeader('Cache-Control', `public, max-age=${maxAgeSeconds(MAPS_TTL_MS)}`);
      return res.status(200).json(payload);
    }

    return res.status(502).json({
      error: 'Offline fallback missing for continent (and upstream disabled or failed)',
      continent,
    });
  };

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: handleBeastsByArea — Handles area beast data retrieval with cache, upstream, and offline fallback strategies.
  // @ai-hash: 606f7964
  // ── END AI-METHOD ──
  // GET /maps/area/:area/beasts -> { beasts: [...] }
  const handleBeastsByArea = async (req: any, res: any) => {
    const areaName = String(req.params?.areaName ?? '').trim();
    if (areaName.length > 80) return res.status(400).json({ error: 'Invalid area' });

    const key = req.path;
    const cached = getCached(key);
    if (cached !== null) {
      res.setHeader('X-Maps-Source', 'cache');
      res.setHeader('Content-Type', 'application/json');
      res.setHeader('Cache-Control', `public, max-age=${maxAgeSeconds(MAPS_TTL_MS)}`);
      return res.status(200).json(cached);
    }

    // upstream first (if configured)
    const upstreamUrl = buildUpstreamUrl(`maps/area/${encodeURIComponent(areaName)}/beasts`);
    if (upstreamUrl) {
      const result = await fetchJsonWithTimeout(upstreamUrl, 10_000);
      if (result.ok && result.json) {
        setCached(key, result.json, MAPS_TTL_MS);
        res.setHeader('X-Maps-Source', 'upstream');
        res.setHeader('Content-Type', 'application/json');
        res.setHeader('Cache-Control', `public, max-age=${maxAgeSeconds(MAPS_TTL_MS)}`);
        return res.status(200).json(result.json);
      }
    }

    res.setHeader('X-Maps-Source', 'offline');
    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Cache-Control', `public, max-age=${maxAgeSeconds(MAPS_TTL_MS)}`);
    return res.status(200).json({ beasts: [] });
  };

  registerGet(app, basePath, '/maps/continent/names', handleContinentNames);
  registerGet(app, basePath, '/maps/continent/:continent/get-area-names', handleAreaNamesByContinent);
  registerGet(app, basePath, '/maps/area/:areaName/beasts', handleBeastsByArea);
});

service
  .start()
  .then(() => {
    console.log(`[web-server] Listening on port ${serverPort}`);
  })
  .catch((err) => {
    console.error(`[web-server] Failed to start`, err);
    process.exit(1);
  });
