// apps/game-client/src/shims/os-browser.ts

// Minimal browser shim for Node's `os` module,
// just enough to keep Fengari happy.

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: platform — (no summary)
// @ai-hash: 11414364
// ── END AI-METHOD ──
export function platform(): string {
  // Fengari mostly uses this to toggle path / line ending behavior.
  // "linux" is a safe, POSIX-y default for browser.
  return 'linux';
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: tmpdir — (no summary)
// @ai-hash: 58209084
// ── END AI-METHOD ──
export function tmpdir(): string {
  return '/tmp';
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: homedir — (no summary)
// @ai-hash: 6ed79ae0
// ── END AI-METHOD ──
export function homedir(): string {
  return '/';
}

export const EOL = '\n';

// Some bundlers / codepaths use the default export style.
export default {
  platform,
  tmpdir,
  homedir,
  EOL,
};
