export const baseDamageType = {
  Unknown: 'unknown',
  AcidicBite: 'acbite',
  Beating: 'beating',
  Bite: 'bite',
  Blast: 'blast',
  Charge: 'charge',
  Chill: 'chill',
  Chop: 'chop',
  Claw: 'claw',
  Cleave: 'cleave',
  Crush: 'crush',
  Divine: 'divine power',
  Drain: 'drain',
  Flame: 'flame',
  FlamingBite: 'flaming bite',
  FreezingBite: 'freezing bite',
  Grep: 'grep',
  Magic: 'magic',
  None: 'none',
  Peck: 'peck',
  Pierce: 'pierce',
  Pound: 'pound',
  Punch: 'punch',
  Scratch: 'scratch',
  ShockingBite: 'shocking bite',
  Shock: 'shock',
  Slap: 'slap',
  Slash: 'slash',
  Slice: 'slice',
  Slime: 'slime',
  Smash: 'smash',
  Stab: 'stab',
  Sting: 'sting',
  Suction: 'suction',
  Thrust: 'thrust',
  Thwack: 'thwack',
  Whip: 'whip',
  Wrath: 'wrath',
} as const;

export type DamageType = (typeof baseDamageType)[keyof typeof baseDamageType];