import type { GameModeConfig, GameModeId, StatBlock, UnitTemplate } from '../model/index.js';

import { MORTAL_RACES, REMORT_RACES, type DslMortalRace, type DslRemortRace } from './dsl/races.js';
import { CLASSES, type DslClassId } from './dsl/classes.js';
import { MOON_TYPES, MOON_PHASES, type DslNamed } from './dsl/moons.js';
import { GODS, type DslGod } from './dsl/gods.js';
import { AFFILIATIONS, type DslAffiliation } from './dsl/affiliations.js';
import { TERRAINS, type DslTerrain } from './dsl/terrain.js';
import { RACE_ATTRIBUTES } from './dsl/race-attributes.js';
import { CLASS_ATTRIBUTES } from './dsl/class-attributes.js';
import {
  ABILITIES,
  ABILITY_GROUPS,
  type DslAbility,
  type DslAbilityGroup,
} from './dsl/abilities.js';

import { CLASS_KITS, defaultClassKit, type ClassKit } from './balance/class-kits.js';
import { RACE_MODIFIERS, DEFAULT_RACE_MODIFIER } from './balance/race-modifiers.js';
import { RECLASS_KITS } from './balance/reclass-kits.js';
import {
  isLegalRaceClass,
  legalClassesForRace,
  legalRacesForClass,
  type RaceClassContext,
} from './balance/legality.js';
import { MOON_EFFECTS, DEFAULT_MOON_EFFECT, type MoonModifier } from './balance/moon-effects.js';
import { TERRAIN_EFFECTS, DEFAULT_TERRAIN_EFFECT, type TerrainEffect } from './balance/terrain.js';
import { classPointCost } from './balance/unit-costs.js';
import {
  isElfRace,
  racialAbilityDefenseDelta,
  racialAbilityTraits,
} from './balance/racial-traits.js';
import { computeCastingLevel } from './balance/casting.js';
import { GAME_MODES, GAME_MODE_LIST } from './balance/modes.js';

const DEFAULT_STATS: StatBlock = { str: 10, int: 10, wis: 10, dex: 10, con: 10 };

/** Read access to all centralized game data. unitTemplate() is the single choke
 * point where distilled DSL data + authored balance compose into resolved units. */
export interface IGameDataProvider {
  races(): readonly DslMortalRace[];
  remortRaces(): readonly DslRemortRace[];
  classes(): readonly DslClassId[];
  moonTypes(): readonly DslNamed[];
  moonPhases(): readonly DslNamed[];
  gods(): readonly DslGod[];
  affiliations(): readonly DslAffiliation[];
  terrains(): readonly DslTerrain[];
  /** Distilled DSL ability catalog (spells/songs/skills) — identity only, no mechanics. */
  abilities(): readonly DslAbility[];
  /** Class ability groups with transitively-resolved member ability keys. */
  abilityGroups(): readonly DslAbilityGroup[];
  /** Look up a single ability by its catalog key. */
  ability(key: string): DslAbility | undefined;
  /** The abilities belonging to a given ability group (empty if unknown group). */
  abilitiesForGroup(groupKey: string): readonly DslAbility[];
  /** Fully resolve a (race × class) into a UnitTemplate. Every mortal class resolves
   * (a hand-authored kit, else a derived default) — never throws for a known class. */
  unitTemplate(raceKey: string, classKey: string): UnitTemplate;
  moonEffect(phaseKey: string): MoonModifier;
  terrainEffect(terrainKey: string): TerrainEffect;
  /** Whether `raceKey` may take `classKey` under the army's affiliation `ctx`
   * (raceRestrictions FORBID + requiresRaces ALLOW + CSR affiliation gate). */
  isLegalRaceClass(raceKey: string, classKey: string, ctx?: RaceClassContext): boolean;
  /** Class keys legal for `raceKey` under `ctx` (single-select per unit). */
  legalClassesForRace(raceKey: string, ctx?: RaceClassContext): readonly string[];
  /** Mortal race keys legal for `classKey` under `ctx`. */
  legalRacesForClass(classKey: string, ctx?: RaceClassContext): readonly string[];
}

export interface IGameModeProvider {
  modes(): readonly GameModeConfig[];
  mode(id: GameModeId): GameModeConfig;
}

const uniq = (xs: readonly string[]): string[] => [...new Set(xs)];

export class GameDataProvider implements IGameDataProvider {
  private readonly raceName = new Map<string, string>(MORTAL_RACES.map((r) => [r.key, r.name]));
  private readonly raceAttr = new Map<string, (typeof RACE_ATTRIBUTES)[number]>(
    RACE_ATTRIBUTES.map((r) => [r.key, r]),
  );
  private readonly classAttr = new Map<string, (typeof CLASS_ATTRIBUTES)[number]>(
    CLASS_ATTRIBUTES.map((c) => [c.key, c]),
  );
  private readonly className = new Map<string, string>(CLASSES.map((c) => [c.key, c.name]));
  private readonly abilityByKey = new Map<string, DslAbility>(ABILITIES.map((a) => [a.key, a]));
  private readonly groupByKey = new Map<string, DslAbilityGroup>(
    ABILITY_GROUPS.map((g) => [g.key, g]),
  );

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: races — (no summary)
  // @ai-hash: 1f9603b6
  // ── END AI-METHOD ──
  races(): readonly DslMortalRace[] {
    return MORTAL_RACES;
  }
  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: remortRaces — (no summary)
  // @ai-hash: 0cfccf36
  // ── END AI-METHOD ──
  remortRaces(): readonly DslRemortRace[] {
    return REMORT_RACES;
  }
  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: classes — (no summary)
  // @ai-hash: 1f240b70
  // ── END AI-METHOD ──
  classes(): readonly DslClassId[] {
    return CLASSES;
  }
  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: moonTypes — (no summary)
  // @ai-hash: 9e309af3
  // ── END AI-METHOD ──
  moonTypes(): readonly DslNamed[] {
    return MOON_TYPES;
  }
  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: moonPhases — (no summary)
  // @ai-hash: 6a6b22a6
  // ── END AI-METHOD ──
  moonPhases(): readonly DslNamed[] {
    return MOON_PHASES;
  }
  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: gods — (no summary)
  // @ai-hash: 3f980b1f
  // ── END AI-METHOD ──
  gods(): readonly DslGod[] {
    return GODS;
  }
  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: affiliations — (no summary)
  // @ai-hash: 399e088f
  // ── END AI-METHOD ──
  affiliations(): readonly DslAffiliation[] {
    return AFFILIATIONS;
  }
  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: terrains — (no summary)
  // @ai-hash: 6f4ec0d4
  // ── END AI-METHOD ──
  terrains(): readonly DslTerrain[] {
    return TERRAINS;
  }

  abilities(): readonly DslAbility[] {
    return ABILITIES;
  }
  abilityGroups(): readonly DslAbilityGroup[] {
    return ABILITY_GROUPS;
  }
  ability(key: string): DslAbility | undefined {
    return this.abilityByKey.get(key);
  }
  abilitiesForGroup(groupKey: string): readonly DslAbility[] {
    const group = this.groupByKey.get(groupKey);
    if (!group) return [];
    return group.abilityKeys.flatMap((k) => {
      const a = this.abilityByKey.get(k);
      return a ? [a] : [];
    });
  }

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: moonEffect — (no summary)
  // @ai-hash: 5ca0a9d2
  // ── END AI-METHOD ──
  moonEffect(phaseKey: string): MoonModifier {
    return MOON_EFFECTS[phaseKey] ?? DEFAULT_MOON_EFFECT;
  }
  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: terrainEffect — (no summary)
  // @ai-hash: 2a108a0e
  // ── END AI-METHOD ──
  terrainEffect(terrainKey: string): TerrainEffect {
    return TERRAIN_EFFECTS[terrainKey] ?? DEFAULT_TERRAIN_EFFECT;
  }

  isLegalRaceClass(raceKey: string, classKey: string, ctx?: RaceClassContext): boolean {
    return isLegalRaceClass(raceKey, classKey, ctx);
  }
  legalClassesForRace(raceKey: string, ctx?: RaceClassContext): readonly string[] {
    return legalClassesForRace(raceKey, ctx);
  }
  legalRacesForClass(classKey: string, ctx?: RaceClassContext): readonly string[] {
    return legalRacesForClass(classKey, ctx);
  }

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: unitTemplate — (no summary)
  // @ai-hash: fe9a821f
  // ── END AI-METHOD ──
  unitTemplate(raceKey: string, classKey: string): UnitTemplate {
    // Resolve the class kit (following a reclass to its base, then applying deltas).
    // A hand-authored kit wins; otherwise derive a default kit from the class's
    // distilled attributes so every mortal class is playable. Reclass deltas only
    // layer on a hand base kit — a derived default already reflects the class's own
    // attributes, so deltas are skipped there to avoid double-counting.
    const reclass = RECLASS_KITS[classKey];
    const kitKey = reclass ? reclass.baseClassKey : classKey;
    const handKit: ClassKit | undefined = CLASS_KITS[kitKey];
    const usingDefault = !handKit;
    const kit: ClassKit = handKit ?? defaultClassKit(classKey);

    const raceMod = RACE_MODIFIERS[raceKey] ?? DEFAULT_RACE_MODIFIER;
    const rAttr = this.raceAttr.get(raceKey);
    const cAttr = this.classAttr.get(classKey);

    const reHp = usingDefault ? 0 : (reclass?.hpDelta ?? 0);
    const reAtk = usingDefault ? 0 : (reclass?.attackDelta ?? 0);
    const reDef = usingDefault ? 0 : (reclass?.defenseDelta ?? 0);

    // Distilled DSL racial abilities (e.g. Toughness) carry authored tactical effects.
    const racialAbilities = rAttr?.racialAbilities ?? [];

    // Race×class DAMAGE boost/gimp (BoostedClasses: boost 10 / superboost 20 / SUPERBOOST 30;
    // gimps negative) — a percent modifier on this race's damage as that class.
    const damageBoostPct = (rAttr?.classBoosts ?? []).find((b) => b.classKey === classKey)?.boost ?? 0;

    const maxHp = kit.baseHp + reHp + raceMod.hpDelta;
    const rawAttack = kit.attackPower + reAtk + raceMod.attackDelta;
    const attackPower = Math.round(rawAttack * (1 + damageBoostPct / 100));
    const defense =
      kit.defense + reDef + raceMod.defenseDelta + racialAbilityDefenseDelta(racialAbilities);
    const moveRange = kit.move.range + raceMod.moveRangeDelta;

    // Effective caster LEVEL: level cap × the class cast factor (below-level casters cast at a
    // fraction), + elf (+1). Class affinity (+1) is a distinct, not-yet-distilled source (NOT the
    // damage boosts above), so it is off for now.
    const castingLevel = computeCastingLevel({
      castsAtLevel: cAttr?.castsAtLevel ?? null,
      castingLevelModifier: cAttr?.castingLevelModifier ?? null,
      hasClassAffinity: false,
      isElf: isElfRace(raceKey),
    });

    const traits = uniq([
      ...kit.traits,
      ...raceMod.traits,
      ...(usingDefault ? [] : (reclass?.addTraits ?? [])),
      ...(rAttr?.isLargeRace ? ['large'] : []),
      ...racialAbilityTraits(racialAbilities),
    ]);

    return {
      id: `${raceKey}:${classKey}`,
      raceKey,
      classKey,
      name: `${this.raceName.get(raceKey) ?? raceKey} ${this.className.get(classKey) ?? classKey}`,
      maxHp,
      stats: rAttr?.baseStats ?? DEFAULT_STATS,
      move: { ...kit.move, range: moveRange },
      attack: kit.attack,
      attackPower,
      defense,
      movementClass: raceMod.movementClassOverride ?? kit.movementClass,
      damageType: kit.damageType,
      // Armor type is the distilled DSL class armor (sole armor-based defensive factor);
      // Cloth (0 mitigation) when a class declares none.
      armorType: cAttr?.armorType ?? 'Cloth',
      abilities: uniq((cAttr?.abilities ?? []).map((a) => a.key)),
      resistances: rAttr?.resistances ?? [],
      vulnerabilities: rAttr?.vulnerabilities ?? [],
      traits,
      cost: classPointCost({
        isReclass: cAttr?.isReclass ?? false,
        baseCpModifier: cAttr?.baseCpModifier ?? null,
      }),
      isReclass: cAttr?.isReclass ?? false,
      classGroup: cAttr?.classGroup ?? classKey,
      castingLevel,
      damageBoostPct,
    };
  }
}

export class GameModeProvider implements IGameModeProvider {
  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: modes — (no summary)
  // @ai-hash: 65f39245
  // ── END AI-METHOD ──
  modes(): readonly GameModeConfig[] {
    return GAME_MODE_LIST;
  }
  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: mode — (no summary)
  // @ai-hash: 212ddc89
  // ── END AI-METHOD ──
  mode(id: GameModeId): GameModeConfig {
    return GAME_MODES[id];
  }
}

export const createGameDataProvider = (): IGameDataProvider => new GameDataProvider();
export const createGameModeProvider = (): IGameModeProvider => new GameModeProvider();

export type { MoonModifier } from './balance/moon-effects.js';
export type { TerrainEffect } from './balance/terrain.js';
export {
  ABILITIES,
  ABILITY_GROUPS,
  type DslAbility,
  type DslAbilityGroup,
  type AbilityKey,
  type AbilityGroupKey,
  type AbilityType,
} from './dsl/abilities.js';
export { AUTHORED_MECHANICS } from './balance/abilities/mechanics.js';
export {
  resolveAbilityMechanics,
  stubMechanics,
  isAuthored,
} from './balance/abilities/resolve.js';
export {
  isLegalRaceClass,
  legalClassesForRace,
  legalRacesForClass,
  type RaceClassContext,
} from './balance/legality.js';
export { defaultClassKit } from './balance/class-kits.js';
export {
  STANCES,
  DEFAULT_STANCE,
  stanceMod,
  stancesForClass,
  isStanceLegalFor,
  type StanceKey,
  type StanceModifier,
} from './balance/stances.js';
export { alignmentForGod, godsByAlignment } from './balance/religion.js';
export {
  MOONS,
  MOON_FOR_ALIGNMENT,
  MOON_PHASE_BONUS,
  MOON_POSITION_REGEN,
  MOON_PHASE_CYCLE,
  NO_MOON_BONUS,
  moonPhaseAt,
  moonSkyAt,
  moonBonusForAlignment,
  type MoonDef,
  type MoonAlignment,
  type MoonPhaseBonus,
  type MoonSky,
} from './balance/moons.js';
