// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: greetServer — Returns a personalized greeting message from the utils-global module.
// @ai-hash: 58d5321d
// ── END AI-METHOD ──
export function greetServer(name: string): string {
  return `Hello, ${name} from utils-global`;
}

export * from './strip-ansi';
