// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: StripAnsi — Removes ANSI escape codes from input string.
// @ai-hash: 39238159
// ── END AI-METHOD ──
export function StripAnsi(str: string) {
  if (!str.includes('\x1b')) {
    return str;
  }
  return str.replace(/\u001b\[[0-9;]*m/g, '');
}
