// utils/utils-client/src/ansi-to-html.ts
import AnsiToHtmlLib from 'ansi-to-html';

/**
 * Small interface so tests (or other environments) can provide their own
 * converter without pulling in the real ansi-to-html dependency.
 */
export interface IAnsiToHtmlConverter {
  toHtml(input: string): string;
}

/**
 * Default implementation using the ansi-to-html library.
 * You can tweak colors/options here to match your theme.
 */
class AnsiToHtmlConverter implements IAnsiToHtmlConverter {
  private readonly converter: AnsiToHtmlLib;

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: constructor — Initializes the converter with ANSI to HTML formatting options and settings.
  // @ai-hash: 6b7e847e
  // ── END AI-METHOD ──
  constructor() {
    this.converter = new AnsiToHtmlLib({
      fg: '#e0e0e0', // default foreground
      bg: '#000000', // default background
      newline: true, // treat \n as <br/>
      escapeXML: true, // escape HTML entities in the input
      stream: false,
    });
  }

  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: toHtml — Converts input string to HTML format using internal converter or returns empty string if input is falsy.
  // @ai-hash: d6e9e027
  // ── END AI-METHOD ──
  toHtml(input: string): string {
    if (!input) return '';
    return this.converter.toHtml(input);
  }
}

/** Default shared converter instance. */
const defaultConverter = new AnsiToHtmlConverter();

/** Currently active converter (can be swapped for mocks in tests). */
let activeConverter: IAnsiToHtmlConverter = defaultConverter;

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: setAnsiToHtmlConverter — Sets the active ANSI to HTML converter, falling back to default if none provided.
// @ai-hash: f4335225
// ── END AI-METHOD ──
/**
 * Replace the active converter implementation.
 * Useful in unit tests or for alternate renderers.
 *
 * Example (jest):
 *   setAnsiToHtmlConverter({ toHtml: s => `MOCK:${s}` });
 */
export function setAnsiToHtmlConverter(converter: IAnsiToHtmlConverter) {
  activeConverter = converter ?? defaultConverter;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: getAnsiToHtmlConverter — Returns the active ANSI to HTML converter instance for color format translation.
// @ai-hash: 4549f7bb
// ── END AI-METHOD ──
/**
 * Get the currently active converter (mainly for advanced usage / tests).
 */
export function getAnsiToHtmlConverter(): IAnsiToHtmlConverter {
  return activeConverter;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: ansiToHtml — Converts ANSI formatted strings to HTML with color and styling.
// @ai-hash: 97d98ead
// ── END AI-METHOD ──
/**
 * Convenience function used by the rest of the app.
 *
 * Example:
 *   import { ansiToHtml } from '../utils/ansiToHtml';
 *   const html = ansiToHtml(rawAnsi);
 */
export function ansiToHtml(input: string): string {
  return activeConverter.toHtml(input);
}
