// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: greetClient — Returns a personalized greeting message for a client using their name.
// @ai-hash: f30a4c76
// ── END AI-METHOD ──
export function greetClient(name: string): string {
  return `Hello, ${name} from utils-client`;
}

export * from './ansi-to-html.js';
export * from './strip-ansi.js';
