// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: greetServer — Returns a server-side greeting message with the provided name.
// @ai-hash: 264ec69a
// ── END AI-METHOD ──
export function greetServer(name: string): string {
  return `Hello, ${name} from utils-server`;
}
