// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: fetchJsonServer — Fetches JSON data from a server URL and returns parsed response or null on failure.
// @ai-hash: 8dcc757c
// ── END AI-METHOD ──
export async function fetchJsonServer<T>(url: string): Promise<T | null> {
  try {
    const response = await fetch(url);
    if (!response.ok) {
      console.error('Server SDK fetch error', response.status, response.statusText);
      return null;
    }
    const data = (await response.json()) as T;
    return data;
  } catch (err) {
    console.error('Server SDK fetch exception', err);
    return null;
  }
}
