import type { IGameDataProvider, StanceModifier } from '../data/index.js';
import { stanceMod } from '../data/index.js';
import type {
  AbilityBuffSpec,
  AbilityHealSpec,
  BoardToken,
  MatchState,
  StatusEffect,
  UnitTemplate,
} from '../model/index.js';
import type { ISeededRng } from '../rng/index.js';
import type { CombatContext, CombatHooks } from './combat-hooks.js';
import { tileAt } from './board.js';
import { legalTargets } from './targeting.js';
import { resolveDamage } from './damage.js';
import { rollSave } from './saves.js';
import { templateForMember } from './squadron.js';

/**
 * A castable ability. A spell may carry a damage component (which AUTO-HITS, per the DSL
 * rules) and/or a maladiction component (a debuff status that only lands if it beats the
 * target's save — see rules/saves.ts). A spell with both is applied in two parts: the
 * damage always lands, the maladiction is rolled separately.
 */
export interface AbilitySpec {
  readonly key: string;
  /** When true, applies auto-hit damage using the caster's attackPower/damageType. */
  readonly damage?: boolean;
  /** Multiplier on the resolved damage amount (default 1). From AbilityDamageSpec.potency. */
  readonly damageScale?: number;
  /** Optional debuff applied only when its save lands. */
  readonly maladiction?: {
    readonly status: StatusEffect;
    /** The maladiction's own save modifier (SaveInput.saves). */
    readonly saves?: number;
    /** Hidden base-save boost/gimp (SaveInput.baseSave). */
    readonly baseSave?: number;
  };
  /** Optional beneficial status applied (no save) to the caster ('self') or the ally target. */
  readonly buff?: AbilityBuffSpec;
  /** Optional HP restoration (no save, capped at max HP) on the caster ('self') or ally target. */
  readonly heal?: AbilityHealSpec;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: resolveTemplate — (no summary)
// @ai-hash: a6081b78
// ── END AI-METHOD ──
/** Resolve a token to a representative UnitTemplate (squadron → its first member). */
function resolveTemplate(token: BoardToken, provider: IGameDataProvider): UnitTemplate {
  const templateId = token.kind === 'unit' ? token.templateId : token.members[0].templateId;
  return templateForMember(templateId, provider);
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: markActed — (no summary)
// @ai-hash: 6529a9dd
// ── END AI-METHOD ──
const markActed = (t: BoardToken): BoardToken =>
  t.kind === 'unit' ? { ...t, hasActed: true } : { ...t, hasActed: true };

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: applyDamageToToken — (no summary)
// @ai-hash: 01ec58e1
// ── END AI-METHOD ──
const applyDamageToToken = (t: BoardToken, amount: number): BoardToken =>
  t.kind === 'unit'
    ? { ...t, hp: Math.max(0, t.hp - amount) }
    : { ...t, hpPool: Math.max(0, t.hpPool - amount) };

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: withStatuses — (no summary)
// @ai-hash: 474fd3b4
// ── END AI-METHOD ──
const withStatuses = (t: BoardToken, statuses: readonly StatusEffect[]): BoardToken =>
  t.kind === 'unit' ? { ...t, statuses } : { ...t, statuses };

const appendStatus = (t: BoardToken, status: StatusEffect): BoardToken =>
  withStatuses(t, [...t.statuses, status]);

/** Apply a buff's StatusEffect (no save) to the caster ('self') or the ally target ('ally'). */
function applyBuff(
  state: MatchState,
  casterId: string,
  targetId: string,
  buff: AbilityBuffSpec,
): MatchState {
  const recipientId = buff.target === 'self' ? casterId : targetId;
  const status: StatusEffect = {
    key: buff.statusKey,
    remaining: buff.duration,
    ...(buff.magnitude !== undefined ? { magnitude: buff.magnitude } : {}),
  };
  return {
    ...state,
    tokens: state.tokens.map((t) => (t.instanceId === recipientId ? appendStatus(t, status) : t)),
  };
}

/** Restore `amount` HP to a token, capped at its max (unit template maxHp / squadron maxHpPool). */
const healToken = (t: BoardToken, amount: number, provider: IGameDataProvider): BoardToken =>
  t.kind === 'unit'
    ? { ...t, hp: Math.min(resolveTemplate(t, provider).maxHp, t.hp + amount) }
    : { ...t, hpPool: Math.min(t.maxHpPool, t.hpPool + amount) };

/** Apply a heal (no save) to the caster ('self') or the ally target. Heal amount is the flat
 * base plus a wisdom bonus (floor(caster WIS × wisScale)); the result is capped at max HP. */
function applyHeal(
  state: MatchState,
  casterId: string,
  targetId: string,
  heal: AbilityHealSpec,
  casterTpl: UnitTemplate,
  provider: IGameDataProvider,
): MatchState {
  const recipientId = heal.target === 'self' ? casterId : targetId;
  const amount = heal.amount + Math.floor(casterTpl.stats.wis * (heal.wisScale ?? 0));
  if (amount <= 0) return state;
  return {
    ...state,
    tokens: state.tokens.map((t) =>
      t.instanceId === recipientId ? healToken(t, amount, provider) : t,
    ),
  };
}

const terrainKeyAt = (state: MatchState, token: BoardToken): string =>
  tileAt(state.board, token.pos)?.terrain ?? 'Field';

/** The combat stance of a token — units carry one (default normal); squadrons are stanceless. */
const stanceOf = (token: BoardToken | undefined): StanceModifier =>
  stanceMod(token && token.kind === 'unit' ? token.stance : undefined);

/** A token's moral alignment (units only) — selects the moon empowering its magi damage. */
const alignmentOf = (token: BoardToken | undefined): string | undefined =>
  token && token.kind === 'unit' ? token.alignment : undefined;

/**
 * One attacker→defender damage exchange run through the OPT-IN per-hit `CombatHooks` in the
 * authoritative order: avoidance (step 2) → resolveDamage → typed shields (step 3) → apply
 * (step 4) → reactions, only if the hit landed (step 5). Always marks the attacker hasActed.
 * All hook randomness comes from `rng` (the server-only salted stream), so it replays
 * deterministically. Used by both the weapon path (applyAttack) and a spell's damage component
 * (applyAbility). Returns the new state plus whether/how much damage landed.
 */
function resolveDamageExchange(
  state: MatchState,
  attackerId: string,
  defenderId: string,
  attackerTpl: UnitTemplate,
  defenderTpl: UnitTemplate,
  isSpell: boolean,
  provider: IGameDataProvider,
  rng: ISeededRng,
  hooks: CombatHooks,
  damageScale = 1,
): { state: MatchState; landed: boolean; dealt: number } {
  const target = state.tokens.find((t) => t.instanceId === defenderId);
  const attackerToken = state.tokens.find((t) => t.instanceId === attackerId);
  const attackerStance = stanceOf(attackerToken);
  const defenderStance = stanceOf(target);
  const ctx: CombatContext = {
    state,
    attacker: attackerTpl,
    defender: defenderTpl,
    attackerId,
    defenderId,
    damageType: attackerTpl.damageType,
    isSpell,
    defenderStatusKeys: target ? target.statuses.map((s) => s.key) : [],
    attackerStance,
    defenderStance,
    provider,
    rng,
  };

  // Step 2 — avoidance (short-circuit: 0 damage, no reactions, but the attacker still acted).
  if (hooks.onAvoid?.(ctx)) {
    const tokens = state.tokens.map((t) => (t.instanceId === attackerId ? markActed(t) : t));
    return { state: { ...state, tokens }, landed: false, dealt: 0 };
  }

  // Step 3 — resolve the hit (stance scales dealt/taken), then let typed shielding auras reduce it.
  let amount = resolveDamage({
    attacker: attackerTpl,
    defender: defenderTpl,
    defenderTerrainKey: target ? terrainKeyAt(state, target) : 'Field',
    moonSky: state.moon.sky,
    attackerAlignment: alignmentOf(attackerToken),
    defenderStatusKeys: ctx.defenderStatusKeys,
    provider,
    rng,
    damageDealtMod: attackerStance.damageDealtMod,
    damageTakenMod: defenderStance.damageTakenMod,
  }).amount;
  if (damageScale !== 1) amount = Math.round(amount * damageScale);
  if (hooks.onDefend) amount = Math.max(0, Math.round(hooks.onDefend(amount, ctx)));

  // Step 4 — apply damage + mark the attacker acted.
  const tokens = state.tokens.map((t) => {
    if (t.instanceId === attackerId) return markActed(t);
    if (t.instanceId === defenderId) return amount > 0 ? applyDamageToToken(t, amount) : t;
    return t;
  });
  let next: MatchState = { ...state, tokens };

  // Step 5 — reactions (thorns etc.), ONLY on a landed hit; sees the post-apply state.
  if (amount > 0 && hooks.onHit) {
    next = hooks.onHit(amount, { ...ctx, state: next });
  }
  return { state: next, landed: amount > 0, dealt: amount };
}

/**
 * Apply a basic (weapon) attack: validates the target is legal, resolves damage, and
 * returns a NEW MatchState with the defender's hp/hpPool reduced and the attacker marked
 * hasActed. Illegal target or missing tokens → state returned unchanged. Pure.
 *
 * OPT-IN reactions: pass `hooks` (with an `rng`) to run the per-hit avoidance/shield/thorns
 * pipeline (see rules/combat-hooks.ts). Omitting `hooks` — or `rng` — keeps the exact
 * Phase-2b deterministic behavior, so existing callers are unaffected.
 */
export function applyAttack(
  state: MatchState,
  attackerId: string,
  targetId: string,
  provider: IGameDataProvider,
  rng?: ISeededRng,
  hooks?: CombatHooks,
): MatchState {
  const attacker = state.tokens.find((t) => t.instanceId === attackerId);
  const target = state.tokens.find((t) => t.instanceId === targetId);
  if (!attacker || !target) return state;
  if (!legalTargets(state, attackerId, provider).includes(targetId)) return state;

  // Opt-in per-hit reactions (needs a seeded stream for deterministic rolls).
  if (hooks && rng) {
    return resolveDamageExchange(
      state,
      attackerId,
      targetId,
      resolveTemplate(attacker, provider),
      resolveTemplate(target, provider),
      false,
      provider,
      rng,
      hooks,
    ).state;
  }

  // Default Phase-2b deterministic path (auto-hit; no avoidance without hooks). Stance still
  // scales damage here so postures matter in local play, which runs no combat hooks.
  const result = resolveDamage({
    attacker: resolveTemplate(attacker, provider),
    defender: resolveTemplate(target, provider),
    defenderTerrainKey: terrainKeyAt(state, target),
    moonSky: state.moon.sky,
    attackerAlignment: alignmentOf(attacker),
    defenderStatusKeys: target.statuses.map((s) => s.key),
    provider,
    rng,
    damageDealtMod: stanceOf(attacker).damageDealtMod,
    damageTakenMod: stanceOf(target).damageTakenMod,
  });

  const tokens = state.tokens.map((t) => {
    if (t.instanceId === attackerId) return markActed(t);
    if (t.instanceId === targetId) return applyDamageToToken(t, result.amount);
    return t;
  });
  return { ...state, tokens };
}

/**
 * Apply a spell/ability. Two-part per the DSL rules: any damage component AUTO-HITS, while
 * a maladiction component rolls the save (rules/saves.ts) and is only appended to the
 * target's statuses when it lands. Returns a NEW MatchState; caster marked hasActed. Pure
 * (RNG advances). Unlike applyAttack, targeting is not range-gated here — spells carry their
 * own targeting and may affect allies.
 */
export function applyAbility(
  state: MatchState,
  casterId: string,
  targetId: string,
  ability: AbilitySpec,
  provider: IGameDataProvider,
  rng: ISeededRng,
  hooks?: CombatHooks,
): MatchState {
  const caster = state.tokens.find((t) => t.instanceId === casterId);
  const target = state.tokens.find((t) => t.instanceId === targetId);
  if (!caster || !target) return state;

  const casterTpl = resolveTemplate(caster, provider);
  const targetTpl = resolveTemplate(target, provider);

  // Opt-in per-hit reactions on the DAMAGE component (spells auto-hit → avoidance only via an
  // opt-in magic-evasion aura); the maladiction still rolls its own save separately.
  if (hooks) {
    let working =
      ability.damage
        ? resolveDamageExchange(state, casterId, targetId, casterTpl, targetTpl, true, provider, rng, hooks, ability.damageScale ?? 1).state
        : { ...state, tokens: state.tokens.map((t) => (t.instanceId === casterId ? markActed(t) : t)) };

    if (ability.buff) working = applyBuff(working, casterId, targetId, ability.buff);
    if (ability.heal) working = applyHeal(working, casterId, targetId, ability.heal, casterTpl, provider);

    if (ability.maladiction) {
      const save = rollSave(
        {
          casterInt: casterTpl.stats.int,
          targetWis: targetTpl.stats.wis,
          saves: ability.maladiction.saves,
          baseSave: ability.maladiction.baseSave,
        },
        rng,
      );
      if (save.landed) {
        const status = ability.maladiction.status;
        working = {
          ...working,
          tokens: working.tokens.map((t) =>
            t.instanceId === targetId ? withStatuses(t, [...t.statuses, status]) : t,
          ),
        };
      }
    }
    return working;
  }

  // Damage component: auto-hit.
  let damageAmount = 0;
  if (ability.damage) {
    damageAmount = resolveDamage({
      attacker: casterTpl,
      defender: targetTpl,
      defenderTerrainKey: terrainKeyAt(state, target),
      moonSky: state.moon.sky,
      attackerAlignment: alignmentOf(caster),
      defenderStatusKeys: target.statuses.map((s) => s.key),
      provider,
      rng,
      damageDealtMod: stanceOf(caster).damageDealtMod,
      damageTakenMod: stanceOf(target).damageTakenMod,
    }).amount;
    const scale = ability.damageScale ?? 1;
    if (scale !== 1) damageAmount = Math.round(damageAmount * scale);
  }

  // Maladiction component: rolls the save; only lands on success.
  let landedStatuses: readonly StatusEffect[] | null = null;
  if (ability.maladiction) {
    const save = rollSave(
      {
        casterInt: casterTpl.stats.int,
        targetWis: targetTpl.stats.wis,
        saves: ability.maladiction.saves,
        baseSave: ability.maladiction.baseSave,
      },
      rng,
    );
    if (save.landed) landedStatuses = [...target.statuses, ability.maladiction.status];
  }

  const tokens = state.tokens.map((t) => {
    if (t.instanceId === casterId) return markActed(t);
    if (t.instanceId === targetId) {
      let nt = damageAmount > 0 ? applyDamageToToken(t, damageAmount) : t;
      if (landedStatuses) nt = withStatuses(nt, landedStatuses);
      return nt;
    }
    return t;
  });
  const applied: MatchState = { ...state, tokens };
  let result = ability.buff ? applyBuff(applied, casterId, targetId, ability.buff) : applied;
  if (ability.heal) result = applyHeal(result, casterId, targetId, ability.heal, casterTpl, provider);
  return result;
}
