import type { Board, BoardToken, Coord, MatchState, Tile } from '../model/index.js';

/** Stable string key for a coord (for Set/Map membership). */
export const coordKey = (c: Coord): string => `${c.x},${c.y}`;

export const coordEquals = (a: Coord, b: Coord): boolean => a.x === b.x && a.y === b.y;

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: inBounds — (no summary)
// @ai-hash: 06d76edb
// ── END AI-METHOD ──
export function inBounds(board: Board, c: Coord): boolean {
  return c.x >= 0 && c.y >= 0 && c.x < board.width && c.y < board.height;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: tileAt — (no summary)
// @ai-hash: 086c1697
// ── END AI-METHOD ──
export function tileAt(board: Board, c: Coord): Tile | undefined {
  return inBounds(board, c) ? board.tiles[c.y][c.x] : undefined;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: tokenAt — (no summary)
// @ai-hash: 6694ab3d
// ── END AI-METHOD ──
/** The token occupying a coord, if any. */
export function tokenAt(state: MatchState, c: Coord): BoardToken | undefined {
  return state.tokens.find((t) => coordEquals(t.pos, c));
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: occupiedKeys — (no summary)
// @ai-hash: bd09925d
// ── END AI-METHOD ──
/** Set of occupied coord keys, optionally excluding one token (e.g. the mover). */
export function occupiedKeys(state: MatchState, exceptTokenId?: string): Set<string> {
  const s = new Set<string>();
  for (const t of state.tokens) {
    if (t.instanceId === exceptTokenId) continue;
    s.add(coordKey(t.pos));
  }
  return s;
}

/** Chebyshev (king-move) distance. */
export const chebyshev = (a: Coord, b: Coord): number =>
  Math.max(Math.abs(a.x - b.x), Math.abs(a.y - b.y));

/** Manhattan distance. */
export const manhattan = (a: Coord, b: Coord): number =>
  Math.abs(a.x - b.x) + Math.abs(a.y - b.y);

/** Unit-step direction offsets for a movement/attack pattern kind. */
export const ORTHOGONAL: readonly Coord[] = [
  { x: 1, y: 0 },
  { x: -1, y: 0 },
  { x: 0, y: 1 },
  { x: 0, y: -1 },
];
export const DIAGONAL: readonly Coord[] = [
  { x: 1, y: 1 },
  { x: 1, y: -1 },
  { x: -1, y: 1 },
  { x: -1, y: -1 },
];
export const OMNI: readonly Coord[] = [...ORTHOGONAL, ...DIAGONAL];
export const KNIGHT: readonly Coord[] = [
  { x: 1, y: 2 },
  { x: 2, y: 1 },
  { x: -1, y: 2 },
  { x: -2, y: 1 },
  { x: 1, y: -2 },
  { x: 2, y: -1 },
  { x: -1, y: -2 },
  { x: -2, y: -1 },
];

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: stepOffsets — (no summary)
// @ai-hash: b4d3a832
// ── END AI-METHOD ──
export function stepOffsets(kind: 'orthogonal' | 'diagonal' | 'omni' | 'knight'): readonly Coord[] {
  switch (kind) {
    case 'orthogonal':
      return ORTHOGONAL;
    case 'diagonal':
      return DIAGONAL;
    case 'omni':
      return OMNI;
    case 'knight':
      return KNIGHT;
  }
}
