import type { ISeededRng } from '../rng/index.js';
import { landingRate, rollSave, SAVE_CONSTANTS } from './saves.js';

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: fixedRng — (no summary)
// @ai-hash: ade3767f
// ── END AI-METHOD ──
/** RNG stub whose `int(max)` always returns a fixed value (so rollSave draws a fixed d100). */
function fixedRng(intResult: number): ISeededRng {
  return {
    next: () => 0,
    int: () => intResult,
    pick: <T>(arr: readonly T[]): T => arr[0],
    state: () => 0,
    clone(): ISeededRng {
      return this;
    },
  };
}

describe('landingRate (SavesCalculator LR formula)', () => {
  it('matches the DSL formula for a sample inside the clamp window', () => {
    // LR = 100 - (30-10)/2 - 30/2 + 0 + 0 = 100 - 10 - 15 = 75
    expect(landingRate({ casterInt: 10, targetWis: 30 })).toBe(75);
    // LR = 100 - (40-10)/2 - 40/2 = 100 - 15 - 20 = 65
    expect(landingRate({ casterInt: 10, targetWis: 40 })).toBe(65);
  });

  it('saves and baseSave each add +2 per point', () => {
    // base (int10/wis30) = 75; + saves*2 + bs*2
    expect(landingRate({ casterInt: 10, targetWis: 30, saves: 3 })).toBe(81);
    expect(landingRate({ casterInt: 10, targetWis: 30, baseSave: 2 })).toBe(79);
  });

  it('clamps to [MIN, MAX]', () => {
    expect(landingRate({ casterInt: 100, targetWis: 0 })).toBe(SAVE_CONSTANTS.MAX); // ~150 → 95
    expect(landingRate({ casterInt: 0, targetWis: 100 })).toBe(SAVE_CONSTANTS.MIN); // 0 → 5
  });
});

describe('rollSave', () => {
  it('lands when the d100 roll is <= landing rate', () => {
    // LR 75; roll = int(100)+1 = 9+1 = 10 <= 75 → lands
    const r = rollSave({ casterInt: 10, targetWis: 30 }, fixedRng(9));
    expect(r.landingRate).toBe(75);
    expect(r.roll).toBe(10);
    expect(r.landed).toBe(true);
  });

  it('misses when the roll exceeds the landing rate', () => {
    // LR 5 (clamped); roll = 89+1 = 90 > 5 → misses
    const r = rollSave({ casterInt: 0, targetWis: 100 }, fixedRng(89));
    expect(r.landingRate).toBe(5);
    expect(r.roll).toBe(90);
    expect(r.landed).toBe(false);
  });
});
