import type { IGameDataProvider } from '../data/index.js';
import type { MatchState, Side, Unit, Squadron } from '../model/index.js';
import { templateForMember } from './squadron.js';

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: turnOrder — (no summary)
// @ai-hash: e180fd40
// ── END AI-METHOD ──
/**
 * Determines the turn order for tokens in the current match state.
 * Returns an array of token instance IDs ordered by initiative (highest first).
 * Initiative is based on the unit's dexterity stat (for units) or the fastest member (for squadrons).
 * For tied initiative, stable sort by instance ID.
 */
export function turnOrder(state: MatchState, provider: IGameDataProvider): string[] {
  // Get all living tokens (units with hp > 0 or squadrons with hpPool > 0)
  const livingTokens = state.tokens.filter(token => {
    if (token.kind === 'unit') {
      return token.hp > 0;
    } else {
      return token.hpPool > 0;
    }
  });

  // Sort by initiative (dexterity for units, fastest member for squadrons)
  return livingTokens
    .map(token => ({
      token,
      initiative: calculateInitiative(token, provider)
    }))
    .sort((a, b) => {
      // Higher initiative first
      if (a.initiative !== b.initiative) {
        return b.initiative - a.initiative;
      }
      // Stable sort by instance ID if initiative is equal
      return a.token.instanceId.localeCompare(b.token.instanceId);
    })
    .map(item => item.token.instanceId);
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: calculateInitiative — (no summary)
// @ai-hash: 371261e5
// ── END AI-METHOD ──
/**
 * Calculates the initiative value for a token based on its dexterity.
 * For units, uses the unit's dexterity directly.
 * For squadrons, uses the dexterity of the fastest member.
 */
function calculateInitiative(token: Unit | Squadron, provider: IGameDataProvider): number {
  // templateForMember resolves a "Race:Class" templateId via provider.unitTemplate.
  if (token.kind === 'unit') {
    return templateForMember(token.templateId, provider).stats.dex;
  }
  // For squadrons, the fastest member sets initiative.
  let fastestDex = -Infinity;
  for (const member of token.members) {
    fastestDex = Math.max(fastestDex, templateForMember(member.templateId, provider).stats.dex);
  }
  return fastestDex;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: nextActiveSide — (no summary)
// @ai-hash: 3d5dca4a
// ── END AI-METHOD ──
/**
 * Determines the next active side in the turn order.
 * Cycles through sides in order, wrapping around when reaching the end.
 */
export function nextActiveSide(state: MatchState): Side {
  // Count how many distinct sides have living tokens
  const sidesWithTokens = new Set<Side>();
  for (const token of state.tokens) {
    if (token.kind === 'unit' && token.hp > 0) {
      sidesWithTokens.add(token.side);
    } else if (token.kind === 'squadron' && token.hpPool > 0) {
      sidesWithTokens.add(token.side);
    }
  }
  
  // If no sides have tokens, return 0
  if (sidesWithTokens.size === 0) {
    return 0;
  }
  
  // Cycle through sides in order
  const sortedSides = Array.from(sidesWithTokens).sort((a, b) => a - b);
  const currentSideIndex = sortedSides.indexOf(state.activeSide);
  const nextIndex = (currentSideIndex + 1) % sortedSides.length;
  
  return sortedSides[nextIndex];
}