import type { IGameDataProvider } from '../data/index.js';
import type { Board, Coord, GameModeConfig, MatchState, Tile, TileFeature, Unit } from '../model/index.js';
import { evaluateVictory } from './victory.js';

// --- test doubles -----------------------------------------------------------

const provider = {} as unknown as IGameDataProvider; // victory does not use the provider

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: mode — (no summary)
// @ai-hash: 2d93d196
// ── END AI-METHOD ──
function mode(victory: GameModeConfig['victory']): GameModeConfig {
  return {
    id: 'skirmish',
    name: 'Test',
    sides: 2,
    budget: 100,
    budgetKind: 'points',
    scale: 'skirmish',
    usesSquadrons: false,
    victory,
    board: { width: 10, height: 10 },
    terrainProfile: 'arena',
    asymmetric: false,
  };
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: board — (no summary)
// @ai-hash: d2be9e4e
// ── END AI-METHOD ──
function board(w: number, h: number, featureAt?: (c: Coord) => TileFeature | null): Board {
  const tiles: Tile[][] = [];
  for (let y = 0; y < h; y++) {
    const row: Tile[] = [];
    for (let x = 0; x < w; x++) row.push({ terrain: 'Field', feature: featureAt?.({ x, y }) ?? null });
    tiles.push(row);
  }
  return { width: w, height: h, tiles };
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: unit — (no summary)
// @ai-hash: 61beeb7f
// ── END AI-METHOD ──
function unit(instanceId: string, side: number, hp: number, pos: Coord = { x: 0, y: 0 }): Unit {
  return { kind: 'unit', instanceId, templateId: 'Test:Unit', side, pos, hp, statuses: [], hasMoved: false, hasActed: false };
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: state — (no summary)
// @ai-hash: dcd9970f
// ── END AI-METHOD ──
function state(b: Board, tokens: Unit[]): MatchState {
  return {
    modeId: 'skirmish',
    board: b,
    armies: [],
    tokens,
    turn: 1,
    activeSide: 0,
    moon: { type: 'White', phase: 'FullMoon' },
    rngState: 1,
    status: 'in-progress',
  };
}

// --- tests ------------------------------------------------------------------

describe('evaluateVictory — rout', () => {
  it('is undecided while multiple sides live', () => {
    const s = state(board(10, 10), [unit('a', 0, 20), unit('b', 1, 20)]);
    expect(evaluateVictory(s, mode('rout'), provider)).toEqual({ decided: false });
  });
  it('awards the last side standing', () => {
    const s = state(board(10, 10), [unit('a', 0, 20), unit('b', 1, 0)]);
    expect(evaluateVictory(s, mode('rout'), provider)).toEqual({ decided: true, winner: 0 });
  });
  it('is a draw when no side lives', () => {
    const s = state(board(10, 10), [unit('a', 0, 0), unit('b', 1, 0)]);
    expect(evaluateVictory(s, mode('rout'), provider)).toEqual({ decided: true, winner: 'draw' });
  });
});

describe('evaluateVictory — control-point', () => {
  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: cp — (no summary)
  // @ai-hash: edfd4f48
  // ── END AI-METHOD ──
  const cp = (c: Coord): TileFeature | null =>
    c.x === 5 && c.y === 5 ? { kind: 'control-point' } : null;

  it('is undecided when the point is uncontested', () => {
    const s = state(board(10, 10, cp), [unit('a', 0, 20, { x: 0, y: 0 })]);
    expect(evaluateVictory(s, mode('control-point'), provider)).toEqual({ decided: false });
  });
  it('awards the side occupying the sole control point', () => {
    const s = state(board(10, 10, cp), [unit('a', 0, 20, { x: 5, y: 5 })]);
    expect(evaluateVictory(s, mode('control-point'), provider)).toEqual({ decided: true, winner: 0 });
  });
});

describe('evaluateVictory — destroy-objective', () => {
  // ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
  // @ai-method: objective — (no summary)
  // @ai-hash: bf1cbba2
  // ── END AI-METHOD ──
  const objective = (owner: number, hp: number) => (c: Coord): TileFeature | null =>
    c.x === 5 && c.y === 5 ? { kind: 'objective', owner, hp } : null;

  it('is undecided while the objective still has hp', () => {
    const s = state(board(10, 10, objective(1, 10)), [unit('a', 0, 20), unit('d', 1, 20)]);
    expect(evaluateVictory(s, mode('destroy-objective'), provider)).toEqual({ decided: false });
  });
  it('awards the attacker (non-owner) once the objective is destroyed', () => {
    const s = state(board(10, 10, objective(1, 0)), [unit('a', 0, 20), unit('d', 1, 20)]);
    expect(evaluateVictory(s, mode('destroy-objective'), provider)).toEqual({ decided: true, winner: 0 });
  });
});

describe('evaluateVictory — survive-waves', () => {
  it('side 0 wins once no enemy remains', () => {
    const s = state(board(10, 10), [unit('a', 0, 20), unit('e', 1, 0)]);
    expect(evaluateVictory(s, mode('survive-waves'), provider)).toEqual({ decided: true, winner: 0 });
  });
  it('undecided while an enemy lives', () => {
    const s = state(board(10, 10), [unit('a', 0, 20), unit('e', 1, 20)]);
    expect(evaluateVictory(s, mode('survive-waves'), provider)).toEqual({ decided: false });
  });
});

describe('evaluateVictory — decided passthrough', () => {
  it('reports a recorded winner without re-evaluating', () => {
    const s: MatchState = { ...state(board(2, 2), []), status: 'decided', winner: 1 };
    expect(evaluateVictory(s, mode('rout'), provider)).toEqual({ decided: true, winner: 1 });
  });
});
