// apps/game-client/src/hooks/useBottomPane.ts
import { useState } from 'react';
import { useEnemyHudState } from './useRightPaneHud';

export type BottomTab = 'compass' | 'opponent' | 'damage' | 'chat' | 'misc';

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: useBottomPane — Manages bottom pane state including tab selection and enemy health percentage.
// @ai-hash: 98c1f14c
// ── END AI-METHOD ──
export function useBottomPane() {
  const [activeTab, setActiveTab] = useState<BottomTab>('chat');
  const enemy = useEnemyHudState();

  const clampedPct = Math.max(0, Math.min(100, enemy.pct));

  const selectTab = (tab: BottomTab) => {
    setActiveTab(tab);
  };

  return {
    activeTab,
    selectTab,
    enemy,
    clampedPct,
  };
}
