// apps/game-client/src/hooks/useCharData.ts
import { useEffect, useState } from 'react';
import { ListenEvent } from '../features/event-emitter/event-dispatcher';
import { getCharData, setCharData } from '../features/charData/charDataStore';

export interface CharDataVitals {
  hp: number;
  hpMax: number;
  mp: number;
  mpMax: number;
  stamina: number;
  staminaMax: number;
}

export interface CharDataAncillary {
  carryWeight: number | null;
  carryWeightMax: number | null;
  carryWeightPct: number | null;
  isQuiet: boolean;
  isFlying: boolean;
  isRiding: boolean;
  isFighting: boolean;
  language: string | null;
}

const defaultVitals: CharDataVitals = {
  hp: 0,
  hpMax: 0,
  mp: 0,
  mpMax: 0,
  stamina: 0,
  staminaMax: 0,
};

const defaultAncillary: CharDataAncillary = {
  carryWeight: null,
  carryWeightMax: null,
  carryWeightPct: null,
  isQuiet: false,
  isFlying: false,
  isRiding: false,
  isFighting: false,
  language: null,
};

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: useCharData — Updates character vitals and ancillary data from game events.
// @ai-hash: c0d645ef
// ── END AI-METHOD ──
export function useCharData() {
  // Seed from charDataStore so a remount — a live theme switch, e.g. —
  // doesn't flash 0/0 vitals until the next game:char-data event.
  const [vitals, setVitals] = useState<CharDataVitals>(() => getCharData()?.vitals ?? defaultVitals);
  const [ancillary, setAncillary] = useState<CharDataAncillary>(() => getCharData()?.ancillary ?? defaultAncillary);

  useEffect(() => {
    const dispose = ListenEvent<any>(
      'game:char-data',
      (data) => {
        const d = data ?? {};

        const hp = Number(d.hp ?? 0);
        const maxHp = Number(d.max_hp ?? 0);
        const mana = Number(d.mana ?? 0);
        const maxMana = Number(d.max_mana ?? 0);
        const move = Number(d.move ?? 0);
        const maxMove = Number(d.max_move ?? 0);

        const carryWeightRaw = Number(d.carry_weight ?? NaN);
        const canCarryWeightRaw = Number(d.can_carry_weight ?? NaN);

        const hasCarry = Number.isFinite(carryWeightRaw);
        const hasCarryMax = Number.isFinite(canCarryWeightRaw) && canCarryWeightRaw > 0;

        const carryWeight = hasCarry ? carryWeightRaw : null;
        const carryWeightMax = hasCarryMax ? canCarryWeightRaw : null;

        const carryWeightPct =
          hasCarry && hasCarryMax ? Math.max(0, Math.min(100, (carryWeightRaw / canCarryWeightRaw) * 100)) : null;

        const nextVitals: CharDataVitals = {
          hp,
          hpMax: maxHp,
          mp: mana,
          mpMax: maxMana,
          stamina: move,
          staminaMax: maxMove,
        };

        const nextAncillary: CharDataAncillary = {
          carryWeight,
          carryWeightMax,
          carryWeightPct,
          isQuiet: !!d.is_quiet,
          isFlying: !!d.is_flying,
          isRiding: !!d.is_riding,
          isFighting: !!d.is_fighting,
          language: typeof d.language === 'string' ? d.language : null,
        };

        setVitals(nextVitals);
        setAncillary(nextAncillary);
        setCharData({ vitals: nextVitals, ancillary: nextAncillary });
      },
      { key: 'vitalsAncillary::game:char-data' },
    );

    return () => {
      try {
        dispose?.();
      } catch {
        // ignore
      }
    };
  }, []);

  return { vitals, ancillary };
}

export interface StatusPiece {
  key: string;
  text: string;
  title: string;
}

// Extracted from RightSidebar.tsx's StatusBlock so both the classic and
// compact layouts render the same status icons from the same rules.
export function computeStatusPieces(ancillary: CharDataAncillary): StatusPiece[] {
  const pieces: StatusPiece[] = [];

  if (ancillary.carryWeight != null && ancillary.carryWeightMax != null && ancillary.carryWeightPct != null) {
    const cw = ancillary.carryWeight.toFixed(0);
    const cwm = ancillary.carryWeightMax.toFixed(0);
    const cwp = ancillary.carryWeightPct.toFixed(0);

    pieces.push({
      key: 'carry',
      text: `🧺 ${cw} / ${cwm} (${cwp}%)`,
      title: `Carry weight: ${cw} / ${cwm} (${cwp}%)`,
    });
  }

  if (ancillary.isQuiet) pieces.push({ key: 'quiet', text: '🔇', title: 'Quiet (deafened)' });
  if (ancillary.isFlying) pieces.push({ key: 'flying', text: '🪽', title: 'Flying' });
  if (ancillary.isRiding) pieces.push({ key: 'riding', text: '🐎', title: 'Riding' });
  if (ancillary.isFighting) pieces.push({ key: 'fighting', text: '⚔️', title: 'Fighting' });

  if (ancillary.language && ancillary.language.toLowerCase() !== 'common') {
    pieces.push({ key: 'language', text: `💬 ${ancillary.language}`, title: `Language: ${ancillary.language}` });
  }

  return pieces;
}
