// apps/game-client/src/hooks/useCompassBlock.ts
import { useCallback, useEffect, useMemo, useState } from 'react';
import { getRoomData, setRoomData } from '../features/room/roomDataStore';
import { DispatchEvent, ListenEvent } from '../features/event-emitter/event-dispatcher';
import { exitsToSet, DIR_TO_COMMAND, type CompassDirection } from '../features/movement/classifyMovement';

// Re-exported so existing consumers (CompassBlock.tsx, CompassBlockMobile.tsx,
// useRightPaneHud.ts, useLayoutShell.ts) keep importing from this module unchanged —
// the real definitions now live in the shared classifyMovement.ts.
export type { CompassDirection };

export type RoomDataPayload = {
  room?: string;
  sector?: string;
  exits?: string[];
};

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: useCompassBlock — Manages compass block exit states and movement logic for room navigation.
// @ai-hash: 3d265672
// ── END AI-METHOD ──
export function useCompassBlock() {
  // Seed from roomDataStore so tab switching keeps exits
  const [exitSet, setExitSet] = useState<Set<CompassDirection>>(() => {
    const cached = getRoomData();
    return exitsToSet(cached?.exits);
  });

  /* ---------------------------------------------
   * Room exit updates — display only. Movement success/failure is the shared
   * movementTracker's job now (features/movement/movementTracker.ts, bound once at
   * app scope in MainContainer.tsx) — it listens to the same game:room-data event
   * independently, so this effect no longer needs to touch pending-move state at all.
   * ------------------------------------------- */
  useEffect(() => {
    const dispose = ListenEvent<RoomDataPayload>(
      'game:room-data',
      (payload) => {
        const safe = payload ?? ({} as RoomDataPayload);
        setRoomData(safe);
        setExitSet(exitsToSet(safe.exits));
      },
      { key: 'roomData::game:room-data' },
    );

    return () => {
      try {
        dispose?.();
      } catch {
        // ignore
      }
    };
  }, []);

  /* ---------------------------------------------
   * Movement attempt — just send it. movementTracker enqueues it automatically off
   * the shatteredarchive:command-sent signal (fired from sendTelnetData once this
   * actually reaches the wire) and dispatches movement-succeeded/-failed itself once
   * it resolves; no local pending-move/timeout bookkeeping needed here anymore.
   * ------------------------------------------- */
  const move = useCallback((dir: CompassDirection) => {
    const cmd = DIR_TO_COMMAND[dir];
    if (!cmd) return;
    DispatchEvent('shatteredarchive:send-command', { cmd });
  }, []);

  const hasExit = useMemo(() => (dir: CompassDirection) => exitSet.has(dir), [exitSet]);

  return {
    hasExit,
    move,
  };
}
