// apps\game-client\src\hooks\useEquipmentState.ts
import { useEffect, useMemo, useSyncExternalStore } from 'react';
import {
  getEquipmentPrefs,
  getEquipmentProfile,
  getEquipmentState,
  hydrateEquipment,
  subscribeEquipment,
} from '../features/equipment/equipment-store';

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: useEquipmentState — Returns synchronized equipment state, preferences, and profile data for a connection.
// @ai-hash: fa953c83
// ── END AI-METHOD ──
export function useEquipmentState(connectionId: string) {
  // one-time hydrate per connectionId
  useEffect(() => {
    void hydrateEquipment(connectionId);
  }, [connectionId]);

  const state = useSyncExternalStore(
    subscribeEquipment,
    () => getEquipmentState(connectionId),
    () => getEquipmentState(connectionId),
  );

  const prefs = useSyncExternalStore(
    subscribeEquipment,
    () => getEquipmentPrefs(connectionId),
    () => getEquipmentPrefs(connectionId),
  );

  const profile = useSyncExternalStore(
    subscribeEquipment,
    () => getEquipmentProfile(connectionId),
    () => getEquipmentProfile(connectionId),
  );

  return useMemo(() => ({ state, prefs, profile }), [state, prefs, profile]);
}
