// apps\game-client\src\hooks\useMainContainer.ts
import { useState, useEffect, useCallback, CSSProperties, useRef } from 'react';
import type React from 'react';
import { initBrowserLuaRunner } from '../features/userScripts/luaRuntime';
import { ensureAudioRuntimeAttached } from '../features/audio/audio-runtime';
import { getAccessibilitySettings } from '../features/accessibility/accessibility-settings-store';

/* -------------------------------------------
   Layout constants
-------------------------------------------- */
/** Min width of SideBar.tsx */
const MIN_RIGHT_WIDTH = 220;
/** Max width of SideBar.tsx */
const MAX_RIGHT_WIDTH = 640;

/** Min height of BottomPane.tsx */
const MIN_BOTTOM_HEIGHT = 120;
/** Max height of BottomPane.tsx */
const MAX_BOTTOM_HEIGHT = 480;

const LS_RIGHT_WIDTH = 'shatteredArchive.layout.rightPaneWidth';
const LS_BOTTOM_HEIGHT = 'shatteredArchive.layout.bottomPaneHeight';

/* -------------------------------------------
   User CSS constants / helpers
-------------------------------------------- */
/** Local storage key for CSS overrides */
const USER_CSS_KEY = 'shatteredArchive.userCssOverride';
/** ID of user css override */
const USER_CSS_STYLE_ID = 'user-css-override-style';

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: clamp — Clamps a number between minimum and maximum values, returning the nearest valid boundary if out of range.
// @ai-hash: 04673440
// ── END AI-METHOD ──
function clamp(n: number, min: number, max: number) {
  if (!Number.isFinite(n)) return min;
  if (n < min) return min;
  if (n > max) return max;
  return n;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: buildAccessibilityCss — Generates responsive font scaling and high-contrast CSS overrides based on accessibility settings.
// @ai-hash: 8bddbea6
// ── END AI-METHOD ──
function buildAccessibilityCss(): string {
  const settings = getAccessibilitySettings();

  const fontScale = clamp(Number(settings.fontScale ?? 1), 0.8, 1.6);

  const fontCss = `
/* [sa-accessibility] Font scale */
:root { --sa-font-scale: ${fontScale}; }
html { font-size: calc(16px * var(--sa-font-scale)); }
`.trim();

  const highContrastCss = settings.preferHighContrast
    ? `
/* [sa-accessibility] Prefer high contrast UI (reasonable) */
#root {
  /* Core palette */
  --sa-hc-bg: #0b0c0f;
  --sa-hc-surface: #12141a;
  --sa-hc-surface2: #171a22;

  --sa-hc-text: #f5f7ff;
  --sa-hc-muted: #c5ccdd;

  --sa-hc-border: #3a4153;
  --sa-hc-border-strong: #6b7590;

  --sa-hc-accent: #7dd3fc;      /* cyan-ish */
  --sa-hc-accent2: #a78bfa;     /* purple-ish */
  --sa-hc-danger: #fb7185;

  --sa-hc-focus: #fbbf24;       /* amber focus ring */
  --sa-hc-shadow: rgba(0, 0, 0, 0.55);

  background: var(--sa-hc-bg) !important;
  color: var(--sa-hc-text) !important;
}

/* Text hierarchy */
#root .muted,
#root [data-muted="true"] {
  color: var(--sa-hc-muted) !important;
}

/* Surfaces (common containers) */
#root .panel,
#root .card,
#root .modal,
#root [role="dialog"],
#root .rightPane,
#root .leftNav {
  background: var(--sa-hc-surface) !important;
  color: var(--sa-hc-text) !important;
  border-color: var(--sa-hc-border) !important;
  box-shadow: 0 8px 24px var(--sa-hc-shadow);
}

/* Dividers */
#root hr,
#root .divider {
  border-color: var(--sa-hc-border) !important;
  opacity: 1 !important;
}

/* Links */
#root a {
  color: var(--sa-hc-accent) !important;
  text-decoration: underline;
  text-underline-offset: 2px;
}
#root a:hover {
  color: #b7ecff !important;
}

/* Buttons */
#root button,
#root [role="button"],
#root input[type="button"],
#root input[type="submit"] {
  background: var(--sa-hc-surface2) !important;
  color: var(--sa-hc-text) !important;
  border: 1px solid var(--sa-hc-border-strong) !important;
}

#root button:hover,
#root [role="button"]:hover {
  border-color: var(--sa-hc-accent) !important;
}

#root button:disabled,
#root input:disabled,
#root select:disabled,
#root textarea:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

/* Inputs */
#root input,
#root textarea,
#root select {
  background: #0e1016 !important;
  color: var(--sa-hc-text) !important;
  border: 1px solid var(--sa-hc-border-strong) !important;
}
#root input::placeholder,
#root textarea::placeholder {
  color: #9aa6bf !important;
  opacity: 1;
}

/* Checkbox / radio accent */
#root input[type="checkbox"],
#root input[type="radio"] {
  accent-color: var(--sa-hc-accent);
}

/* Selection */
#root ::selection {
  background: rgba(125, 211, 252, 0.35);
}

/* Focus: make it obvious and consistent */
#root :focus-visible {
  outline: 3px solid var(--sa-hc-focus) !important;
  outline-offset: 2px;
}

/* Scrollbars (Chromium / Edge) */
#root *::-webkit-scrollbar {
  width: 12px;
  height: 12px;
}
#root *::-webkit-scrollbar-thumb {
  background: #3b4256;
  border: 2px solid var(--sa-hc-surface);
  border-radius: 10px;
}
#root *::-webkit-scrollbar-thumb:hover {
  background: #4b5470;
}
#root *::-webkit-scrollbar-corner {
  background: var(--sa-hc-surface);
}
`.trim()
    : '';

  return [fontCss, highContrastCss].filter(Boolean).join('\n\n');
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: ensureStyleTag — Ensures a style tag with the given ID exists in the document head, returning the element or null if unavailable.
// @ai-hash: 6505d691
// ── END AI-METHOD ──
function ensureStyleTag(id: string): HTMLStyleElement | null {
  if (typeof document === 'undefined') return null;

  const head = document.head || document.getElementsByTagName('head')[0];
  if (!head) return null;

  let el = document.getElementById(id);

  // If something else stole the id, delete it.
  if (el && el.tagName.toLowerCase() !== 'style') {
    el.parentElement?.removeChild(el);
    el = null;
  }

  const styleEl = (el as HTMLStyleElement) ?? document.createElement('style');
  styleEl.id = id;

  // Always move to end of <head> so it wins the cascade.
  head.appendChild(styleEl);

  return styleEl;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: applyUserCss — Updates the user CSS stylesheet with the provided CSS content.
// @ai-hash: feff094a
// ── END AI-METHOD ──
function applyUserCss(css: string) {
  const styleEl = ensureStyleTag(USER_CSS_STYLE_ID);
  if (!styleEl) return;

  styleEl.textContent = css || '';
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: applyCombinedCss — Combines user and accessibility CSS into a single stylesheet and applies it to the document.
// @ai-hash: 02b6a2c9
// ── END AI-METHOD ──
function applyCombinedCss(userCss: string) {
  const accessibilityCss = buildAccessibilityCss();

  const combined = `
/* =========================================================
   Shattered Archive CSS Overrides
   ========================================================= */

/* [user-css] */
${userCss ?? ''}

/* [accessibility-css] */
${accessibilityCss ?? ''}
`.trim();

  applyUserCss(combined);
}

/* -------------------------------------------
   Layout sizing
-------------------------------------------- */
// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: useLayoutSizing — Manages resizable layout pane dimensions with persistent storage and mouse interaction.
// @ai-hash: 6b668e2c
// ── END AI-METHOD ──
export function useLayoutSizing() {
  const [rightWidth, setRightWidth] = useState(() => {
    try {
      const raw = window.localStorage.getItem(LS_RIGHT_WIDTH);
      const n = raw ? Number(raw) : NaN;
      return Number.isFinite(n) ? clamp(n, MIN_RIGHT_WIDTH, MAX_RIGHT_WIDTH) : 320;
    } catch {
      return 320;
    }
  });

  const [bottomHeight, setBottomHeight] = useState(() => {
    try {
      const raw = window.localStorage.getItem(LS_BOTTOM_HEIGHT);
      const n = raw ? Number(raw) : NaN;
      return Number.isFinite(n) ? clamp(n, MIN_BOTTOM_HEIGHT, MAX_BOTTOM_HEIGHT) : 220;
    } catch {
      return 220;
    }
  });

  // Persist on change
  useEffect(() => {
    try {
      window.localStorage.setItem(LS_RIGHT_WIDTH, String(rightWidth));
    } catch {
      // ignore
    }
  }, [rightWidth]);

  useEffect(() => {
    try {
      window.localStorage.setItem(LS_BOTTOM_HEIGHT, String(bottomHeight));
    } catch {
      // ignore
    }
  }, [bottomHeight]);

  const layoutVars: CSSProperties = {
    '--right-pane-width': `${rightWidth}px`,
    '--bottom-pane-height': `${bottomHeight}px`,
  } as CSSProperties;

  const handleVerticalResizeMouseDown = useCallback(
    (e: React.MouseEvent<HTMLDivElement>) => {
      e.preventDefault();

      const startX = e.clientX;
      const startWidth = rightWidth;

      const onMouseMove = (ev: MouseEvent) => {
        const delta = startX - ev.clientX;
        const nextWidth = clamp(startWidth + delta, MIN_RIGHT_WIDTH, MAX_RIGHT_WIDTH);
        setRightWidth(nextWidth);
      };

      const onMouseUp = () => {
        window.removeEventListener('mousemove', onMouseMove);
        window.removeEventListener('mouseup', onMouseUp);
        document.body.style.userSelect = '';
      };

      document.body.style.userSelect = 'none';
      window.addEventListener('mousemove', onMouseMove);
      window.addEventListener('mouseup', onMouseUp);
    },
    [rightWidth],
  );

  const handleHorizontalResizeMouseDown = useCallback(
    (e: React.MouseEvent<HTMLDivElement>) => {
      e.preventDefault();

      const startY = e.clientY;
      const startHeight = bottomHeight;

      const onMouseMove = (ev: MouseEvent) => {
        const delta = startY - ev.clientY; // move up => positive => grow
        const nextHeight = clamp(startHeight + delta, MIN_BOTTOM_HEIGHT, MAX_BOTTOM_HEIGHT);
        setBottomHeight(nextHeight);
      };

      const onMouseUp = () => {
        window.removeEventListener('mousemove', onMouseMove);
        window.removeEventListener('mouseup', onMouseUp);
        document.body.style.userSelect = '';
      };

      document.body.style.userSelect = 'none';
      window.addEventListener('mousemove', onMouseMove);
      window.addEventListener('mouseup', onMouseUp);
    },
    [bottomHeight],
  );

  return {
    layoutVars,
    handleVerticalResizeMouseDown,
    handleHorizontalResizeMouseDown,
  };
}

/* -------------------------------------------
   Hook: top menu state
-------------------------------------------- */
type GameSettingsSection = 'Graphics' | 'Audio' | null;

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: useMenuState — Manages global menu state and provides toggle/close functions for root menus and game settings.
// @ai-hash: 4b4a4251
// ── END AI-METHOD ──
export function useMenuState() {
  const [openRootMenu, setOpenRootMenu] = useState<string | null>(null);
  const [isGameSettingsOpen, setIsGameSettingsOpen] = useState(false);
  const [openGameSettingsSection, setOpenGameSettingsSection] = useState<GameSettingsSection>(null);

  const toggleRootMenu = (id: string) => {
    setOpenRootMenu((prev) => (prev === id ? null : id));
    setIsGameSettingsOpen(false);
    setOpenGameSettingsSection(null);
  };

  const closeAllMenus = () => {
    setOpenRootMenu(null);
    setIsGameSettingsOpen(false);
    setOpenGameSettingsSection(null);
  };

  const toggleGameSettings = (e: React.MouseEvent) => {
    e.stopPropagation();
    setIsGameSettingsOpen((prev) => !prev);
    setOpenGameSettingsSection(null);
  };

  const toggleGameSettingsSection = (e: React.MouseEvent, section: Exclude<GameSettingsSection, null>) => {
    e.stopPropagation();
    setOpenGameSettingsSection((prev) => (prev === section ? null : section));
  };

  return {
    openRootMenu,
    isGameSettingsOpen,
    openGameSettingsSection,
    toggleRootMenu,
    closeAllMenus,
    toggleGameSettings,
    toggleGameSettingsSection,
  };
}

/* -------------------------------------------
   Hook: user CSS overrides + modal state
-------------------------------------------- */
// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: useUserCssOverrides — Manages user-defined CSS overrides with draft handling, persistence, and real-time preview functionality.
// @ai-hash: 7d777b43
// ── END AI-METHOD ──
export function useUserCssOverrides() {
  const [userCssApplied, setUserCssApplied] = useState<string>('');
  const [userCssDraft, _setUserCssDraft] = useState<string>('');
  const [isStyleModalOpen, setIsStyleModalOpen] = useState(false);

  // Holds the latest draft synchronously (avoids “click Save before last onChange commits”)
  const draftRef = useRef<string>('');
  const appliedRef = useRef<string>('');

  const setUserCssDraft = (css: string) => {
    draftRef.current = css ?? '';
    _setUserCssDraft(css ?? '');
  };

  useEffect(() => {
    try {
      const stored = window.localStorage.getItem(USER_CSS_KEY) || '';
      setUserCssApplied(stored);
      appliedRef.current = stored;

      setUserCssDraft(stored);

      applyCombinedCss(stored);
    } catch {
      // ignore localStorage errors
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // keep refs in sync with state
  useEffect(() => {
    appliedRef.current = userCssApplied;
  }, [userCssApplied]);

  // When accessibility settings change, re-apply combined CSS (using current applied user css)
  useEffect(() => {
    const onUpdated = () => {
      applyCombinedCss(appliedRef.current);
    };

    window.addEventListener('shatteredarchive:accessibility-updated', onUpdated);
    return () => window.removeEventListener('shatteredarchive:accessibility-updated', onUpdated);
  }, []);

  const openStyleModal = () => setIsStyleModalOpen(true);

  const closeStyleModal = () => {
    // revert any preview to applied on close
    applyCombinedCss(appliedRef.current);
    setIsStyleModalOpen(false);
  };

  // Accept explicit cssArg (best), otherwise fall back to ref (safe), then state.
  const saveUserCss = (cssArg?: string) => {
    const css = (cssArg ?? draftRef.current ?? userCssDraft) || '';

    setUserCssApplied(css);
    appliedRef.current = css;

    // Keep draft in sync after save (so modal reads correctly if reopened immediately)
    setUserCssDraft(css);

    applyCombinedCss(css);

    try {
      if (css.trim()) {
        window.localStorage.setItem(USER_CSS_KEY, css);
      } else {
        window.localStorage.removeItem(USER_CSS_KEY);
      }
    } catch {
      // ignore storage errors
    }
  };

  // Apply combined but do NOT persist
  const previewDraft = (cssArg?: string) => {
    const css = (cssArg ?? draftRef.current ?? userCssDraft) || '';
    applyCombinedCss(css);
  };

  const discardDraft = () => {
    setUserCssDraft(appliedRef.current);
    applyCombinedCss(appliedRef.current);
  };

  return {
    userCssApplied,
    userCssDraft,
    setUserCssDraft,
    isStyleModalOpen,
    openStyleModal,
    closeStyleModal,
    saveUserCss,
    previewDraft,
    discardDraft,
  };
}

/* -------------------------------------------
   Hook: main initialization + connect modal + library modal
-------------------------------------------- */
// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: useMainContainer — Initializes Lua runtime and audio capabilities while managing three modal open states.
// @ai-hash: 889b4d02
// ── END AI-METHOD ──
export function useMainContainer() {
  useEffect(() => {
    if (typeof window !== 'undefined') {
      try {
        initBrowserLuaRunner();
      } catch (err) {
        console.error('[Lua] Failed to initialize Lua runtime:', err);
      }
    }
  }, []);

  useEffect(() => {
    ensureAudioRuntimeAttached();
  }, []);

  const [isConnectModalOpen, setIsConnectModalOpen] = useState(false);
  const openConnectModal = () => setIsConnectModalOpen(true);
  const closeConnectModal = () => setIsConnectModalOpen(false);

  const [isLibraryModalOpen, setIsLibraryModalOpen] = useState(false);
  const openLibraryModal = () => setIsLibraryModalOpen(true);
  const closeLibraryModal = () => setIsLibraryModalOpen(false);

  const [isEquipmentModalOpen, setIsEquipmentModalOpen] = useState(false);
  const openEquipmentModal = () => setIsEquipmentModalOpen(true);
  const closeEquipmentModal = () => setIsEquipmentModalOpen(false);

  return {
    isConnectModalOpen,
    openConnectModal,
    closeConnectModal,

    isLibraryModalOpen,
    openLibraryModal,
    closeLibraryModal,

    isEquipmentModalOpen,
    openEquipmentModal,
    closeEquipmentModal,
  };
}
