// apps\game-client\src\hooks\useMiscPane.ts
import { useState } from 'react';

export type MiscSection = 'bestiary' | 'archives' | 'autopilot' | 'log';

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: useMiscPane — Manages the active section state for a miscellaneous pane component.
// @ai-hash: 79f4248d
// ── END AI-METHOD ──
export function useMiscPane() {
  const [activeSection, setActiveSection] = useState<MiscSection>('bestiary');

  return {
    activeSection,
    setActiveSection,
  };
}
