import { useEffect, useState } from 'react';

const PLUGIN_CSS_KEY_PREFIX = 'shatteredArchive.pluginCssOverride.';
const PLUGIN_CSS_STYLE_ID_PREFIX = 'plugin-css-override-style-';

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: getStorageKey — Returns a formatted storage key combining connection ID and plugin ID with a CSS prefix.
// @ai-hash: 86a22d81
// ── END AI-METHOD ──
function getStorageKey(connectionId: string, pluginId: string) {
  const c = connectionId && connectionId.trim().length > 0 ? connectionId.trim() : 'default';
  return `${PLUGIN_CSS_KEY_PREFIX}${c}.${pluginId}`;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: getStyleId — Returns a styled CSS ID by combining connection and plugin identifiers.
// @ai-hash: 64fe995b
// ── END AI-METHOD ──
function getStyleId(connectionId: string, pluginId: string) {
  const c = connectionId && connectionId.trim().length > 0 ? connectionId.trim() : 'default';
  return `${PLUGIN_CSS_STYLE_ID_PREFIX}${c}-${pluginId}`;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: applyPluginUserCss — Applies CSS styles to a document for a specific plugin connection, creating or updating a style element as needed.
// @ai-hash: ddb3a88e
// ── END AI-METHOD ──
export function applyPluginUserCss(connectionId: string, pluginId: string, css: string) {
  if (typeof document === 'undefined') return;

  const styleId = getStyleId(connectionId, pluginId);
  let styleEl = document.getElementById(styleId) as HTMLStyleElement | null;

  if (!styleEl) {
    styleEl = document.createElement('style');
    styleEl.id = styleId;
    document.head.appendChild(styleEl);
  }

  styleEl.textContent = css || '';
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: removePluginUserCss — Removes a plugin's user CSS style element from the document by its ID.
// @ai-hash: d683e83f
// ── END AI-METHOD ──
export function removePluginUserCss(connectionId: string, pluginId: string) {
  if (typeof document === 'undefined') return;
  const styleId = getStyleId(connectionId, pluginId);
  const el = document.getElementById(styleId);
  if (el && el.parentNode) el.parentNode.removeChild(el);
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: usePluginCssOverrides — Manages CSS overrides for a plugin by handling storage, application, and UI state for user-defined styles.
// @ai-hash: fb5b731a
// ── END AI-METHOD ──
export function usePluginCssOverrides(connectionId: string, pluginId: string) {
  const [appliedCss, setAppliedCss] = useState<string>('');
  const [draftCss, setDraftCss] = useState<string>('');
  const [isOpen, setIsOpen] = useState<boolean>(false);

  useEffect(() => {
    try {
      const key = getStorageKey(connectionId, pluginId);
      const stored = window.localStorage.getItem(key) || '';
      setAppliedCss(stored);
      setDraftCss(stored);
      applyPluginUserCss(connectionId, pluginId, stored);
    } catch {
      // ignore
    }
  }, [connectionId, pluginId]);

  const open = () => setIsOpen(true);
  const close = () => setIsOpen(false);

  const save = (cssArg?: string) => {
    const css = cssArg ?? draftCss;

    setAppliedCss(css);
    setDraftCss(css);
    applyPluginUserCss(connectionId, pluginId, css);

    try {
      const key = getStorageKey(connectionId, pluginId);
      if (css.trim()) {
        window.localStorage.setItem(key, css);
      } else {
        window.localStorage.removeItem(key);
      }
    } catch {
      // ignore
    }
  };

  const discardDraft = () => {
    setDraftCss(appliedCss);
  };

  return {
    appliedCss,
    draftCss,
    setDraftCss,
    isOpen,
    open,
    close,
    save,
    discardDraft,
  };
}
