// apps\game-client\src\hooks\usePlugins.ts
import { useCallback, useMemo, useState } from 'react';
import type { PluginId } from '@shatteredarchive/types-client';
import { findCorePlugin } from '../features/plugins/registry';

/* -------------------------------------------
   Types (local to game-client)
-------------------------------------------- */

export type InstalledPluginRecord = {
  id: PluginId;
  name: string;
  version: string;
  description?: string;
  author?: string;
  enabled: boolean;
  installedAt: number;
  userConfig: Record<string, unknown>;
  kind: string;
};

/* -------------------------------------------
   Storage
-------------------------------------------- */

// Exported so Phase D's cloud sync (features/auth/AccountModal) can read/write
// the same global (non-connection-scoped) key without duplicating it.
export const PLUGINS_STORAGE_KEY = 'shatteredArchive.plugins.installed';
const LEGACY_KEY_PREFIX = 'shatteredArchive.plugins.installed.';

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: migrateLegacyStorage — Migrates legacy plugin storage entries to new format and cleans up old entries.
// @ai-hash: ea5cae8f
// ── END AI-METHOD ──
/**
 * One-time migration: if the new global key is empty but the old per-connection
 * key has data, merge it forward and clean up the legacy keys.
 */
function migrateLegacyStorage(): void {
  if (typeof window === 'undefined') return;
  try {
    // Only migrate if the new key doesn't exist yet
    if (window.localStorage.getItem(PLUGINS_STORAGE_KEY) !== null) return;

    const seen = new Map<string, InstalledPluginRecord>();
    const keysToRemove: string[] = [];

    for (let i = 0; i < window.localStorage.length; i++) {
      const key = window.localStorage.key(i);
      if (!key?.startsWith(LEGACY_KEY_PREFIX)) continue;

      keysToRemove.push(key);
      try {
        const raw = window.localStorage.getItem(key);
        if (!raw) continue;
        const arr = JSON.parse(raw);
        if (!Array.isArray(arr)) continue;
        for (const rec of arr as InstalledPluginRecord[]) {
          if (rec?.id && !seen.has(rec.id)) seen.set(rec.id, rec);
        }
      } catch {
        // ignore malformed entry
      }
    }

    if (seen.size > 0) {
      window.localStorage.setItem(PLUGINS_STORAGE_KEY, JSON.stringify([...seen.values()]));
    }

    for (const key of keysToRemove) {
      window.localStorage.removeItem(key);
    }
  } catch {
    // ignore storage errors
  }
}

migrateLegacyStorage();

/**
 * One-time (idempotent) migration for plugins that were merged into a single
 * successor id. voice-dictation-engine + voice-dictation-input -> voice-dictation
 * (2026-07-21): the two configs are combined into the successor's userConfig
 * (successor wins on key collision — there are none today), enabled if either
 * source was enabled, and the old records are removed either way so stale
 * ids don't linger in the installed list once they're gone from the registry.
 */
function migratePluginMerges(): void {
  if (typeof window === 'undefined') return;
  try {
    const current = loadFromStorage();
    const merges: Array<{ into: PluginId; from: PluginId[] }> = [
      { into: 'voice-dictation', from: ['voice-dictation-engine', 'voice-dictation-input'] },
    ];

    let changed = false;

    for (const merge of merges) {
      const sources = current.filter((p) => merge.from.includes(p.id));
      if (sources.length === 0) continue;

      const existingIndex = current.findIndex((p) => p.id === merge.into);
      if (existingIndex === -1) {
        const core = findCorePlugin(merge.into);
        const mergedConfig = sources.reduce<Record<string, unknown>>((acc, s) => ({ ...acc, ...s.userConfig }), {});
        current.push({
          id: merge.into,
          name: core?.manifest.name ?? merge.into,
          version: core?.manifest.version ?? '0.1.0',
          author: core?.manifest.author,
          description: core?.manifest.description,
          enabled: sources.some((s) => s.enabled),
          installedAt: Math.min(...sources.map((s) => s.installedAt)),
          userConfig: mergedConfig,
          kind: sources[0].kind,
        });
      }

      for (const src of sources) {
        const idx = current.findIndex((p) => p.id === src.id);
        if (idx !== -1) current.splice(idx, 1);
      }
      changed = true;
    }

    if (changed) saveToStorage(current);
  } catch {
    // ignore storage errors
  }
}

migratePluginMerges();

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: loadFromStorage — Loads plugin records from browser storage or returns empty array if unavailable.
// @ai-hash: a129d4c0
// ── END AI-METHOD ──
function loadFromStorage(): InstalledPluginRecord[] {
  if (typeof window === 'undefined') return [];

  try {
    const raw = window.localStorage.getItem(PLUGINS_STORAGE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? (parsed as InstalledPluginRecord[]) : [];
  } catch {
    return [];
  }
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: saveToStorage — Saves plugin records to browser's local storage when available.
// @ai-hash: 2bb38fc4
// ── END AI-METHOD ──
function saveToStorage(items: InstalledPluginRecord[]) {
  if (typeof window === 'undefined') return;
  try {
    window.localStorage.setItem(PLUGINS_STORAGE_KEY, JSON.stringify(items));
  } catch {
    // ignore
  }
}

/* -------------------------------------------
   Hook
-------------------------------------------- */

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: usePlugins — Manages global plugin installation, enabling, disabling, and configuration with persistent storage.
// @ai-hash: 7f935b5c
// ── END AI-METHOD ──
export function usePlugins(_connectionId?: string | null) {
  // Plugins are global (not per-connection) so they persist correctly across restarts.
  // _connectionId is kept in the signature for call-site compatibility but not used for storage.
  const [plugins, setPlugins] = useState<InstalledPluginRecord[]>(() => loadFromStorage());

  // Persist immediately with the computed "next" value (no effect-race)
  const setPluginsPersist = useCallback((updater: (prev: InstalledPluginRecord[]) => InstalledPluginRecord[]) => {
    setPlugins((prev) => {
      const next = updater(prev);
      saveToStorage(next);
      return next;
    });
  }, []);

  /* -------------------------------------------
     Derived
  -------------------------------------------- */

  // aliases your UI may expect
  const installed = plugins;

  const byId = useMemo(() => {
    const map = new Map<string, InstalledPluginRecord>();
    for (const p of plugins) map.set(p.id, p);
    return map;
  }, [plugins]);

  const getInstallRecord = useCallback((id: PluginId) => byId.get(id) ?? null, [byId]);
  const getPlugin = useCallback((id: PluginId) => byId.get(id) ?? null, [byId]);

  const isInstalled = useCallback((id: PluginId) => byId.has(id), [byId]);

  const isEnabled = useCallback(
    (id: PluginId) => {
      const rec = byId.get(id);
      return !!rec?.enabled;
    },
    [byId],
  );

  /* -------------------------------------------
     Actions
  -------------------------------------------- */

  /**
   * Install core plugin by id (from registry).
   * Safe to call multiple times.
   */
  const installCorePlugin = useCallback(
    (id: PluginId) => {
      const core = findCorePlugin(id);
      if (!core) return;

      setPluginsPersist((prev) => {
        if (prev.some((p) => p.id === id)) return prev;

        const rec: InstalledPluginRecord = {
          id: core.id,
          name: core.manifest.name,
          version: core.manifest.version,
          author: core.manifest.author,
          description: core.manifest.description,
          enabled: false,
          installedAt: Date.now(),
          userConfig: {},
          kind: 'unknown-plugin-kind',
        };

        return [...prev, rec];
      });
    },
    [setPluginsPersist],
  );

  const uninstallPlugin = useCallback(
    (id: PluginId) => {
      setPluginsPersist((prev) => prev.filter((p) => p.id !== id));
    },
    [setPluginsPersist],
  );

  // compatibility name some UI used
  const removePlugin = uninstallPlugin;

  const enablePlugin = useCallback(
    (id: PluginId) => {
      setPluginsPersist((prev) => prev.map((p) => (p.id === id ? { ...p, enabled: true } : p)));
    },
    [setPluginsPersist],
  );

  const disablePlugin = useCallback(
    (id: PluginId) => {
      setPluginsPersist((prev) => prev.map((p) => (p.id === id ? { ...p, enabled: false } : p)));
    },
    [setPluginsPersist],
  );

  // compatibility name some UI used
  const setPluginEnabled = useCallback(
    (id: PluginId, enabled: boolean) => {
      if (enabled) enablePlugin(id);
      else disablePlugin(id);
    },
    [enablePlugin, disablePlugin],
  );

  /**
   * Persist FULL userConfig object (what your modal "Save" is doing).
   * This avoids merge bugs where old keys stick around.
   */
  const updatePluginConfig = useCallback(
    (id: PluginId, nextUserConfig: Record<string, unknown>) => {
      setPluginsPersist((prev) =>
        prev.map((p) =>
          p.id === id
            ? {
                ...p,
                userConfig: { ...nextUserConfig },
              }
            : p,
        ),
      );
    },
    [setPluginsPersist],
  );

  return {
    // base
    plugins,

    // selectors
    installed,
    getPlugin,
    getInstallRecord,
    isInstalled,
    isEnabled,

    // actions
    installCorePlugin,
    uninstallPlugin,
    removePlugin,
    enablePlugin,
    disablePlugin,
    setPluginEnabled,
    updatePluginConfig,
  };
}

export default usePlugins;
