// apps/game-client/src/hooks/useRightPaneHud.ts
import { useEffect, useRef, useState } from 'react';
import { ListenEvent } from '../features/event-emitter/event-dispatcher';

/** Re-export so existing imports keep working */
export { useTickTimer } from './useTickTimer';

/** Directions supported by the compass. */
export type CompassDirection = 'N' | 'S' | 'E' | 'W' | 'NE' | 'NW' | 'SE' | 'SW' | 'U' | 'D';

export interface VitalsState {
  hp: number;
  hpMax: number;
  mp: number;
  mpMax: number;
  stamina: number;
  staminaMax: number;
}

export interface EnemyHudState {
  visible: boolean;
  label: string;
  pct: number; // 0–100
  statusText?: string;
}

export interface AffectEntry {
  id: string; // stable key (e.g. from GMCP, or hash of name+location)
  name: string;
  summary?: string;
}

/** Compass exits state. */
export interface CompassState {
  exits: Set<CompassDirection>;
}

type AnyRecord = Record<string, unknown>;

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: isRecord — Checks if a value is a non-null object record.
// @ai-hash: cd774a12
// ── END AI-METHOD ──
function isRecord(v: unknown): v is AnyRecord {
  return typeof v === 'object' && v !== null;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: toNum — Converts input to number, returning undefined for non-finite values.
// @ai-hash: 6429646b
// ── END AI-METHOD ──
function toNum(x: unknown): number | undefined {
  const n = Number(x);
  return Number.isFinite(n) ? n : undefined;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: applyVitalsPatch — Updates vitals state with new values while preserving existing ones.
// @ai-hash: 29257278
// ── END AI-METHOD ──
function applyVitalsPatch(prev: VitalsState, detail: unknown): VitalsState {
  // Supports:
  // - legacy: { hp, hpMax, mp, mpMax, stamina, staminaMax }
  // - GMCP char_data: { hp, max_hp, mana, max_mana, move, max_move }
  const d = isRecord(detail) ? detail : {};

  const hp = toNum(d.hp);
  const hpMax = toNum(d.hpMax ?? d.max_hp);

  const mp = toNum(d.mp ?? d.mana);
  const mpMax = toNum(d.mpMax ?? d.max_mana);

  const stamina = toNum(d.stamina ?? d.mv ?? d.move);
  const staminaMax = toNum(d.staminaMax ?? d.mvMax ?? d.max_move);

  return {
    hp: hp ?? prev.hp,
    hpMax: hpMax ?? prev.hpMax,
    mp: mp ?? prev.mp,
    mpMax: mpMax ?? prev.mpMax,
    stamina: stamina ?? prev.stamina,
    staminaMax: staminaMax ?? prev.staminaMax,
  };
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: makeInstanceKey — Generates a unique instance key with prefix and random suffix.
// @ai-hash: 0d248ab6
// ── END AI-METHOD ──
function makeInstanceKey(prefix: string): string {
  // stable-enough randomness for per-mount uniqueness
  return `${prefix}::${Math.random().toString(16).slice(2)}`;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: useVitalsState — Manages and updates character vitals state from game events.
// @ai-hash: 7b2d3c6d
// ── END AI-METHOD ──
/**
 * Player vitals from GMCP.
 *
 * Source of truth:
 *  - "game:char-data"
 *
 * IMPORTANT:
 * Multiple components can mount this hook (RightSidebar + FocusBar).
 * Listener keys MUST be unique per instance, otherwise one will clobber the other.
 */
export function useVitalsState(): VitalsState {
  const [vitals, setVitals] = useState<VitalsState>({
    hp: 0,
    hpMax: 0,
    mp: 0,
    mpMax: 0,
    stamina: 0,
    staminaMax: 0,
  });

  const keyRef = useRef<string>(makeInstanceKey('useVitalsState::game:char-data'));

  useEffect(() => {
    const disposeChar = ListenEvent<any>(
      'game:char-data',
      (payload) => {
        setVitals((prev) => applyVitalsPatch(prev, payload));
      },
      { key: keyRef.current },
    );

    return () => {
      try {
        disposeChar?.();
      } catch {
        // ignore
      }
    };
  }, []);

  return vitals;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: useEnemyHudState — Updates and returns enemy HUD state based on enemy health events.
// @ai-hash: 6929cea7
// ── END AI-METHOD ──
/**
 * Enemy HUD state.
 */
export function useEnemyHudState(): EnemyHudState {
  const [state, setState] = useState<EnemyHudState>({
    visible: false,
    label: '',
    pct: 0,
    statusText: '',
  });

  const keyRef = useRef<string>(makeInstanceKey('useEnemyHudState::event:fighting:opponent'));
  const lastSeenRef = useRef<number>(0);

  // Enemy condition is dispatched as 'event:fighting:opponent' (OpponentStatusDetail:
  // { pct, label, statusText, ts, ... }) by the combat opponent probe. This was
  // previously wired to a phantom 'event:enemy-hp' that nothing emits.
  useEffect(() => {
    const STALE_MS = 10000; // no opponent line for this long → hide the enemy HUD

    const dispose = ListenEvent<any>(
      'event:fighting:opponent',
      (payload) => {
        const d = isRecord(payload) ? payload : {};

        const pctRaw = toNum(d.pct);
        if (pctRaw === undefined) return; // ignore lines without a usable pct
        const pct = Math.max(0, Math.min(100, pctRaw));

        const label = typeof d.label === 'string' ? d.label.trim() : '';
        const statusText = typeof d.statusText === 'string' ? d.statusText : undefined;

        lastSeenRef.current = Date.now();

        setState((prev) => ({
          visible: true,
          label: label || prev.label || 'Enemy',
          pct,
          statusText: statusText ?? prev.statusText,
        }));
      },
      { key: keyRef.current },
    );

    // Staleness sweep: combat ended (no opponent line) → hide.
    const ticker = window.setInterval(() => {
      if (lastSeenRef.current === 0) return;
      if (Date.now() - lastSeenRef.current >= STALE_MS) {
        setState((prev) => (prev.visible ? { ...prev, visible: false } : prev));
      }
    }, 1000);

    return () => {
      try {
        dispose?.();
      } catch {
        // ignore
      }
      window.clearInterval(ticker);
    };
  }, []);

  return state;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: useAffectsState — Manages and synchronizes game affect entries from external events.
// @ai-hash: 79d815da
// ── END AI-METHOD ──
/**
 * Affects state.
 *
 * Sourced from GMCP, dispatched by the script runtime:
 *   game:affects-trueup – full replace: { affects: [{ n, d, m, lc, t }] }
 *   game:affect-added   – add/update:   { n, d, m, lc, t }  (or { affect: {...} })
 *   game:affect-removed – remove:       { n }               (by affect name)
 *
 * GMCP affects use short keys (n = name; d/m/lc/t = duration/modifier/location/type)
 * and carry no server id, so entries are keyed by lower-cased name.
 */
export function useAffectsState(): AffectEntry[] {
  const [affects, setAffects] = useState<AffectEntry[]>([]);

  const trueupKeyRef = useRef<string>(makeInstanceKey('useAffectsState::game:affects-trueup'));
  const addKeyRef = useRef<string>(makeInstanceKey('useAffectsState::game:affect-added'));
  const remKeyRef = useRef<string>(makeInstanceKey('useAffectsState::game:affect-removed'));

  useEffect(() => {
    // Map a GMCP affect object → AffectEntry. Accepts the affect directly or wrapped
    // in { affect: {...} }. Name comes from `n` (fallback `name`); id is the lc name.
    const toEntry = (raw: unknown): AffectEntry | null => {
      const outer = isRecord(raw) ? raw : {};
      const src = isRecord((outer as any).affect) ? ((outer as any).affect as AnyRecord) : outer;
      const name = String((src as any).n ?? (src as any).name ?? '').trim();
      if (!name) return null;
      return { id: name.toLowerCase(), name };
    };

    const disposeSync = ListenEvent<any>(
      'game:affects-trueup',
      (payload) => {
        const d = isRecord(payload) ? payload : {};
        const raw = (d as any).affects;

        const byId = new Map<string, AffectEntry>();
        if (Array.isArray(raw)) {
          for (const item of raw) {
            const a = toEntry(item);
            if (a) byId.set(a.id, a); // de-dupe by name (keep last)
          }
        }

        setAffects(Array.from(byId.values()));
      },
      { key: trueupKeyRef.current },
    );

    const disposeAdd = ListenEvent<any>(
      'game:affect-added',
      (payload) => {
        const a = toEntry(payload);
        if (!a) return;

        setAffects((prev) => {
          const idx = prev.findIndex((x) => x.id === a.id);
          if (idx === -1) return [...prev, a];
          const next = [...prev];
          next[idx] = a;
          return next;
        });
      },
      { key: addKeyRef.current },
    );

    const disposeRemove = ListenEvent<any>(
      'game:affect-removed',
      (payload) => {
        const d = isRecord(payload) ? payload : {};
        const name = String((d as any).n ?? (d as any).name ?? '')
          .trim()
          .toLowerCase();
        if (!name) return;

        setAffects((prev) => prev.filter((a) => a.id !== name));
      },
      { key: remKeyRef.current },
    );

    return () => {
      try {
        disposeSync?.();
      } catch {}
      try {
        disposeAdd?.();
      } catch {}
      try {
        disposeRemove?.();
      } catch {}
    };
  }, []);

  return affects;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: useCompassState — Manages compass direction exits state by listening to room exit events and updating available directions.
// @ai-hash: 9bebfdee
// ── END AI-METHOD ──
/**
 * Compass exits.
 *
 * Expect:
 *   DispatchEvent('dsl:room-exits', { exits: ["N","E","S","D"] }));
 */
export function useCompassState(): CompassState {
  const [exits, setExits] = useState<Set<CompassDirection>>(new Set());

  const keyRef = useRef<string>(makeInstanceKey('useCompassState::dsl:room-exits'));

  useEffect(() => {
    const dispose = ListenEvent<any>(
      'dsl:room-exits',
      (payload) => {
        const d = isRecord(payload) ? payload : {};
        const raw = (d as any).exits;

        if (!Array.isArray(raw)) {
          setExits(new Set());
          return;
        }

        const next = new Set<CompassDirection>();
        for (const dir of raw) {
          const up = String(dir).toUpperCase();
          if (
            up === 'N' ||
            up === 'S' ||
            up === 'E' ||
            up === 'W' ||
            up === 'NE' ||
            up === 'NW' ||
            up === 'SE' ||
            up === 'SW' ||
            up === 'U' ||
            up === 'D'
          ) {
            next.add(up as CompassDirection);
          }
        }

        setExits(next);
      },
      { key: keyRef.current },
    );

    return () => {
      try {
        dispose?.();
      } catch {
        // ignore
      }
    };
  }, []);

  return { exits };
}
