// apps/game-client/src/hooks/useRightSidebar.ts
import { useState } from 'react';
import { useCharData } from './useCharData';

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: useRightSidebarViewModel — Manages right sidebar visibility state and provides toggle functionality for ancillary bar.
// @ai-hash: 8f9df7bf
// ── END AI-METHOD ──
export function useRightSidebarViewModel() {
  const { ancillary } = useCharData();
  const [showAncillaryBar, setShowAncillaryBar] = useState(true);

  const toggleAncillaryBar = () => setShowAncillaryBar((prev) => !prev);

  return {
    ancillary,
    showAncillaryBar,
    toggleAncillaryBar,
  };
}
