// apps\game-client\src\hooks\useRoomHeader.ts
import { useEffect, useMemo, useState } from 'react';
import { ListenEvent } from '../features/event-emitter/event-dispatcher';
import { getRoomData, setRoomData } from '../features/room/roomDataStore';

type RoomDataPayload = {
  room?: string;
  sector?: string;
  exits?: string[];
};

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: useRoomHeader — Fetches and tracks room name, sector, and flags from game events.
// @ai-hash: 728aa1ed
// ── END AI-METHOD ──
export function useRoomHeader() {
  // Seed from roomDataStore (the same cache useCompassBlock already seeds
  // exits from) so a remount — a live theme switch, e.g. — doesn't blank
  // the room name/sector until the next game:room-data event.
  const [roomName, setRoomName] = useState(() => getRoomData()?.room ?? '');
  const [sector, setSector] = useState(() => getRoomData()?.sector ?? '');

  useEffect(() => {
    const dispose = ListenEvent<RoomDataPayload>(
      'game:room-data',
      (payload) => {
        const nextRoom = String(payload?.room ?? '');
        const nextSector = String(payload?.sector ?? '');

        setRoomName(nextRoom);
        setSector(nextSector);
        // Write independently rather than relying on useCompassBlock's own
        // listener to persist this same event — the two hooks aren't
        // guaranteed to be mounted together in every shell/widget layout.
        setRoomData(payload ?? {});
      },
      { key: 'useRoomHeader::game:room-data' },
    );

    return () => {
      try {
        dispose?.();
      } catch {
        // ignore
      }
    };
  }, []);

  const roomFlags = useMemo(() => {
    if (!sector) return '';
    return `(${sector})`;
  }, [sector]);

  return { roomName, sector, roomFlags };
}
