// apps\game-client\src\hooks\useTickTimer.ts
import { useTickData } from './useTickData';

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: useTickTimer — Returns the remaining time in seconds for a ticking timer animation.
// @ai-hash: 731cd016
// ── END AI-METHOD ──
/**
 * Convenience wrapper when you only care about the countdown number,
 * not the time-of-day string.
 */
export function useTickTimer(durationSec: number) {
  const { remaining } = useTickData(durationSec);
  return { remaining };
}
