import { useEffect, useRef, useState, useCallback } from 'react';
import { Terminal as XTerm } from '@xterm/xterm';
import { FitAddon } from '@xterm/addon-fit';

import { ShatteredArchiveTerminal } from '../features/terminal/shatteredArchiveTerminal';
import { registerListener, unregisterListener } from '../features/event-emitter/event-dispatcher';

type ScrollTarget = {
  el: HTMLDivElement;
  kind: 'viewport' | 'scrollable';
};

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: loadTerminalFonts — Loads and applies four VeraMono font variants asynchronously for terminal-style text rendering.
// @ai-hash: bccb63e5
// ── END AI-METHOD ──
async function loadTerminalFonts() {
  const fonts = [
    new FontFace('VeraMono', 'url(/fonts/VeraMono.ttf)', {
      style: 'normal',
      weight: '400',
    }),
    new FontFace('VeraMono', 'url(/fonts/VeraMono-Italic.ttf)', {
      style: 'italic',
      weight: '400',
    }),
    new FontFace('VeraMono', 'url(/fonts/VeraMono-Bold.ttf)', {
      style: 'normal',
      weight: '700',
    }),
    new FontFace('VeraMono', 'url(/fonts/VeraMono-Bold-Italic.ttf)', {
      style: 'italic',
      weight: '700',
    }),
  ];

  for (const font of fonts) {
    document.fonts.add(font);
    await font.load();
  }

  await document.fonts.load('18px "VeraMono"');
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: useTerminal — Initializes and manages a terminal instance with auto-scroll and resize functionality.
// @ai-hash: f9e12c15
// ── END AI-METHOD ──
export function useTerminal() {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const termRef = useRef<XTerm | null>(null);
  const fitRef = useRef<FitAddon | null>(null);

  const [showJump, setShowJump] = useState(false);
  const autoScrollRef = useRef(true);

  useEffect(() => {
    let disposed = false;
    let cleanup: (() => void) | undefined;

    const init = async () => {
      const isSmall = typeof window !== 'undefined' && window.innerWidth <= 768;

      await loadTerminalFonts();
      if (disposed) return;

      const term = new XTerm({
        convertEol: true,
        disableStdin: true,
        fontFamily:
          '"VeraMono",' +
          '"Cascadia Mono","Cascadia Code","JetBrains Mono",' +
          'ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,' +
          '"Liberation Mono","DejaVu Sans Mono",monospace',
        fontSize: 13,
        lineHeight: 1.2,
        letterSpacing: 0,
        cursorBlink: false,
        cursorInactiveStyle: 'none',
        scrollback: 5000,
        theme: {
          background: '#000000',
          foreground: '#e0e0e0',
        },
      });

      const fitAddon = new FitAddon();
      term.loadAddon(fitAddon);

      termRef.current = term;
      fitRef.current = fitAddon;

      const container = containerRef.current;
      if (!container) {
        term.dispose();
        return;
      }

      term.open(container);

      requestAnimationFrame(() => {
        try {
          fitAddon.fit();
        } catch {
          // ignore
        }
        try {
          term.refresh(0, term.rows - 1);
        } catch {
          // ignore
        }
      });

      const applyNoKeyboardToXtermTextarea = () => {
        const helper = container.querySelector('.xterm-helper-textarea') as HTMLTextAreaElement | null;
        if (!helper) return;

        helper.tabIndex = -1;
        helper.setAttribute('tabindex', '-1');
        helper.setAttribute('readonly', 'true');

        helper.setAttribute('inputmode', 'none');
        helper.setAttribute('autocomplete', 'off');
        helper.setAttribute('autocorrect', 'off');
        helper.setAttribute('autocapitalize', 'off');
        helper.setAttribute('spellcheck', 'false');
      };

      applyNoKeyboardToXtermTextarea();
      const helperTick = window.setTimeout(() => applyNoKeyboardToXtermTextarea(), 0);

      ShatteredArchiveTerminal.Instance.attach(term, fitAddon);

      const ro = new ResizeObserver(() => {
        try {
          fitAddon.fit();
        } catch {
          // ignore
        }
        try {
          term.refresh(0, term.rows - 1);
        } catch {
          // ignore
        }
      });

      ro.observe(container);
      if (container.parentElement) ro.observe(container.parentElement);

      const onWindowResize = () => {
        try {
          fitAddon.fit();
        } catch {
          // ignore
        }
        try {
          term.refresh(0, term.rows - 1);
        } catch {
          // ignore
        }
      };

      window.addEventListener('resize', onWindowResize);
      window.addEventListener('orientationchange', onWindowResize);

      const updateScrollState = () => {
        const t = termRef.current;
        if (!t) return;

        const buffer = t.buffer.active;
        const viewportY = buffer.viewportY;
        const baseY = buffer.baseY;
        const atBottom = viewportY >= baseY;

        if (atBottom) {
          autoScrollRef.current = true;
          setShowJump(false);
          try {
            ShatteredArchiveTerminal.Instance.setAutoScroll(true);
          } catch {
            // ignore
          }
        } else {
          autoScrollRef.current = false;
          setShowJump(true);
          try {
            ShatteredArchiveTerminal.Instance.setAutoScroll(false);
          } catch {
            // ignore
          }
        }
      };

      term.onScroll(() => updateScrollState());
      updateScrollState();

      cleanup = () => {
        window.removeEventListener('resize', onWindowResize);
        window.removeEventListener('orientationchange', onWindowResize);

        try {
          ro.disconnect();
        } catch {}

        window.clearTimeout(helperTick);

        try {
          ShatteredArchiveTerminal.Instance.detach();
        } catch {
          // ignore
        }

        term.dispose();
        termRef.current = null;
        fitRef.current = null;
      };
    };

    void init();

    return () => {
      disposed = true;
      cleanup?.();
    };
  }, []);

  const handleJumpToLive = useCallback(() => {
    const term = termRef.current;
    if (!term) return;

    try {
      term.scrollToBottom();
      autoScrollRef.current = true;
      setShowJump(false);

      try {
        ShatteredArchiveTerminal.Instance.setAutoScroll(true);
      } catch {
        // ignore
      }
    } catch {
      // ignore
    }
  }, []);

  return {
    containerRef,
    showJump,
    handleJumpToLive,
  };
}
