// apps/game-client/src/hooks/useUserVariables.ts
import { useEffect, useState, useCallback } from 'react';
import {
  getUserVariablesSnapshot,
  setNamedVariable,
  deleteNamedVariable,
} from '../features/userScripts/userVariablesStore';
import { ListenEvent } from '../features/event-emitter/event-dispatcher';

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: useUserVariables — Manages user variables with real-time updates and provides methods to set or remove variables.
// @ai-hash: d5c2ab33
// ── END AI-METHOD ──
export function useUserVariables(connectionId?: string | null) {
  const [vars, setVars] = useState(() => getUserVariablesSnapshot(connectionId));

  useEffect(() => {
    setVars(getUserVariablesSnapshot(connectionId));
  }, [connectionId]);

  useEffect(() => {
    const dispose = ListenEvent<{ connectionId?: string }>(
      'shatteredarchive:userVariables-updated',
      (payload) => {
        const evConn = payload?.connectionId ?? 'default';
        const curConn = connectionId ?? 'default';
        if (evConn !== curConn) return;

        setVars(getUserVariablesSnapshot(connectionId));
      },
      { key: 'useUserVariables::window::userVariables-updated' },
    );

    return () => {
      try {
        dispose?.();
      } catch {
        // ignore
      }
    };
  }, [connectionId]);

  const setVar = useCallback(
    (name: string, value: string) => {
      setNamedVariable(connectionId, name, value);
      setVars(getUserVariablesSnapshot(connectionId));
    },
    [connectionId],
  );

  const removeVar = useCallback(
    (name: string) => {
      deleteNamedVariable(connectionId, name);
      setVars(getUserVariablesSnapshot(connectionId));
    },
    [connectionId],
  );

  return { vars, setVar, removeVar };
}
