import type { Action, MatchState, Side } from '../model/index.js';

/**
 * The `/ws/kt` wire contract, shared by the Kingdom Tactics client and server so the two
 * cannot drift. It lives in the engine because the engine is the isomorphic package both
 * apps already depend on. `MatchState` is a serializable readonly value, so a snapshot IS
 * the state — no custom codec in v1 (see Phase-4 plan, decision 1). Bump `KT_PROTOCOL_VERSION`
 * on any breaking change to these shapes.
 */
export const KT_PROTOCOL_VERSION = 1 as const;

// ─────────────────────────────────────────────────────────────────────────────
// Client → server
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Join (or create) a match and claim a seat. `side` omitted = server assigns.
 * `token` (Phase F) is an optional hub bearer token — the server introspects
 * it to attach an accountId to the claimed seat for history/persistence.
 * Additive only: omitting it is identical to today's fully anonymous join,
 * and an invalid/expired token degrades to anonymous rather than rejecting
 * the join.
 */
export interface KtJoinMessage {
  readonly type: 'join';
  readonly matchId: string;
  readonly side?: Side;
  readonly token?: string;
}

/** Submit an intent; the server validates seat ownership + engine legality. */
export interface KtActionMessage {
  readonly type: 'action';
  readonly matchId: string;
  readonly action: Action;
}

/** Ask the server to re-send the current snapshot. */
export interface KtRequestSnapshotMessage {
  readonly type: 'requestSnapshot';
  readonly matchId: string;
}

/** Release the seat / leave the match. */
export interface KtLeaveMessage {
  readonly type: 'leave';
  readonly matchId: string;
}

export type KtClientMessage =
  | KtJoinMessage
  | KtActionMessage
  | KtRequestSnapshotMessage
  | KtLeaveMessage;

// ─────────────────────────────────────────────────────────────────────────────
// Server → client
// ─────────────────────────────────────────────────────────────────────────────

/** Confirms a join: the seat granted + the current state + the protocol version. */
export interface KtJoinedMessage {
  readonly type: 'joined';
  readonly matchId: string;
  readonly side: Side;
  readonly state: MatchState;
  readonly protocol: number;
}

/** A new authoritative snapshot after an applied action (v1: full state, not a delta). */
export interface KtSnapshotMessage {
  readonly type: 'snapshot';
  readonly matchId: string;
  readonly state: MatchState;
  readonly lastAction?: Action;
}

/** A rejected message / illegal action / protocol error. */
export interface KtErrorMessage {
  readonly type: 'error';
  readonly matchId?: string;
  readonly message: string;
}

/** The match is decided; carries the final state + winner. */
export interface KtOverMessage {
  readonly type: 'over';
  readonly matchId: string;
  readonly state: MatchState;
  readonly winner: Side | 'draw';
}

export type KtServerMessage =
  | KtJoinedMessage
  | KtSnapshotMessage
  | KtErrorMessage
  | KtOverMessage;

// ─────────────────────────────────────────────────────────────────────────────
// Parsing / validation (client input is UNTRUSTED — validate defensively)
// ─────────────────────────────────────────────────────────────────────────────

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: isRecord — (no summary)
// @ai-hash: 82ad6c94
// ── END AI-METHOD ──
function isRecord(x: unknown): x is Record<string, unknown> {
  return typeof x === 'object' && x !== null;
}

const ACTION_TYPES = new Set(['move', 'attack', 'ability', 'set-stance', 'end-turn']);

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: looksLikeAction — (no summary)
// @ai-hash: 9e957099
// ── END AI-METHOD ──
/** Shallow structural check that `action` looks like an engine Action (the reducer does
 * the deep legality check). */
function looksLikeAction(x: unknown): x is Action {
  return isRecord(x) && typeof x.type === 'string' && ACTION_TYPES.has(x.type);
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: isKtClientMessage — (no summary)
// @ai-hash: 141531e5
// ── END AI-METHOD ──
/** Type guard for a well-formed client message. Rejects anything with a missing/unknown
 * `type` or missing required fields — safe to run on raw socket input. */
export function isKtClientMessage(x: unknown): x is KtClientMessage {
  if (!isRecord(x) || typeof x.type !== 'string') return false;
  switch (x.type) {
    case 'join':
      return (
        typeof x.matchId === 'string' &&
        (x.side === undefined || typeof x.side === 'number') &&
        (x.token === undefined || typeof x.token === 'string')
      );
    case 'action':
      return typeof x.matchId === 'string' && looksLikeAction(x.action);
    case 'requestSnapshot':
    case 'leave':
      return typeof x.matchId === 'string';
    default:
      return false;
  }
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: parseKtClientMessage — (no summary)
// @ai-hash: c1547fd0
// ── END AI-METHOD ──
/** Parse a raw socket frame into a validated `KtClientMessage`, or `null` if the JSON is
 * malformed or the shape is invalid. Never throws. */
export function parseKtClientMessage(raw: string): KtClientMessage | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  return isKtClientMessage(parsed) ? parsed : null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Parsing / validation (server → client; the client treats server frames defensively too)
// ─────────────────────────────────────────────────────────────────────────────

/** Shallow structural check that `state` looks like a serialized `MatchState`. The reducer /
 * renderer do the real work; here we only guard against obviously-wrong frames. */
function looksLikeState(x: unknown): x is MatchState {
  return isRecord(x) && typeof (x as { activeSide?: unknown }).activeSide === 'number';
}

/** A winner is a seat index or the literal `'draw'`. */
function looksLikeWinner(x: unknown): x is Side | 'draw' {
  return typeof x === 'number' || x === 'draw';
}

/** Type guard for a well-formed server message. Mirrors {@link isKtClientMessage}: rejects a
 * missing/unknown `type` or any variant missing its required fields. Safe on raw socket input. */
export function isKtServerMessage(x: unknown): x is KtServerMessage {
  if (!isRecord(x) || typeof x.type !== 'string') return false;
  switch (x.type) {
    case 'joined':
      return (
        typeof x.matchId === 'string' &&
        typeof x.side === 'number' &&
        looksLikeState(x.state) &&
        typeof x.protocol === 'number'
      );
    case 'snapshot':
      return (
        typeof x.matchId === 'string' &&
        looksLikeState(x.state) &&
        (x.lastAction === undefined || looksLikeAction(x.lastAction))
      );
    case 'error':
      return typeof x.message === 'string' && (x.matchId === undefined || typeof x.matchId === 'string');
    case 'over':
      return typeof x.matchId === 'string' && looksLikeState(x.state) && looksLikeWinner(x.winner);
    default:
      return false;
  }
}

/** Parse a raw socket frame into a validated `KtServerMessage`, or `null` if the JSON is
 * malformed or the shape is invalid. Never throws. Symmetric to {@link parseKtClientMessage}. */
export function parseKtServerMessage(raw: string): KtServerMessage | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  return isKtServerMessage(parsed) ? parsed : null;
}
