import type { Side } from '../model/index.js';
import type { MatchConfig } from './match-simulator.js';
import { runMatch } from './match-simulator.js';
import type { MatchResult } from './types.js';

/** N seeded matches of one match-up, aggregated — the balance-tuning workhorse. */
export interface BatchConfig extends Omit<MatchConfig, 'seed'> {
  /** First seed; match i uses seed + i (deterministic, reproducible). */
  readonly baseSeed: number;
  readonly matches: number;
}

export interface BatchResult {
  readonly matches: number;
  readonly winsBySide: Readonly<Record<number, number>>;
  readonly draws: number;
  readonly turnLimitHits: number;
  readonly avgTurns: number;
  readonly results: readonly MatchResult[];
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: runBatch — (no summary)
// @ai-hash: 26573a19
// ── END AI-METHOD ──
export function runBatch(cfg: BatchConfig): BatchResult {
  const results: MatchResult[] = [];
  const winsBySide: Record<number, number> = {};
  let draws = 0;
  let turnLimitHits = 0;
  let turnSum = 0;

  for (let i = 0; i < cfg.matches; i++) {
    const r = runMatch({ ...cfg, seed: cfg.baseSeed + i });
    results.push(r);
    turnSum += r.turns;
    if (r.reason === 'turn-limit') turnLimitHits++;
    if (r.winner === 'draw') draws++;
    else winsBySide[r.winner as Side] = (winsBySide[r.winner as Side] ?? 0) + 1;
  }

  return {
    matches: cfg.matches,
    winsBySide,
    draws,
    turnLimitHits,
    avgTurns: cfg.matches > 0 ? turnSum / cfg.matches : 0,
    results,
  };
}
