import { createGameDataProvider, createGameModeProvider } from '../data/index.js';
import type { EngineProviders } from '../engine/game-engine.js';
import type { Action, Board, Coord, MatchState, Side, Tile, Unit } from '../model/index.js';
import type { IAiPolicy } from '../ai/policy.js';
import { RandomPolicy } from '../ai/random-policy.js';
import { GreedyPolicy } from '../ai/greedy-policy.js';
import { runMatch } from './match-simulator.js';
import { runBatch } from './batch-simulator.js';

const providers: EngineProviders = {
  data: createGameDataProvider(),
  modes: createGameModeProvider(),
};

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: board — (no summary)
// @ai-hash: dec4a33d
// ── END AI-METHOD ──
function board(w: number, h: number): Board {
  const tiles: Tile[][] = [];
  for (let y = 0; y < h; y++) {
    const row: Tile[] = [];
    for (let x = 0; x < w; x++) row.push({ terrain: 'Field', feature: null });
    tiles.push(row);
  }
  return { width: w, height: h, tiles };
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: unit — (no summary)
// @ai-hash: 3e98d98b
// ── END AI-METHOD ──
function unit(instanceId: string, templateId: string, pos: Coord, side: number, hp = 999): Unit {
  return { kind: 'unit', instanceId, templateId, side, pos, hp, statuses: [], hasMoved: false, hasActed: false };
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: makeState — (no summary)
// @ai-hash: 0a289700
// ── END AI-METHOD ──
function makeState(tokens: Unit[], w = 6, h = 6): MatchState {
  return {
    modeId: 'skirmish',
    board: board(w, h),
    armies: [],
    tokens,
    turn: 1,
    activeSide: 0,
    moon: { type: 'White', phase: 'HalfMoon' },
    rngState: 1,
    status: 'in-progress',
  };
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: duelState — (no summary)
// @ai-hash: 26736834
// ── END AI-METHOD ──
function duelState(): MatchState {
  return makeState([
    unit('a', 'Human:Warrior', { x: 1, y: 1 }, 0),
    unit('d', 'Human:Warrior', { x: 4, y: 4 }, 1),
  ]);
}

const noopPolicy: IAiPolicy = {
  name: 'noop',
  chooseAction: (_s, side: Side): Action => ({ type: 'end-turn', side }),
};

describe('runBatch', () => {
  it('runs exactly N matches and aggregates wins correctly', () => {
    const cfg = {
      initial: duelState(),
      policies: { 0: new RandomPolicy(), 1: new RandomPolicy() },
      providers,
      baseSeed: 42,
      matches: 10,
    };
    const result = runBatch(cfg);

    expect(result.matches).toBe(10);
    expect(result.results.length).toBe(10);

    const totalWins = Object.values(result.winsBySide).reduce((s, v) => s + v, 0);
    expect(totalWins + result.draws).toBe(10);
  });

  it('is deterministic: two calls with the same baseSeed give identical winsBySide', () => {
    const cfg = {
      initial: duelState(),
      policies: { 0: new GreedyPolicy(), 1: new GreedyPolicy() },
      providers,
      baseSeed: 7,
      matches: 5,
    };

    const r1 = runBatch(cfg);
    const r2 = runBatch(cfg);

    expect(r1.winsBySide).toEqual(r2.winsBySide);
    expect(r1.draws).toBe(r2.draws);
    expect(r1.avgTurns).toBe(r2.avgTurns);
  });

  it('zero matches returns zeroes', () => {
    const result = runBatch({
      initial: duelState(),
      policies: { 0: new RandomPolicy(), 1: new RandomPolicy() },
      providers,
      baseSeed: 1,
      matches: 0,
    });

    expect(result.matches).toBe(0);
    expect(result.results.length).toBe(0);
    expect(result.draws).toBe(0);
    expect(result.turnLimitHits).toBe(0);
    expect(result.avgTurns).toBe(0);
    expect(Object.keys(result.winsBySide).length).toBe(0);
  });

  it('the stronger side wins consistently across a batch', () => {
    const initial = makeState(
      [
        unit('a1', 'Human:Warrior', { x: 3, y: 3 }, 0),
        unit('a2', 'Human:Warrior', { x: 3, y: 4 }, 0),
        unit('d', 'Human:Warrior', { x: 4, y: 3 }, 1, 30),
      ],
      8,
      8,
    );

    const result = runBatch({
      initial,
      policies: { 0: new GreedyPolicy(), 1: new GreedyPolicy() },
      providers,
      baseSeed: 1,
      matches: 20,
    });

    expect(result.winsBySide[0] ?? 0).toBe(20);
    expect(result.draws).toBe(0);
    expect(result.turnLimitHits).toBe(0);
  });

  it('turn-limit hits are counted correctly', () => {
    const initial = makeState([
      unit('a', 'Human:Warrior', { x: 0, y: 0 }, 0),
      unit('d', 'Human:Warrior', { x: 5, y: 5 }, 1),
    ]);

    const result = runBatch({
      initial,
      policies: { 0: noopPolicy, 1: noopPolicy },
      providers,
      baseSeed: 1,
      matches: 5,
      maxTurns: 3,
    });

    expect(result.turnLimitHits).toBe(5);
    expect(result.draws).toBe(5);
  });
});
