import type { Action, MatchState, Side } from '../model/index.js';
import { createRng } from '../rng/index.js';
import { applyAction, type EngineProviders } from '../engine/game-engine.js';
import type { IAiPolicy } from '../ai/policy.js';
import type { MatchResult } from './types.js';

/** One seeded self-driving match: a policy per side, played to victory or a turn limit. */
export interface MatchConfig {
  readonly initial: MatchState;
  /** side index → the policy that controls it. A side with no policy simply ends its turns. */
  readonly policies: Readonly<Record<number, IAiPolicy>>;
  readonly providers: EngineProviders;
  readonly seed: number;
  /** Safety cap on the `turn` counter (default 200). */
  readonly maxTurns?: number;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: survivorsBySide — (no summary)
// @ai-hash: cf93b47e
// ── END AI-METHOD ──
/** Living tokens per side (side index → count). */
function survivorsBySide(state: MatchState): Record<number, number> {
  const out: Record<number, number> = {};
  for (const t of state.tokens) {
    const alive = t.kind === 'unit' ? t.hp > 0 : t.hpPool > 0;
    if (alive) out[t.side] = (out[t.side] ?? 0) + 1;
  }
  return out;
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: runMatch — (no summary)
// @ai-hash: e4e86a45
// ── END AI-METHOD ──
/**
 * Run a full headless match. Each iteration the active side's policy chooses ONE action,
 * which is applied through the deterministic reducer; the side keeps acting until it (or
 * a guard) ends its turn. Terminates when the reducer flags the match `decided` or the
 * `turn` counter passes `maxTurns`. Pure w.r.t. inputs — all randomness comes from a
 * `createRng(seed)` stream, so the same config always yields the same `MatchResult`.
 *
 * Two anti-stall guards keep a bad policy from looping forever: a per-turn action cap
 * (`MAX_ACTIONS_PER_TURN`) forces an end-turn, and an illegal/no-op action (reducer
 * returns the same state) is converted into an end-turn.
 */
export function runMatch(cfg: MatchConfig): MatchResult {
  const rng = createRng(cfg.seed);
  const maxTurns = cfg.maxTurns ?? 200;
  const MAX_ACTIONS_PER_TURN = 500;

  let state = cfg.initial;
  let actions = 0;

  // Per-turn action counter, reset whenever the (side, turn) segment changes.
  let segmentSide: Side = state.activeSide;
  let segmentTurn = state.turn;
  let actionsThisTurn = 0;

  while (state.status === 'in-progress' && state.turn <= maxTurns) {
    const side = state.activeSide;
    if (side !== segmentSide || state.turn !== segmentTurn) {
      segmentSide = side;
      segmentTurn = state.turn;
      actionsThisTurn = 0;
    }

    const policy = cfg.policies[side];
    const forceEnd = !policy || actionsThisTurn >= MAX_ACTIONS_PER_TURN;
    const action: Action = forceEnd
      ? { type: 'end-turn', side }
      : policy.chooseAction(state, side, cfg.providers, rng);

    const next = applyAction(state, action, rng, cfg.providers);

    if (next === state) {
      // No-op (illegal action, or a rejected end-turn we should never see): end the turn
      // to guarantee forward progress. If even that is a no-op, bail to avoid an infinite loop.
      if (action.type === 'end-turn') break;
      const ended = applyAction(state, { type: 'end-turn', side }, rng, cfg.providers);
      if (ended === state) break;
      state = ended;
      actions++;
      continue;
    }

    state = next;
    actions++;
    actionsThisTurn++;
  }

  const decided = state.status === 'decided';
  return {
    winner: decided ? (state.winner ?? 'draw') : 'draw',
    decided,
    turns: state.turn,
    actions,
    reason: decided ? 'victory' : 'turn-limit',
    survivors: survivorsBySide(state),
    seed: cfg.seed,
  };
}
