import { createGameDataProvider, createGameModeProvider } from '../data/index.js';
import type { Action, Board, Coord, MatchState, Side, Tile, Unit } from '../model/index.js';
import type { EngineProviders } from '../engine/game-engine.js';
import type { IAiPolicy } from '../ai/policy.js';
import { RandomPolicy } from '../ai/random-policy.js';
import { GreedyPolicy } from '../ai/greedy-policy.js';
import { runMatch, type MatchConfig } from './match-simulator.js';

const providers: EngineProviders = {
  data: createGameDataProvider(),
  modes: createGameModeProvider(),
};

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: board — (no summary)
// @ai-hash: dec4a33d
// ── END AI-METHOD ──
function board(w: number, h: number): Board {
  const tiles: Tile[][] = [];
  for (let y = 0; y < h; y++) {
    const row: Tile[] = [];
    for (let x = 0; x < w; x++) row.push({ terrain: 'Field', feature: null });
    tiles.push(row);
  }
  return { width: w, height: h, tiles };
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: unit — (no summary)
// @ai-hash: 3e98d98b
// ── END AI-METHOD ──
function unit(instanceId: string, templateId: string, pos: Coord, side: number, hp = 999): Unit {
  return { kind: 'unit', instanceId, templateId, side, pos, hp, statuses: [], hasMoved: false, hasActed: false };
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: state — (no summary)
// @ai-hash: 4f025f76
// ── END AI-METHOD ──
function state(tokens: Unit[], w = 6, h = 6): MatchState {
  return {
    modeId: 'skirmish',
    board: board(w, h),
    armies: [],
    tokens,
    turn: 1,
    activeSide: 0,
    moon: { type: 'White', phase: 'HalfMoon' },
    rngState: 1,
    status: 'in-progress',
  };
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: duelState — (no summary)
// @ai-hash: 1d93b382
// ── END AI-METHOD ──
/** A tiny 1v1 duel on a 6×6 — the shared setup reused by the batch simulator test. */
export function duelState(): MatchState {
  return state([
    unit('a', 'Human:Warrior', { x: 1, y: 1 }, 0),
    unit('d', 'Human:Warrior', { x: 4, y: 4 }, 1),
  ]);
}

/** Always ends the turn — used to exercise the turn-limit path deterministically. */
const noop: IAiPolicy = {
  name: 'noop',
  chooseAction: (_s, side: Side): Action => ({ type: 'end-turn', side }),
};

describe('runMatch', () => {
  it('is fully deterministic for a fixed seed (golden: two runs are identical)', () => {
    const cfg: MatchConfig = {
      initial: duelState(),
      policies: { 0: new RandomPolicy(), 1: new RandomPolicy() },
      providers,
      seed: 7,
    };
    const r1 = runMatch(cfg);
    const r2 = runMatch(cfg);
    expect(r2).toEqual(r1);
    expect(['victory', 'turn-limit']).toContain(r1.reason);
  });

  it('the stronger side (2 Greedy units vs 1 weak) wins', () => {
    const initial = state(
      [
        unit('a1', 'Human:Warrior', { x: 3, y: 3 }, 0),
        unit('a2', 'Human:Warrior', { x: 3, y: 4 }, 0),
        unit('d', 'Human:Warrior', { x: 4, y: 3 }, 1, 30),
      ],
      8,
      8,
    );
    const r = runMatch({
      initial,
      policies: { 0: new GreedyPolicy(), 1: new GreedyPolicy() },
      providers,
      seed: 1,
    });
    expect(r.decided).toBe(true);
    expect(r.winner).toBe(0);
    expect(r.reason).toBe('victory');
  });

  it('a board with no tokens is a draw', () => {
    const r = runMatch({
      initial: state([]),
      policies: { 0: new RandomPolicy(), 1: new RandomPolicy() },
      providers,
      seed: 3,
    });
    expect(r.winner).toBe('draw');
  });

  it('hitting the turn limit yields reason "turn-limit" and no decision', () => {
    const initial = state([
      unit('a', 'Human:Warrior', { x: 0, y: 0 }, 0),
      unit('d', 'Human:Warrior', { x: 5, y: 5 }, 1),
    ]);
    const r = runMatch({
      initial,
      policies: { 0: noop, 1: noop },
      providers,
      seed: 1,
      maxTurns: 3,
    });
    expect(r.reason).toBe('turn-limit');
    expect(r.decided).toBe(false);
    expect(r.winner).toBe('draw');
  });
});
