import { createGameDataProvider, createGameModeProvider } from '../data/index.js';
import type { Board, Coord, MatchState, Tile, Unit } from '../model/index.js';
import { createRng } from '../rng/index.js';
import type { EngineProviders } from '../engine/game-engine.js';
import { ScenarioSimulator } from './scenario-simulator.js';

const providers: EngineProviders = {
  data: createGameDataProvider(),
  modes: createGameModeProvider(),
};

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: board — (no summary)
// @ai-hash: dec4a33d
// ── END AI-METHOD ──
function board(w: number, h: number): Board {
  const tiles: Tile[][] = [];
  for (let y = 0; y < h; y++) {
    const row: Tile[] = [];
    for (let x = 0; x < w; x++) row.push({ terrain: 'Field', feature: null });
    tiles.push(row);
  }
  return { width: w, height: h, tiles };
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: unit — (no summary)
// @ai-hash: 6c5ff3d4
// ── END AI-METHOD ──
function unit(instanceId: string, templateId: string, pos: Coord, side: number): Unit {
  return { kind: 'unit', instanceId, templateId, side, pos, hp: 999, statuses: [], hasMoved: false, hasActed: false };
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: duelState — (no summary)
// @ai-hash: 15229db2
// ── END AI-METHOD ──
function duelState(): MatchState {
  return {
    modeId: 'skirmish',
    board: board(6, 6),
    armies: [],
    tokens: [unit('a', 'Human:Warrior', { x: 1, y: 1 }, 0), unit('d', 'Human:Warrior', { x: 4, y: 4 }, 1)],
    turn: 1,
    activeSide: 0,
    moon: { gameHour: 0, sky: { Black: 'HalfMoon', Red: 'HalfMoon', White: 'HalfMoon' } },
    rngState: 1,
    status: 'in-progress',
  };
}

describe('ScenarioSimulator', () => {
  it('applies a manual move then end-turn, recording history', () => {
    const sim = new ScenarioSimulator(duelState(), providers, createRng(1));
    sim.step({ type: 'move', tokenId: 'a', to: { x: 2, y: 1 } });
    const after = sim.step({ type: 'end-turn', side: 0 });

    const a = after.tokens.find((t) => t.instanceId === 'a') as Unit;
    expect(a.pos).toEqual({ x: 2, y: 1 });
    expect(a.hasMoved).toBe(true);
    expect(after.activeSide).toBe(1);
    expect(sim.history()).toHaveLength(2);
    expect(sim.isOver()).toBe(false);
  });

  it('leaves state unchanged on an illegal move (no throw)', () => {
    const sim = new ScenarioSimulator(duelState(), providers, createRng(1));
    const before = sim.getState();
    const after = sim.step({ type: 'move', tokenId: 'a', to: { x: 5, y: 5 } }); // out of range
    expect(after).toBe(before);
    expect(sim.getState()).toBe(before);
  });
});
