    {"test bolt",
     {10, 10, 10, 10},
     {1, 1, 1, 1},
     spell_test_bolt,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(0),
     20,
     12,
     "test bolt",
     "!Test Bolt!",
     ""},