/**
 * GENERATED from merc-mud/2.4/src/const.c skill_table — do not hand-edit.
 * Regenerate with `pnpm --filter @shatteredarchive/merc-area gen-skills-stock`
 * (scripts/gen-skills-stock.ts) after any const.c skill_table change, then
 * review the diff before committing.
 * Row 0 ("reserved", spell_fun 0) is excluded: it is not authorable.
 */

import type { StockSkillRow } from './skills.js';

/** Every spell function name appearing in the stock table (incl. spell_null for non-spell skills). */
export const SKILL_SPELL_FUNS: readonly string[] = [
  "spell_acid_blast",
  "spell_acid_breath",
  "spell_armor",
  "spell_bless",
  "spell_blindness",
  "spell_burning_hands",
  "spell_call_lightning",
  "spell_calm",
  "spell_cancellation",
  "spell_cause_critical",
  "spell_cause_light",
  "spell_cause_serious",
  "spell_chain_lightning",
  "spell_change_sex",
  "spell_charm_person",
  "spell_chill_touch",
  "spell_colour_spray",
  "spell_continual_light",
  "spell_control_weather",
  "spell_create_food",
  "spell_create_rose",
  "spell_create_spring",
  "spell_create_water",
  "spell_cure_blindness",
  "spell_cure_critical",
  "spell_cure_disease",
  "spell_cure_light",
  "spell_cure_poison",
  "spell_cure_serious",
  "spell_curse",
  "spell_demonfire",
  "spell_detect_evil",
  "spell_detect_good",
  "spell_detect_hidden",
  "spell_detect_invis",
  "spell_detect_magic",
  "spell_detect_poison",
  "spell_dispel_evil",
  "spell_dispel_good",
  "spell_dispel_magic",
  "spell_earthquake",
  "spell_enchant_armor",
  "spell_enchant_weapon",
  "spell_energy_drain",
  "spell_faerie_fire",
  "spell_faerie_fog",
  "spell_farsight",
  "spell_fire_breath",
  "spell_fireball",
  "spell_fireproof",
  "spell_flamestrike",
  "spell_floating_disc",
  "spell_fly",
  "spell_frenzy",
  "spell_frost_breath",
  "spell_gas_breath",
  "spell_gate",
  "spell_general_purpose",
  "spell_giant_strength",
  "spell_harm",
  "spell_haste",
  "spell_heal",
  "spell_heat_metal",
  "spell_high_explosive",
  "spell_holy_word",
  "spell_identify",
  "spell_infravision",
  "spell_invis",
  "spell_know_alignment",
  "spell_lightning_bolt",
  "spell_lightning_breath",
  "spell_locate_object",
  "spell_magic_missile",
  "spell_mass_healing",
  "spell_mass_invis",
  "spell_nexus",
  "spell_null",
  "spell_pass_door",
  "spell_plague",
  "spell_poison",
  "spell_portal",
  "spell_protection_evil",
  "spell_protection_good",
  "spell_ray_of_truth",
  "spell_recharge",
  "spell_refresh",
  "spell_remove_curse",
  "spell_sanctuary",
  "spell_shield",
  "spell_shocking_grasp",
  "spell_sleep",
  "spell_slow",
  "spell_spark_bolt",
  "spell_stone_skin",
  "spell_summon",
  "spell_teleport",
  "spell_ventriloquate",
  "spell_weaken",
  "spell_word_of_recall"
];

/** Every (spellFun, target) pair proven safe at compile time, as "fun target" keys. */
export const STOCK_FUN_TARGET_PAIRS: readonly string[] = [
  "spell_acid_blast 1",
  "spell_acid_breath 1",
  "spell_armor 2",
  "spell_bless 5",
  "spell_blindness 1",
  "spell_burning_hands 1",
  "spell_call_lightning 0",
  "spell_calm 0",
  "spell_cancellation 2",
  "spell_cause_critical 1",
  "spell_cause_light 1",
  "spell_cause_serious 1",
  "spell_chain_lightning 1",
  "spell_change_sex 2",
  "spell_charm_person 1",
  "spell_chill_touch 1",
  "spell_colour_spray 1",
  "spell_continual_light 0",
  "spell_control_weather 0",
  "spell_create_food 0",
  "spell_create_rose 0",
  "spell_create_spring 0",
  "spell_create_water 4",
  "spell_cure_blindness 2",
  "spell_cure_critical 2",
  "spell_cure_disease 2",
  "spell_cure_light 2",
  "spell_cure_poison 2",
  "spell_cure_serious 2",
  "spell_curse 6",
  "spell_demonfire 1",
  "spell_detect_evil 3",
  "spell_detect_good 3",
  "spell_detect_hidden 3",
  "spell_detect_invis 3",
  "spell_detect_magic 3",
  "spell_detect_poison 4",
  "spell_dispel_evil 1",
  "spell_dispel_good 1",
  "spell_dispel_magic 1",
  "spell_earthquake 0",
  "spell_enchant_armor 4",
  "spell_enchant_weapon 4",
  "spell_energy_drain 1",
  "spell_faerie_fire 1",
  "spell_faerie_fog 0",
  "spell_farsight 0",
  "spell_fire_breath 1",
  "spell_fireball 1",
  "spell_fireproof 4",
  "spell_flamestrike 1",
  "spell_floating_disc 0",
  "spell_fly 2",
  "spell_frenzy 2",
  "spell_frost_breath 1",
  "spell_gas_breath 0",
  "spell_gate 0",
  "spell_general_purpose 1",
  "spell_giant_strength 2",
  "spell_harm 1",
  "spell_haste 2",
  "spell_heal 2",
  "spell_heat_metal 1",
  "spell_high_explosive 1",
  "spell_holy_word 0",
  "spell_identify 4",
  "spell_infravision 2",
  "spell_invis 5",
  "spell_know_alignment 2",
  "spell_lightning_bolt 1",
  "spell_lightning_breath 1",
  "spell_locate_object 0",
  "spell_magic_missile 1",
  "spell_mass_healing 0",
  "spell_mass_invis 0",
  "spell_nexus 0",
  "spell_null 0",
  "spell_null 1",
  "spell_pass_door 3",
  "spell_plague 1",
  "spell_poison 6",
  "spell_portal 0",
  "spell_protection_evil 3",
  "spell_protection_good 3",
  "spell_ray_of_truth 1",
  "spell_recharge 4",
  "spell_refresh 2",
  "spell_remove_curse 5",
  "spell_sanctuary 2",
  "spell_shield 2",
  "spell_shocking_grasp 1",
  "spell_sleep 1",
  "spell_slow 1",
  "spell_spark_bolt 1",
  "spell_stone_skin 3",
  "spell_summon 0",
  "spell_teleport 3",
  "spell_ventriloquate 0",
  "spell_weaken 1",
  "spell_word_of_recall 3"
];

export const STOCK_SKILLS: readonly StockSkillRow[] = [
  { name: "acid blast", spellFun: "spell_acid_blast", target: 1, position: 7, levels: [28, 53, 35, 32], ratings: [1, 1, 2, 2], minMana: 20, beats: 12, nounDamage: "acid blast", msgOff: "!Acid Blast!", msgObj: null, slot: 70, hasGsn: false },
  { name: "armor", spellFun: "spell_armor", target: 2, position: 8, levels: [7, 2, 10, 5], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "You feel less armored.", msgObj: "", slot: 1, hasGsn: false },
  { name: "bless", spellFun: "spell_bless", target: 5, position: 8, levels: [53, 7, 53, 8], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "You feel less righteous.", msgObj: "$p's holy aura fades.", slot: 3, hasGsn: false },
  { name: "blindness", spellFun: "spell_blindness", target: 1, position: 7, levels: [12, 8, 17, 15], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "You can see again.", msgObj: "", slot: 4, hasGsn: true },
  { name: "burning hands", spellFun: "spell_burning_hands", target: 1, position: 7, levels: [7, 53, 10, 9], ratings: [1, 1, 2, 2], minMana: 15, beats: 12, nounDamage: "burning hands", msgOff: "!Burning Hands!", msgObj: "", slot: 5, hasGsn: false },
  { name: "call lightning", spellFun: "spell_call_lightning", target: 0, position: 7, levels: [26, 18, 31, 22], ratings: [1, 1, 2, 2], minMana: 15, beats: 12, nounDamage: "lightning bolt", msgOff: "!Call Lightning!", msgObj: "", slot: 6, hasGsn: false },
  { name: "calm", spellFun: "spell_calm", target: 0, position: 7, levels: [48, 16, 50, 20], ratings: [1, 1, 2, 2], minMana: 30, beats: 12, nounDamage: "", msgOff: "You have lost your peace of mind.", msgObj: "", slot: 509, hasGsn: false },
  { name: "cancellation", spellFun: "spell_cancellation", target: 2, position: 7, levels: [18, 26, 34, 34], ratings: [1, 1, 2, 2], minMana: 20, beats: 12, nounDamage: "!cancellation!", msgOff: "", msgObj: null, slot: 507, hasGsn: false },
  { name: "cause critical", spellFun: "spell_cause_critical", target: 1, position: 7, levels: [53, 13, 53, 19], ratings: [1, 1, 2, 2], minMana: 20, beats: 12, nounDamage: "spell", msgOff: "!Cause Critical!", msgObj: "", slot: 63, hasGsn: false },
  { name: "cause light", spellFun: "spell_cause_light", target: 1, position: 7, levels: [53, 1, 53, 3], ratings: [1, 1, 2, 2], minMana: 15, beats: 12, nounDamage: "spell", msgOff: "!Cause Light!", msgObj: "", slot: 62, hasGsn: false },
  { name: "cause serious", spellFun: "spell_cause_serious", target: 1, position: 7, levels: [53, 7, 53, 10], ratings: [1, 1, 2, 2], minMana: 17, beats: 12, nounDamage: "spell", msgOff: "!Cause Serious!", msgObj: "", slot: 64, hasGsn: false },
  { name: "chain lightning", spellFun: "spell_chain_lightning", target: 1, position: 7, levels: [33, 53, 39, 36], ratings: [1, 1, 2, 2], minMana: 25, beats: 12, nounDamage: "lightning", msgOff: "!Chain Lightning!", msgObj: "", slot: 500, hasGsn: false },
  { name: "change sex", spellFun: "spell_change_sex", target: 2, position: 7, levels: [53, 53, 53, 53], ratings: [1, 1, 2, 2], minMana: 15, beats: 12, nounDamage: "", msgOff: "Your body feels familiar again.", msgObj: "", slot: 82, hasGsn: false },
  { name: "charm person", spellFun: "spell_charm_person", target: 1, position: 8, levels: [20, 53, 25, 53], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "You feel more self-confident.", msgObj: "", slot: 7, hasGsn: true },
  { name: "chill touch", spellFun: "spell_chill_touch", target: 1, position: 7, levels: [4, 53, 6, 6], ratings: [1, 1, 2, 2], minMana: 15, beats: 12, nounDamage: "chilling touch", msgOff: "You feel less cold.", msgObj: "", slot: 8, hasGsn: false },
  { name: "colour spray", spellFun: "spell_colour_spray", target: 1, position: 7, levels: [16, 53, 22, 20], ratings: [1, 1, 2, 2], minMana: 15, beats: 12, nounDamage: "colour spray", msgOff: "!Colour Spray!", msgObj: "", slot: 10, hasGsn: false },
  { name: "continual light", spellFun: "spell_continual_light", target: 0, position: 8, levels: [6, 4, 6, 9], ratings: [1, 1, 2, 2], minMana: 7, beats: 12, nounDamage: "", msgOff: "!Continual Light!", msgObj: "", slot: 57, hasGsn: false },
  { name: "control weather", spellFun: "spell_control_weather", target: 0, position: 8, levels: [15, 19, 28, 22], ratings: [1, 1, 2, 2], minMana: 25, beats: 12, nounDamage: "", msgOff: "!Control Weather!", msgObj: "", slot: 11, hasGsn: false },
  { name: "create food", spellFun: "spell_create_food", target: 0, position: 8, levels: [10, 5, 11, 12], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "!Create Food!", msgObj: "", slot: 12, hasGsn: false },
  { name: "create rose", spellFun: "spell_create_rose", target: 0, position: 8, levels: [16, 11, 10, 24], ratings: [1, 1, 2, 2], minMana: 30, beats: 12, nounDamage: "", msgOff: "!Create Rose!", msgObj: "", slot: 511, hasGsn: false },
  { name: "create spring", spellFun: "spell_create_spring", target: 0, position: 8, levels: [14, 17, 23, 20], ratings: [1, 1, 2, 2], minMana: 20, beats: 12, nounDamage: "", msgOff: "!Create Spring!", msgObj: "", slot: 80, hasGsn: false },
  { name: "create water", spellFun: "spell_create_water", target: 4, position: 8, levels: [8, 3, 12, 11], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "!Create Water!", msgObj: "", slot: 13, hasGsn: false },
  { name: "cure blindness", spellFun: "spell_cure_blindness", target: 2, position: 7, levels: [53, 6, 53, 8], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "!Cure Blindness!", msgObj: "", slot: 14, hasGsn: false },
  { name: "cure critical", spellFun: "spell_cure_critical", target: 2, position: 7, levels: [53, 13, 53, 19], ratings: [1, 1, 2, 2], minMana: 20, beats: 12, nounDamage: "", msgOff: "!Cure Critical!", msgObj: "", slot: 15, hasGsn: false },
  { name: "cure disease", spellFun: "spell_cure_disease", target: 2, position: 8, levels: [53, 13, 53, 14], ratings: [1, 1, 2, 2], minMana: 20, beats: 12, nounDamage: "", msgOff: "!Cure Disease!", msgObj: "", slot: 501, hasGsn: false },
  { name: "cure light", spellFun: "spell_cure_light", target: 2, position: 7, levels: [53, 1, 53, 3], ratings: [1, 1, 2, 2], minMana: 10, beats: 12, nounDamage: "", msgOff: "!Cure Light!", msgObj: "", slot: 16, hasGsn: false },
  { name: "cure poison", spellFun: "spell_cure_poison", target: 2, position: 8, levels: [53, 14, 53, 16], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "!Cure Poison!", msgObj: "", slot: 43, hasGsn: false },
  { name: "cure serious", spellFun: "spell_cure_serious", target: 2, position: 7, levels: [53, 7, 53, 10], ratings: [1, 1, 2, 2], minMana: 15, beats: 12, nounDamage: "", msgOff: "!Cure Serious!", msgObj: "", slot: 61, hasGsn: false },
  { name: "curse", spellFun: "spell_curse", target: 6, position: 7, levels: [18, 18, 26, 22], ratings: [1, 1, 2, 2], minMana: 20, beats: 12, nounDamage: "curse", msgOff: "The curse wears off.", msgObj: "$p is no longer impure.", slot: 17, hasGsn: true },
  { name: "demonfire", spellFun: "spell_demonfire", target: 1, position: 7, levels: [53, 34, 53, 45], ratings: [1, 1, 2, 2], minMana: 20, beats: 12, nounDamage: "torments", msgOff: "!Demonfire!", msgObj: "", slot: 505, hasGsn: false },
  { name: "detect evil", spellFun: "spell_detect_evil", target: 3, position: 8, levels: [11, 4, 12, 53], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "The red in your vision disappears.", msgObj: "", slot: 18, hasGsn: false },
  { name: "detect good", spellFun: "spell_detect_good", target: 3, position: 8, levels: [11, 4, 12, 53], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "The gold in your vision disappears.", msgObj: "", slot: 513, hasGsn: false },
  { name: "detect hidden", spellFun: "spell_detect_hidden", target: 3, position: 8, levels: [15, 11, 12, 53], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "You feel less aware of your surroundings.", msgObj: "", slot: 44, hasGsn: false },
  { name: "detect invis", spellFun: "spell_detect_invis", target: 3, position: 8, levels: [3, 8, 6, 53], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "You no longer see invisible objects.", msgObj: "", slot: 19, hasGsn: false },
  { name: "detect magic", spellFun: "spell_detect_magic", target: 3, position: 8, levels: [2, 6, 5, 53], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "The detect magic wears off.", msgObj: "", slot: 20, hasGsn: false },
  { name: "detect poison", spellFun: "spell_detect_poison", target: 4, position: 8, levels: [15, 7, 9, 53], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "!Detect Poison!", msgObj: "", slot: 21, hasGsn: false },
  { name: "dispel evil", spellFun: "spell_dispel_evil", target: 1, position: 7, levels: [53, 15, 53, 21], ratings: [1, 1, 2, 2], minMana: 15, beats: 12, nounDamage: "dispel evil", msgOff: "!Dispel Evil!", msgObj: "", slot: 22, hasGsn: false },
  { name: "dispel good", spellFun: "spell_dispel_good", target: 1, position: 7, levels: [53, 15, 53, 21], ratings: [1, 1, 2, 2], minMana: 15, beats: 12, nounDamage: "dispel good", msgOff: "!Dispel Good!", msgObj: "", slot: 512, hasGsn: false },
  { name: "dispel magic", spellFun: "spell_dispel_magic", target: 1, position: 7, levels: [16, 24, 30, 30], ratings: [1, 1, 2, 2], minMana: 15, beats: 12, nounDamage: "", msgOff: "!Dispel Magic!", msgObj: "", slot: 59, hasGsn: false },
  { name: "earthquake", spellFun: "spell_earthquake", target: 0, position: 7, levels: [53, 10, 53, 14], ratings: [1, 1, 2, 2], minMana: 15, beats: 12, nounDamage: "earthquake", msgOff: "!Earthquake!", msgObj: "", slot: 23, hasGsn: false },
  { name: "enchant armor", spellFun: "spell_enchant_armor", target: 4, position: 8, levels: [16, 53, 53, 53], ratings: [2, 2, 4, 4], minMana: 100, beats: 24, nounDamage: "", msgOff: "!Enchant Armor!", msgObj: "", slot: 510, hasGsn: false },
  { name: "enchant weapon", spellFun: "spell_enchant_weapon", target: 4, position: 8, levels: [17, 53, 53, 53], ratings: [2, 2, 4, 4], minMana: 100, beats: 24, nounDamage: "", msgOff: "!Enchant Weapon!", msgObj: "", slot: 24, hasGsn: false },
  { name: "energy drain", spellFun: "spell_energy_drain", target: 1, position: 7, levels: [19, 22, 26, 23], ratings: [1, 1, 2, 2], minMana: 35, beats: 12, nounDamage: "energy drain", msgOff: "!Energy Drain!", msgObj: "", slot: 25, hasGsn: false },
  { name: "faerie fire", spellFun: "spell_faerie_fire", target: 1, position: 7, levels: [6, 3, 5, 8], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "faerie fire", msgOff: "The pink aura around you fades away.", msgObj: "", slot: 72, hasGsn: false },
  { name: "faerie fog", spellFun: "spell_faerie_fog", target: 0, position: 8, levels: [14, 21, 16, 24], ratings: [1, 1, 2, 2], minMana: 12, beats: 12, nounDamage: "faerie fog", msgOff: "!Faerie Fog!", msgObj: "", slot: 73, hasGsn: false },
  { name: "farsight", spellFun: "spell_farsight", target: 0, position: 8, levels: [14, 16, 16, 53], ratings: [1, 1, 2, 2], minMana: 36, beats: 20, nounDamage: "farsight", msgOff: "!Farsight!", msgObj: "", slot: 521, hasGsn: false },
  { name: "fireball", spellFun: "spell_fireball", target: 1, position: 7, levels: [22, 53, 30, 26], ratings: [1, 1, 2, 2], minMana: 15, beats: 12, nounDamage: "fireball", msgOff: "!Fireball!", msgObj: "", slot: 26, hasGsn: false },
  { name: "fireproof", spellFun: "spell_fireproof", target: 4, position: 8, levels: [13, 12, 19, 18], ratings: [1, 1, 2, 2], minMana: 10, beats: 12, nounDamage: "", msgOff: "", msgObj: "$p's protective aura fades.", slot: 523, hasGsn: false },
  { name: "flamestrike", spellFun: "spell_flamestrike", target: 1, position: 7, levels: [53, 20, 53, 27], ratings: [1, 1, 2, 2], minMana: 20, beats: 12, nounDamage: "flamestrike", msgOff: "!Flamestrike!", msgObj: "", slot: 65, hasGsn: false },
  { name: "fly", spellFun: "spell_fly", target: 2, position: 8, levels: [10, 18, 20, 22], ratings: [1, 1, 2, 2], minMana: 10, beats: 18, nounDamage: "", msgOff: "You slowly float to the ground.", msgObj: "", slot: 56, hasGsn: false },
  { name: "floating disc", spellFun: "spell_floating_disc", target: 0, position: 8, levels: [4, 10, 7, 16], ratings: [1, 1, 2, 2], minMana: 40, beats: 24, nounDamage: "", msgOff: "!Floating disc!", msgObj: "", slot: 522, hasGsn: false },
  { name: "frenzy", spellFun: "spell_frenzy", target: 2, position: 8, levels: [53, 24, 53, 26], ratings: [1, 1, 2, 2], minMana: 30, beats: 24, nounDamage: "", msgOff: "Your rage ebbs.", msgObj: "", slot: 504, hasGsn: false },
  { name: "gate", spellFun: "spell_gate", target: 0, position: 7, levels: [27, 17, 32, 28], ratings: [1, 1, 2, 2], minMana: 80, beats: 12, nounDamage: "", msgOff: "!Gate!", msgObj: "", slot: 83, hasGsn: false },
  { name: "giant strength", spellFun: "spell_giant_strength", target: 2, position: 8, levels: [11, 53, 22, 20], ratings: [1, 1, 2, 2], minMana: 20, beats: 12, nounDamage: "", msgOff: "You feel weaker.", msgObj: "", slot: 39, hasGsn: false },
  { name: "harm", spellFun: "spell_harm", target: 1, position: 7, levels: [53, 23, 53, 28], ratings: [1, 1, 2, 2], minMana: 35, beats: 12, nounDamage: "harm spell", msgOff: "!Harm!,\t\t", msgObj: null, slot: 27, hasGsn: false },
  { name: "haste", spellFun: "spell_haste", target: 2, position: 7, levels: [21, 53, 26, 29], ratings: [1, 1, 2, 2], minMana: 30, beats: 12, nounDamage: "", msgOff: "You feel yourself slow down.", msgObj: "", slot: 502, hasGsn: false },
  { name: "heal", spellFun: "spell_heal", target: 2, position: 7, levels: [53, 21, 33, 30], ratings: [1, 1, 2, 2], minMana: 50, beats: 12, nounDamage: "", msgOff: "!Heal!", msgObj: "", slot: 28, hasGsn: false },
  { name: "heat metal", spellFun: "spell_heat_metal", target: 1, position: 7, levels: [53, 16, 53, 23], ratings: [1, 1, 2, 2], minMana: 25, beats: 18, nounDamage: "spell", msgOff: "!Heat Metal!", msgObj: "", slot: 516, hasGsn: false },
  { name: "holy word", spellFun: "spell_holy_word", target: 0, position: 7, levels: [53, 36, 53, 42], ratings: [2, 2, 4, 4], minMana: 200, beats: 24, nounDamage: "divine wrath", msgOff: "!Holy Word!", msgObj: "", slot: 506, hasGsn: false },
  { name: "identify", spellFun: "spell_identify", target: 4, position: 8, levels: [15, 16, 18, 53], ratings: [1, 1, 2, 2], minMana: 12, beats: 24, nounDamage: "", msgOff: "!Identify!", msgObj: "", slot: 53, hasGsn: false },
  { name: "infravision", spellFun: "spell_infravision", target: 2, position: 8, levels: [9, 13, 10, 16], ratings: [1, 1, 2, 2], minMana: 5, beats: 18, nounDamage: "", msgOff: "You no longer see in the dark.", msgObj: "", slot: 77, hasGsn: false },
  { name: "invisibility", spellFun: "spell_invis", target: 5, position: 8, levels: [5, 53, 9, 53], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "You are no longer invisible.", msgObj: "$p fades into view.", slot: 29, hasGsn: true },
  { name: "know alignment", spellFun: "spell_know_alignment", target: 2, position: 7, levels: [12, 9, 20, 53], ratings: [1, 1, 2, 2], minMana: 9, beats: 12, nounDamage: "", msgOff: "!Know Alignment!", msgObj: "", slot: 58, hasGsn: false },
  { name: "lightning bolt", spellFun: "spell_lightning_bolt", target: 1, position: 7, levels: [13, 23, 18, 16], ratings: [1, 1, 2, 2], minMana: 15, beats: 12, nounDamage: "lightning bolt", msgOff: "!Lightning Bolt!", msgObj: "", slot: 30, hasGsn: false },
  { name: "locate object", spellFun: "spell_locate_object", target: 0, position: 8, levels: [9, 15, 11, 53], ratings: [1, 1, 2, 2], minMana: 20, beats: 18, nounDamage: "", msgOff: "!Locate Object!", msgObj: "", slot: 31, hasGsn: false },
  { name: "magic missile", spellFun: "spell_magic_missile", target: 1, position: 7, levels: [1, 53, 2, 2], ratings: [1, 1, 2, 2], minMana: 15, beats: 12, nounDamage: "magic missile", msgOff: "!Magic Missile!", msgObj: "", slot: 32, hasGsn: false },
  { name: "mass healing", spellFun: "spell_mass_healing", target: 0, position: 8, levels: [53, 38, 53, 46], ratings: [2, 2, 4, 4], minMana: 100, beats: 36, nounDamage: "", msgOff: "!Mass Healing!", msgObj: "", slot: 508, hasGsn: false },
  { name: "mass invis", spellFun: "spell_mass_invis", target: 0, position: 8, levels: [22, 25, 31, 53], ratings: [1, 1, 2, 2], minMana: 20, beats: 24, nounDamage: "", msgOff: "You are no longer invisible.", msgObj: "", slot: 69, hasGsn: true },
  { name: "nexus", spellFun: "spell_nexus", target: 0, position: 8, levels: [40, 35, 50, 45], ratings: [2, 2, 4, 4], minMana: 150, beats: 36, nounDamage: "", msgOff: "!Nexus!", msgObj: "", slot: 520, hasGsn: false },
  { name: "pass door", spellFun: "spell_pass_door", target: 3, position: 8, levels: [24, 32, 25, 37], ratings: [1, 1, 2, 2], minMana: 20, beats: 12, nounDamage: "", msgOff: "You feel solid again.", msgObj: "", slot: 74, hasGsn: false },
  { name: "plague", spellFun: "spell_plague", target: 1, position: 7, levels: [23, 17, 36, 26], ratings: [1, 1, 2, 2], minMana: 20, beats: 12, nounDamage: "sickness", msgOff: "Your sores vanish.", msgObj: "", slot: 503, hasGsn: true },
  { name: "poison", spellFun: "spell_poison", target: 6, position: 7, levels: [17, 12, 15, 21], ratings: [1, 1, 2, 2], minMana: 10, beats: 12, nounDamage: "poison", msgOff: "You feel less sick.", msgObj: "The poison on $p dries up.", slot: 33, hasGsn: true },
  { name: "portal", spellFun: "spell_portal", target: 0, position: 8, levels: [35, 30, 45, 40], ratings: [2, 2, 4, 4], minMana: 100, beats: 24, nounDamage: "", msgOff: "!Portal!", msgObj: "", slot: 519, hasGsn: false },
  { name: "protection evil", spellFun: "spell_protection_evil", target: 3, position: 8, levels: [12, 9, 17, 11], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "You feel less protected.", msgObj: "", slot: 34, hasGsn: false },
  { name: "protection good", spellFun: "spell_protection_good", target: 3, position: 8, levels: [12, 9, 17, 11], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "You feel less protected.", msgObj: "", slot: 514, hasGsn: false },
  { name: "ray of truth", spellFun: "spell_ray_of_truth", target: 1, position: 7, levels: [53, 35, 53, 47], ratings: [1, 1, 2, 2], minMana: 20, beats: 12, nounDamage: "ray of truth", msgOff: "!Ray of Truth!", msgObj: "", slot: 518, hasGsn: false },
  { name: "recharge", spellFun: "spell_recharge", target: 4, position: 8, levels: [9, 53, 53, 53], ratings: [1, 1, 2, 2], minMana: 60, beats: 24, nounDamage: "", msgOff: "!Recharge!", msgObj: "", slot: 517, hasGsn: false },
  { name: "refresh", spellFun: "spell_refresh", target: 2, position: 8, levels: [8, 5, 12, 9], ratings: [1, 1, 2, 2], minMana: 12, beats: 18, nounDamage: "refresh", msgOff: "!Refresh!", msgObj: "", slot: 81, hasGsn: false },
  { name: "remove curse", spellFun: "spell_remove_curse", target: 5, position: 8, levels: [53, 18, 53, 22], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "!Remove Curse!", msgObj: "", slot: 35, hasGsn: false },
  { name: "sanctuary", spellFun: "spell_sanctuary", target: 2, position: 8, levels: [36, 20, 42, 30], ratings: [1, 1, 2, 2], minMana: 75, beats: 12, nounDamage: "", msgOff: "The white aura around your body fades.", msgObj: "", slot: 36, hasGsn: true },
  { name: "shield", spellFun: "spell_shield", target: 2, position: 8, levels: [20, 35, 35, 40], ratings: [1, 1, 2, 2], minMana: 12, beats: 18, nounDamage: "", msgOff: "Your force shield shimmers then fades away.", msgObj: "", slot: 67, hasGsn: false },
  { name: "shocking grasp", spellFun: "spell_shocking_grasp", target: 1, position: 7, levels: [10, 53, 14, 13], ratings: [1, 1, 2, 2], minMana: 15, beats: 12, nounDamage: "shocking grasp", msgOff: "!Shocking Grasp!", msgObj: "", slot: 53, hasGsn: false },
  { name: "sleep", spellFun: "spell_sleep", target: 1, position: 8, levels: [10, 53, 11, 53], ratings: [1, 1, 2, 2], minMana: 15, beats: 12, nounDamage: "", msgOff: "You feel less tired.", msgObj: "", slot: 38, hasGsn: true },
  { name: "slow", spellFun: "spell_slow", target: 1, position: 7, levels: [23, 30, 29, 32], ratings: [1, 1, 2, 2], minMana: 30, beats: 12, nounDamage: "", msgOff: "You feel yourself speed up.", msgObj: "", slot: 515, hasGsn: false },
  { name: "spark bolt", spellFun: "spell_spark_bolt", target: 1, position: 7, levels: [1, 1, 1, 1], ratings: [1, 1, 1, 1], minMana: 15, beats: 12, nounDamage: "spark bolt", msgOff: "!Spark Bolt!", msgObj: "", slot: 0, hasGsn: false },
  { name: "stone skin", spellFun: "spell_stone_skin", target: 3, position: 8, levels: [25, 40, 40, 45], ratings: [1, 1, 2, 2], minMana: 12, beats: 18, nounDamage: "", msgOff: "Your skin feels soft again.", msgObj: "", slot: 66, hasGsn: false },
  { name: "summon", spellFun: "spell_summon", target: 0, position: 8, levels: [24, 12, 29, 22], ratings: [1, 1, 2, 2], minMana: 50, beats: 12, nounDamage: "", msgOff: "!Summon!", msgObj: "", slot: 40, hasGsn: false },
  { name: "teleport", spellFun: "spell_teleport", target: 3, position: 7, levels: [13, 22, 25, 36], ratings: [1, 1, 2, 2], minMana: 35, beats: 12, nounDamage: "", msgOff: "!Teleport!", msgObj: "", slot: 2, hasGsn: false },
  { name: "ventriloquate", spellFun: "spell_ventriloquate", target: 0, position: 8, levels: [1, 53, 2, 53], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "!Ventriloquate!", msgObj: "", slot: 41, hasGsn: false },
  { name: "weaken", spellFun: "spell_weaken", target: 1, position: 7, levels: [11, 14, 16, 17], ratings: [1, 1, 2, 2], minMana: 20, beats: 12, nounDamage: "spell", msgOff: "You feel stronger.", msgObj: "", slot: 68, hasGsn: false },
  { name: "word of recall", spellFun: "spell_word_of_recall", target: 3, position: 5, levels: [32, 28, 40, 30], ratings: [1, 1, 2, 2], minMana: 5, beats: 12, nounDamage: "", msgOff: "!Word of Recall!", msgObj: "", slot: 42, hasGsn: false },
  { name: "acid breath", spellFun: "spell_acid_breath", target: 1, position: 7, levels: [31, 32, 33, 34], ratings: [1, 1, 2, 2], minMana: 100, beats: 24, nounDamage: "blast of acid", msgOff: "!Acid Breath!", msgObj: "", slot: 200, hasGsn: false },
  { name: "fire breath", spellFun: "spell_fire_breath", target: 1, position: 7, levels: [40, 45, 50, 51], ratings: [1, 1, 2, 2], minMana: 200, beats: 24, nounDamage: "blast of flame", msgOff: "The smoke leaves your eyes.", msgObj: "", slot: 201, hasGsn: false },
  { name: "frost breath", spellFun: "spell_frost_breath", target: 1, position: 7, levels: [34, 36, 38, 40], ratings: [1, 1, 2, 2], minMana: 125, beats: 24, nounDamage: "blast of frost", msgOff: "!Frost Breath!", msgObj: "", slot: 202, hasGsn: false },
  { name: "gas breath", spellFun: "spell_gas_breath", target: 0, position: 7, levels: [39, 43, 47, 50], ratings: [1, 1, 2, 2], minMana: 175, beats: 24, nounDamage: "blast of gas", msgOff: "!Gas Breath!", msgObj: "", slot: 203, hasGsn: false },
  { name: "lightning breath", spellFun: "spell_lightning_breath", target: 1, position: 7, levels: [37, 40, 43, 46], ratings: [1, 1, 2, 2], minMana: 150, beats: 24, nounDamage: "blast of lightning", msgOff: "!Lightning Breath!", msgObj: "", slot: 204, hasGsn: false },
  { name: "general purpose", spellFun: "spell_general_purpose", target: 1, position: 7, levels: [53, 53, 53, 53], ratings: [0, 0, 0, 0], minMana: 0, beats: 12, nounDamage: "general purpose ammo", msgOff: "!General Purpose Ammo!", msgObj: "", slot: 401, hasGsn: false },
  { name: "high explosive", spellFun: "spell_high_explosive", target: 1, position: 7, levels: [53, 53, 53, 53], ratings: [0, 0, 0, 0], minMana: 0, beats: 12, nounDamage: "high explosive ammo", msgOff: "!High Explosive Ammo!", msgObj: "", slot: 402, hasGsn: false },
  { name: "axe", spellFun: "spell_null", target: 0, position: 7, levels: [1, 1, 1, 1], ratings: [6, 6, 5, 4], minMana: 0, beats: 0, nounDamage: "", msgOff: "!Axe!", msgObj: "", slot: 0, hasGsn: true },
  { name: "dagger", spellFun: "spell_null", target: 0, position: 7, levels: [1, 1, 1, 1], ratings: [2, 3, 2, 2], minMana: 0, beats: 0, nounDamage: "", msgOff: "!Dagger!", msgObj: "", slot: 0, hasGsn: true },
  { name: "flail", spellFun: "spell_null", target: 0, position: 7, levels: [1, 1, 1, 1], ratings: [6, 3, 6, 4], minMana: 0, beats: 0, nounDamage: "", msgOff: "!Flail!", msgObj: "", slot: 0, hasGsn: true },
  { name: "mace", spellFun: "spell_null", target: 0, position: 7, levels: [1, 1, 1, 1], ratings: [5, 2, 3, 3], minMana: 0, beats: 0, nounDamage: "", msgOff: "!Mace!", msgObj: "", slot: 0, hasGsn: true },
  { name: "polearm", spellFun: "spell_null", target: 0, position: 7, levels: [1, 1, 1, 1], ratings: [6, 6, 6, 4], minMana: 0, beats: 0, nounDamage: "", msgOff: "!Polearm!", msgObj: "", slot: 0, hasGsn: true },
  { name: "shield block", spellFun: "spell_null", target: 0, position: 7, levels: [1, 1, 1, 1], ratings: [6, 4, 6, 2], minMana: 0, beats: 0, nounDamage: "", msgOff: "!Shield!", msgObj: "", slot: 0, hasGsn: true },
  { name: "spear", spellFun: "spell_null", target: 0, position: 7, levels: [1, 1, 1, 1], ratings: [4, 4, 4, 3], minMana: 0, beats: 0, nounDamage: "", msgOff: "!Spear!", msgObj: "", slot: 0, hasGsn: true },
  { name: "sword", spellFun: "spell_null", target: 0, position: 7, levels: [1, 1, 1, 1], ratings: [5, 6, 3, 2], minMana: 0, beats: 0, nounDamage: "", msgOff: "!sword!", msgObj: "", slot: 0, hasGsn: true },
  { name: "whip", spellFun: "spell_null", target: 0, position: 7, levels: [1, 1, 1, 1], ratings: [6, 5, 5, 4], minMana: 0, beats: 0, nounDamage: "", msgOff: "!Whip!", msgObj: "", slot: 0, hasGsn: true },
  { name: "backstab", spellFun: "spell_null", target: 0, position: 8, levels: [53, 53, 1, 53], ratings: [0, 0, 5, 0], minMana: 0, beats: 24, nounDamage: "backstab", msgOff: "!Backstab!", msgObj: "", slot: 0, hasGsn: true },
  { name: "bash", spellFun: "spell_null", target: 0, position: 7, levels: [53, 53, 53, 1], ratings: [0, 0, 0, 4], minMana: 0, beats: 24, nounDamage: "bash", msgOff: "!Bash!", msgObj: "", slot: 0, hasGsn: true },
  { name: "berserk", spellFun: "spell_null", target: 0, position: 7, levels: [53, 53, 53, 18], ratings: [0, 0, 0, 5], minMana: 0, beats: 24, nounDamage: "", msgOff: "You feel your pulse slow down.", msgObj: "", slot: 0, hasGsn: true },
  { name: "dirt kicking", spellFun: "spell_null", target: 0, position: 7, levels: [53, 53, 3, 3], ratings: [0, 0, 4, 4], minMana: 0, beats: 24, nounDamage: "kicked dirt", msgOff: "You rub the dirt out of your eyes.", msgObj: "", slot: 0, hasGsn: true },
  { name: "disarm", spellFun: "spell_null", target: 0, position: 7, levels: [53, 53, 12, 11], ratings: [0, 0, 6, 4], minMana: 0, beats: 24, nounDamage: "", msgOff: "!Disarm!", msgObj: "", slot: 0, hasGsn: true },
  { name: "dodge", spellFun: "spell_null", target: 0, position: 7, levels: [20, 22, 1, 13], ratings: [8, 8, 4, 6], minMana: 0, beats: 0, nounDamage: "", msgOff: "!Dodge!", msgObj: "", slot: 0, hasGsn: true },
  { name: "enhanced damage", spellFun: "spell_null", target: 0, position: 7, levels: [45, 30, 25, 1], ratings: [10, 9, 5, 3], minMana: 0, beats: 0, nounDamage: "", msgOff: "!Enhanced Damage!", msgObj: "", slot: 0, hasGsn: true },
  { name: "envenom", spellFun: "spell_null", target: 0, position: 5, levels: [53, 53, 10, 53], ratings: [0, 0, 4, 0], minMana: 0, beats: 36, nounDamage: "", msgOff: "!Envenom!", msgObj: "", slot: 0, hasGsn: true },
  { name: "hand to hand", spellFun: "spell_null", target: 0, position: 7, levels: [25, 10, 15, 6], ratings: [8, 5, 6, 4], minMana: 0, beats: 0, nounDamage: "", msgOff: "!Hand to Hand!", msgObj: "", slot: 0, hasGsn: true },
  { name: "kick", spellFun: "spell_null", target: 1, position: 7, levels: [53, 12, 14, 8], ratings: [0, 4, 6, 3], minMana: 0, beats: 12, nounDamage: "kick", msgOff: "!Kick!", msgObj: "", slot: 0, hasGsn: true },
  { name: "parry", spellFun: "spell_null", target: 0, position: 7, levels: [22, 20, 13, 1], ratings: [8, 8, 6, 4], minMana: 0, beats: 0, nounDamage: "", msgOff: "!Parry!", msgObj: "", slot: 0, hasGsn: true },
  { name: "rescue", spellFun: "spell_null", target: 0, position: 7, levels: [53, 53, 53, 1], ratings: [0, 0, 0, 4], minMana: 0, beats: 12, nounDamage: "", msgOff: "!Rescue!", msgObj: "", slot: 0, hasGsn: true },
  { name: "trip", spellFun: "spell_null", target: 0, position: 7, levels: [53, 53, 1, 15], ratings: [0, 0, 4, 8], minMana: 0, beats: 24, nounDamage: "trip", msgOff: "!Trip!", msgObj: "", slot: 0, hasGsn: true },
  { name: "second attack", spellFun: "spell_null", target: 0, position: 7, levels: [30, 24, 12, 5], ratings: [10, 8, 5, 3], minMana: 0, beats: 0, nounDamage: "", msgOff: "!Second Attack!", msgObj: "", slot: 0, hasGsn: true },
  { name: "third attack", spellFun: "spell_null", target: 0, position: 7, levels: [53, 53, 24, 12], ratings: [0, 0, 10, 4], minMana: 0, beats: 0, nounDamage: "", msgOff: "!Third Attack!", msgObj: "", slot: 0, hasGsn: true },
  { name: "fast healing", spellFun: "spell_null", target: 0, position: 4, levels: [15, 9, 16, 6], ratings: [8, 5, 6, 4], minMana: 0, beats: 0, nounDamage: "", msgOff: "!Fast Healing!", msgObj: "", slot: 0, hasGsn: true },
  { name: "haggle", spellFun: "spell_null", target: 0, position: 5, levels: [7, 18, 1, 14], ratings: [5, 8, 3, 6], minMana: 0, beats: 0, nounDamage: "", msgOff: "!Haggle!", msgObj: "", slot: 0, hasGsn: true },
  { name: "hide", spellFun: "spell_null", target: 0, position: 5, levels: [53, 53, 1, 12], ratings: [0, 0, 4, 6], minMana: 0, beats: 12, nounDamage: "", msgOff: "!Hide!", msgObj: "", slot: 0, hasGsn: true },
  { name: "lore", spellFun: "spell_null", target: 0, position: 5, levels: [10, 10, 6, 20], ratings: [6, 6, 4, 8], minMana: 0, beats: 36, nounDamage: "", msgOff: "!Lore!", msgObj: "", slot: 0, hasGsn: true },
  { name: "meditation", spellFun: "spell_null", target: 0, position: 4, levels: [6, 6, 15, 15], ratings: [5, 5, 8, 8], minMana: 0, beats: 0, nounDamage: "", msgOff: "Meditation", msgObj: "", slot: 0, hasGsn: true },
  { name: "peek", spellFun: "spell_null", target: 0, position: 8, levels: [8, 21, 1, 14], ratings: [5, 7, 3, 6], minMana: 0, beats: 0, nounDamage: "", msgOff: "!Peek!", msgObj: "", slot: 0, hasGsn: true },
  { name: "pick lock", spellFun: "spell_null", target: 0, position: 8, levels: [25, 25, 7, 25], ratings: [8, 8, 4, 8], minMana: 0, beats: 12, nounDamage: "", msgOff: "!Pick!", msgObj: "", slot: 0, hasGsn: true },
  { name: "sneak", spellFun: "spell_null", target: 0, position: 8, levels: [53, 53, 4, 10], ratings: [0, 0, 4, 6], minMana: 0, beats: 12, nounDamage: "", msgOff: "You no longer feel stealthy.", msgObj: "", slot: 0, hasGsn: true },
  { name: "steal", spellFun: "spell_null", target: 0, position: 8, levels: [53, 53, 5, 53], ratings: [0, 0, 4, 0], minMana: 0, beats: 24, nounDamage: "", msgOff: "!Steal!", msgObj: "", slot: 0, hasGsn: true },
  { name: "scrolls", spellFun: "spell_null", target: 0, position: 8, levels: [1, 1, 1, 1], ratings: [2, 3, 5, 8], minMana: 0, beats: 24, nounDamage: "", msgOff: "!Scrolls!", msgObj: "", slot: 0, hasGsn: true },
  { name: "staves", spellFun: "spell_null", target: 0, position: 8, levels: [1, 1, 1, 1], ratings: [2, 3, 5, 8], minMana: 0, beats: 12, nounDamage: "", msgOff: "!Staves!", msgObj: "", slot: 0, hasGsn: true },
  { name: "wands", spellFun: "spell_null", target: 0, position: 8, levels: [1, 1, 1, 1], ratings: [2, 3, 5, 8], minMana: 0, beats: 12, nounDamage: "", msgOff: "!Wands!", msgObj: "", slot: 0, hasGsn: true },
  { name: "recall", spellFun: "spell_null", target: 0, position: 8, levels: [1, 1, 1, 1], ratings: [2, 2, 2, 2], minMana: 0, beats: 12, nounDamage: "", msgOff: "!Recall!", msgObj: "", slot: 0, hasGsn: true },
];
