import AbilityGroup from "./ability-group";

const AbilityGroupDescriptions: { [key in AbilityGroup]: string } = {
  [AbilityGroup.None]: "None",
  [AbilityGroup.Alteration]: "Alteration",
  [AbilityGroup.AnalyticalMind]: "Analytical Mind",
  [AbilityGroup.AngelBasics]: "Angel Basics",
  [AbilityGroup.AngelDefault]: "Angel Default",
  [AbilityGroup.ArmsmanBasics]: "Armsman Basics",
  [AbilityGroup.ArmsmanDefault]: "Armsman Default",
  [AbilityGroup.AssassinBasics]: "Assassin Basics",
  [AbilityGroup.AssassinDefault]: "Assassin Default",
  [AbilityGroup.Attack]: "Attack",
  [AbilityGroup.BalanxBasics]: "Balanx Basics",
  [AbilityGroup.BalanxDefault]: "Balanx Default",
  [AbilityGroup.BanditBasics]: "Bandit Basics",
  [AbilityGroup.BanditDefault]: "Bandit Default",
  [AbilityGroup.BarbarianBasics]: "Barbarian Basics",
  [AbilityGroup.BarbarianDefault]: "Barbarian Default",
  [AbilityGroup.BardBasics]: "Bard Basics",
  [AbilityGroup.BardDefault]: "Bard Default",
  [AbilityGroup.BattlemageBasics]: "Battlemage Basics",
  [AbilityGroup.BattlemageDefault]: "Battlemage Default",
  [AbilityGroup.Battlemagic]: "Battlemagic",
  [AbilityGroup.BattleragerBasics]: "Battlerager Basics",
  [AbilityGroup.BattleragerDefault]: "Battlerager Default",
  [AbilityGroup.Beguiling]: "Beguiling",
  [AbilityGroup.Benedictions]: "Benedictions",
  [AbilityGroup.BladesingerBasics]: "Bladesinger Basics",
  [AbilityGroup.BladesingerDefault]: "Bladesinger Default",
  [AbilityGroup.BrewmasterBasics]: "Brewmaster Basics",
  [AbilityGroup.BrewmasterDefault]: "Brewmaster Default",
  [AbilityGroup.CharlatanBasics]: "Charlatan Basics",
  [AbilityGroup.CharlatanDefault]: "Charlatan Default",
  [AbilityGroup.ClericBasics]: "Cleric Basics",
  [AbilityGroup.ClericDefault]: "Cleric Default",
  [AbilityGroup.Combat]: "Combat",
  [AbilityGroup.ConfessorBasics]: "Confessor Basics",
  [AbilityGroup.ConfessorDefault]: "Confessor Default",
  [AbilityGroup.Creation]: "Creation",
  [AbilityGroup.CrusaderBasics]: "Crusader Basics",
  [AbilityGroup.CrusaderDefault]: "Crusader Default",
  [AbilityGroup.Curative]: "Curative",
  [AbilityGroup.DemonBasics]: "Demon Basics",
  [AbilityGroup.DemonDefault]: "Demon Default",
  [AbilityGroup.Detection]: "Detection",
  [AbilityGroup.DivineBlessings]: "Divine Blessing",
  [AbilityGroup.Draconian]: "Draconian",
  [AbilityGroup.DraconianDefault]: "Draconian Default",
  [AbilityGroup.DragonDefault]: "Dragon Default",
  [AbilityGroup.DragonslayerBasics]: "Dragonslayer Basics",
  [AbilityGroup.DragonslayerDefault]: "Dragonslayer Default",
  [AbilityGroup.DruidBasics]: "Druid Basics",
  [AbilityGroup.DruidDefault]: "Druid Default",
  [AbilityGroup.Earth]: "Earth",
  [AbilityGroup.EideticMemory]: "Eidetic Memory",
  [AbilityGroup.Eldritch]: "Eldritch",
  [AbilityGroup.EldritchBasics]: "Eldritch Basics",
  [AbilityGroup.EldritchDefault]: "Eldritch Default",
  [AbilityGroup.Elemental]: "Elemental",
  [AbilityGroup.Enchantment]: "Enchantment",
  [AbilityGroup.EnhancedEnchantment]: "Enhanced Enchantment",
  [AbilityGroup.EnchantorBasics]: "Enchantor Basics",
  [AbilityGroup.EnchantorDefault]: "Enchantor Default",
  [AbilityGroup.Fire]: "Fire",
  [AbilityGroup.GiantBasics]: "Giant Basics",
  [AbilityGroup.GiantDefault]: "Giant Default",
  [AbilityGroup.GiantExtras]: "Giant Extras",
  [AbilityGroup.GreaterIllusions]: "Greater Illusions",
  [AbilityGroup.Harmful]: "Harmful",
  [AbilityGroup.Healing]: "Healing",
  [AbilityGroup.Holy]: "Holy",
  [AbilityGroup.HymnsOfLife]: "Hymns of Life",
  [AbilityGroup.Illusion]: "Illusion",
  [AbilityGroup.IllusionistBasics]: "Illusionist Basics",
  [AbilityGroup.IllusionistDefault]: "Illusionist Default",
  [AbilityGroup.Invocation]: "Invocation",
  [AbilityGroup.InvokerBasics]: "Invoker Basics",
  [AbilityGroup.InvokerDefault]: "Invoker Default",
  [AbilityGroup.JongleurBasics]: "Jongleur Basics",
  [AbilityGroup.JongleurDefault]: "Jongleur Default",
  [AbilityGroup.MageBasics]: "Mage Basics",
  [AbilityGroup.MageDefault]: "Mage Default",
  [AbilityGroup.Maladictions]: "Maladictions",
  [AbilityGroup.Mentalism]: "Mentalism",
  [AbilityGroup.MentalistBasics]: "Mentalist Basics",
  [AbilityGroup.MentalistDefault]: "Mentalist Default",
  [AbilityGroup.Metal]: "Metal",
  [AbilityGroup.MonkBasics]: "Monk Basics",
  [AbilityGroup.MonkDefault]: "Monk Default",
  [AbilityGroup.Nature]: "Nature",
  [AbilityGroup.NecromancerBasics]: "Necromancer Basics",
  [AbilityGroup.NecromancerDefault]: "Necromancer Default",
  [AbilityGroup.Necromancy]: "Necromancy",
  [AbilityGroup.NightshadeBasics]: "Nightshade Basics",
  [AbilityGroup.NightshadeDefault]: "Nightshade Default",
  [AbilityGroup.NinjaBasics]: "Ninja Basics",
  [AbilityGroup.NinjaDefault]: "Ninja Default",
  [AbilityGroup.PaladinBasics]: "Paladin Basics",
  [AbilityGroup.PaladinDefault]: "Paladin Default",
  [AbilityGroup.PirateBasics]: "Pirate Basics",
  [AbilityGroup.PirateDefault]: "Pirate Default",
  [AbilityGroup.Polearm]: "Polearm",
  [AbilityGroup.PriestBasics]: "Priest Basics",
  [AbilityGroup.PriestDefault]: "Priest Default",
  [AbilityGroup.Protective]: "Protective",
  [AbilityGroup.Psionic]: "Psionic",
  [AbilityGroup.Purification]: "Purification",
  [AbilityGroup.RangerBasics]: "Ranger Basics",
  [AbilityGroup.RangerDefault]: "Ranger Default",
  [AbilityGroup.RomBasics]: "Rom Basics",
  [AbilityGroup.RunesmithBasics]: "Runesmith Basics",
  [AbilityGroup.RunesmithDefault]: "Runesmith Default",
  [AbilityGroup.Runesmithing]: "Runesmithing",
  [AbilityGroup.SamuraiBasics]: "Samurai Basics",
  [AbilityGroup.SamuraiDefault]: "Samurai Default",
  [AbilityGroup.ShamanBasics]: "Shaman Basics",
  [AbilityGroup.ShamanDefault]: "Shaman Default",
  [AbilityGroup.ShadowknightBasics]: "Shadowknight Basics",
  [AbilityGroup.ShadowknightDefault]: "Shadowknight Default",
  [AbilityGroup.ShadowmageBasics]: "Shadowmage Basics",
  [AbilityGroup.ShadowmageDefault]: "Shadowmage Default",
  [AbilityGroup.Shadowmagic]: "Shadowmagic",
  [AbilityGroup.Shukenja]: "Shukenja",
  [AbilityGroup.ShukenjaBasics]: "Shukenja Basics",
  [AbilityGroup.ShukenjaDefault]: "Shukenja Default",
  [AbilityGroup.SkaldBasics]: "Skald Basics",
  [AbilityGroup.SkaldChants]: "Skald Chants",
  [AbilityGroup.SkaldDefault]: "Skald Default",
  [AbilityGroup.SlipperyMind]: "Slippery Mind",
  [AbilityGroup.Spear]: "Spear",
  [AbilityGroup.SwashbucklerBasics]: "Swashbuckler Basics",
  [AbilityGroup.SwashbucklerDefault]: "Swashbuckler Default",
  [AbilityGroup.ThiefBasics]: "Thief Basics",
  [AbilityGroup.ThiefDefault]: "Thief Default",
  [AbilityGroup.TransmuterBasics]: "Transmuter Basics",
  [AbilityGroup.TransmuterDefault]: "Transmuter Default",
  [AbilityGroup.Transportation]: "Transportation",
  [AbilityGroup.Unholy]: "Unholy",
  [AbilityGroup.Vampire]: "Vampire",
  [AbilityGroup.Voodoo]: "Voodoo",
  [AbilityGroup.WarHymns]: "War Hymns",
  [AbilityGroup.WarlockBasics]: "Warlock Basics",
  [AbilityGroup.WarlockDefault]: "Warlock Default",
  [AbilityGroup.WarriorBasics]: "Warrior Basics",
  [AbilityGroup.WarriorDefault]: "Warrior Default",
  [AbilityGroup.Water]: "Water",
  [AbilityGroup.WayOfTheMoon]: "Way of the Moon",
  [AbilityGroup.WayOfTheStars]: "Way of the Stars",
  [AbilityGroup.WayOfTheSun]: "Way of the Sun",
  [AbilityGroup.Weather]: "Weather",
  [AbilityGroup.Wind]: "Wind",
  [AbilityGroup.Weaponsmaster]: "Weaponsmaster",
  [AbilityGroup.Whip]: "Whip",
  [AbilityGroup.WitchBasics]: "Witch Basics",
  [AbilityGroup.WitchDefault]: "Witch Default",
  [AbilityGroup.Witchcraft]: "Witchcraft",
  [AbilityGroup.WujenBasics]: "Wujen Basics",
  [AbilityGroup.WujenDefault]: "Wujen Default",
  [AbilityGroup.Worship]: "Worship",
  [AbilityGroup.MasterySword]: "Mastery Sword",
  [AbilityGroup.MasteryMace]: "Mastery Mace",
  [AbilityGroup.MasteryDagger]: "Mastery Dagger",
  [AbilityGroup.MasteryPolearm]: "Mastery Polearm",
  [AbilityGroup.MasteryWhip]: "Mastery Whip",
  [AbilityGroup.Enhancement]: "Enhancement",
  [AbilityGroup.MasteryFlail]: "Mastery Flail",
  [AbilityGroup.MasterySpear]: "Mastery Spear",
  [AbilityGroup.MasteryAxe]: "Mastery Axe",
};

export default AbilityGroupDescriptions;
