// apps\game-client\src\pages\client-status-page.tsx
import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';

type HealthResult = {
  ok: boolean;
  statusText: string;
  latency?: number;
};

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: checkEndpoint — (no summary)
// @ai-hash: d5f1c7a6
// ── END AI-METHOD ──
async function checkEndpoint(label: string, url: string): Promise<HealthResult> {
  const start = performance.now();
  try {
    const res = await fetch(url, { method: 'GET' });
    const time = performance.now() - start;
    return {
      ok: res.ok,
      statusText: res.ok ? 'OK' : `HTTP ${res.status}`,
      latency: Math.round(time),
    };
  } catch (e) {
    return { ok: false, statusText: 'Connection Failed' };
  }
}

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: ClientStatusPage — (no summary)
// @ai-hash: b91ddc86
// ── END AI-METHOD ──
function ClientStatusPage() {
  const [results, setResults] = useState<{
    game: HealthResult | null;
    web: HealthResult | null;
  }>({
    game: null,
    web: null,
  });

  async function runChecks() {
    const [game, web, client] = await Promise.all([
      checkEndpoint('game-server', '/api/game/health'),
      checkEndpoint('web-server', '/api/web/health'),
      checkEndpoint('client', '/api/health'),
    ]);

    setResults({ game, web });
  }

  useEffect(() => {
    runChecks();

    // refresh every 5 seconds
    const id = setInterval(runChecks, 5000);
    return () => clearInterval(id);
  }, []);

  function renderRow(label: string, r: HealthResult | null) {
    if (!r)
      return (
        <tr>
          <td>{label}</td>
          <td colSpan={2}>Loading…</td>
        </tr>
      );

    return (
      <tr>
        <td>{label}</td>
        <td style={{ color: r.ok ? 'limegreen' : 'red' }}>{r.statusText}</td>
        <td>{r.latency ? `${r.latency} ms` : '-'}</td>
      </tr>
    );
  }

  return (
    <div style={{ padding: 20, fontFamily: 'sans-serif' }}>
      <h1>System Status</h1>
      <p style={{ opacity: 0.7 }}>Auto-refreshing every 5 seconds</p>

      <table
        style={{
          width: '100%',
          maxWidth: 600,
          borderCollapse: 'collapse',
          marginTop: 20,
        }}
      >
        <thead>
          <tr>
            <th style={{ textAlign: 'left' }}>Service</th>
            <th style={{ textAlign: 'left' }}>Status</th>
            <th style={{ textAlign: 'left' }}>Latency</th>
          </tr>
        </thead>
        <tbody>
          {renderRow('Game Server', results.game)}
          {renderRow('Web Server', results.web)}
        </tbody>
      </table>
    </div>
  );
}

const root = createRoot(document.getElementById('root')!);
root.render(<ClientStatusPage />);
