// apps\game-client\src\pages\MainContainer.tsx
import React from 'react';
import { createPortal } from 'react-dom';
import styles from '../styles/MainContainer.module.scss';
import { useVisualViewportHeight } from '../hooks/useVisualViewportHeight';
import Terminal from '../components/Terminal';

import { UserStyleOverrideModal } from '../components/UserStyleOverrideModal';
import UserScriptSandboxModal from '../components/UserScriptSandboxModal';
import ConnectModal from '../components/ConnectModal';
import PluginsModal from '../components/PluginsModal';

import { useUserCssOverrides, useMainContainer } from '../hooks/useMainContainer';
import { usePlugins } from '../hooks/usePlugins';

import { MainMenuBar } from '../components/MainMenuBar';
import { getHudThemeId, HUD_THEME_CHANGED_EVENT, type HudThemeId } from '../features/hudLayout/hudThemeStore';
import { resolveActiveTheme } from '../features/hudLayout/themeRegistry';
import { useGameConnection } from '../hooks/useGameConnection';
import { useBeforeUnloadGuard } from '../hooks/useBeforeUnloadGuard';

import { CORE_PLUGINS } from '../features/plugins/registry';
import { pluginHost } from '../features/plugins/pluginHost';

import { applyCssToDom, getAppliedCss } from '../features/userStyles/userStyleOverrideStore';
import LibraryModal from '../components/LibraryModal';
import AccountModal from '../components/AccountModal';

import EquipmentModal from '../components/EquipmentModal';
import { useEquipmentCapture } from '../hooks/useEquipmentCapture';
import { useEquipmentDeltas } from '../hooks/useEquipmentDeltas';

import AutoLevelingWizard from '../components/AutoLevelingWizard';
import { useAutoLeveling } from '../hooks/useAutoLeveling';
import { RuntimeSingleton } from '../features/userScripts/runtimeSingleton';
import { useTerminal } from '../hooks/useTerminal';
import { ShatteredArchiveTerminal } from '../features/terminal/shatteredArchiveTerminal';
import { DispatchEvent, ListenEvent } from '../features/event-emitter/event-dispatcher';
import { PLUGIN_CONFIG_PERSIST_EVENT, type PluginConfigPersistPayload } from '../features/plugins/pluginConfigPersist';
import FocusBarVitals from '../components/FocusBarVitals';
import ContributeIdentifyModal from '../components/ContributeIdentifyModal';
import ContributeCreatureLoreModal from '../components/ContributeCreatureLoreModal';
import ScriptingHelpModal from '../components/ScriptingHelpModal';
import { useAuthCallback } from '../hooks/useAuthCallback';
import { movementTracker } from '../features/movement/movementTracker';

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: MainContainer — (no summary)
// @ai-hash: 66d5b39d
// ── END AI-METHOD ──
export const MainContainer: React.FC = () => {
  useVisualViewportHeight();
  useAuthCallback();
  const main = useMainContainer();
  const gameConn = useGameConnection();

  const [hudThemeId, setHudThemeIdState] = React.useState<HudThemeId>(() => getHudThemeId());
  const [viewportWidth, setViewportWidth] = React.useState(() =>
    typeof window === 'undefined' ? 1024 : window.innerWidth,
  );

  React.useEffect(() => {
    const onResize = () => setViewportWidth(window.innerWidth);
    window.addEventListener('resize', onResize);
    return () => window.removeEventListener('resize', onResize);
  }, []);

  // Live theme switching: setHudThemeId (hudThemeStore.ts) dispatches this on
  // every change, same-tab included (localStorage's native `storage` event
  // never fires for a change made in the tab that called setItem, so that
  // alone can't drive this).
  React.useEffect(() => {
    return ListenEvent<{ id: HudThemeId }>(HUD_THEME_CHANGED_EVENT, (payload) => {
      if (payload?.id) setHudThemeIdState(payload.id);
    });
  }, []);

  const { theme: activeTheme, ShellComponent: ActiveShell } = resolveActiveTheme(hudThemeId, viewportWidth);

  /**
   * Terminal hoisting: <Terminal/> is rendered ONCE below (outside the
   * per-theme Suspense tree) into a container that is NEVER swapped, instead
   * of each shell rendering its own <Terminal/>. A theme switch would
   * otherwise unmount/remount Terminal — useTerminal.ts creates a BRAND NEW
   * xterm.js instance on every mount (scrollback: 5000 lines, empty), so a
   * live switch would silently wipe the visible session history.
   *
   * createPortal's container is part of React's identity check for the
   * portal fiber: passing a DIFFERENT container on a later render — e.g. the
   * new shell's own terminal-slot div after a theme switch — makes React
   * unmount the old portal's subtree and mount a fresh one into the new
   * container, exactly the remount this hoist exists to avoid (confirmed
   * live via Playwright: the xterm scrollback was lost on switch when the
   * portal target itself was the swapped div). So `terminalHost` here is a
   * detached DOM node created ONCE (lazy useState initializer) and passed to
   * createPortal for the app's entire lifetime — the portal target never
   * changes, so Terminal never remounts. Getting it to the RIGHT visual spot
   * is a separate, plain DOM operation: the effect below re-parents this
   * same node with .appendChild() into whichever shell's slot is currently
   * attached. appendChild on a node that already has a parent MOVES it
   * (removes then reinserts), which preserves the live xterm canvas/state —
   * it does not recreate anything.
   */
  const [terminalHost] = React.useState<HTMLDivElement>(() => {
    const el = document.createElement('div');
    el.style.width = '100%';
    el.style.height = '100%';
    // Every shell's terminal slot (.terminalBody, .playAreaTerminalShell) is
    // `display: flex` on purpose — Terminal.tsx's own root divs size
    // themselves via `flex: 1; min-height: 0`, which only takes effect when
    // their DIRECT parent is a flex container. Without this, terminalHost is
    // a plain block box: Terminal's flex rules go inert, its height
    // collapses to content/default instead of filling the slot, and the
    // slot's own flex-allocated space is left showing as empty background
    // behind it (caught live: a real gap below the terminal in compact mode).
    el.style.display = 'flex';
    el.style.minHeight = '0';
    el.style.minWidth = '0';
    return el;
  });
  const [terminalSlot, setTerminalSlot] = React.useState<HTMLDivElement | null>(null);
  const terminalSlotRef = React.useCallback((el: HTMLDivElement | null) => {
    if (el) setTerminalSlot(el);
  }, []);

  React.useEffect(() => {
    if (terminalSlot && terminalHost.parentElement !== terminalSlot) {
      terminalSlot.appendChild(terminalHost);
    }
  }, [terminalSlot, terminalHost]);

  // A theme's styles apply only while IT is the one actually rendering (not
  // the theme that was selected but fell back away from at a narrow width —
  // resolveActiveTheme already accounts for that, activeTheme is always the
  // one whose styles belong on screen right now) — and get stripped back out
  // the moment that stops being true, so "switching themes off returns to
  // today's default shell exactly" (spec §6).
  React.useEffect(() => {
    activeTheme.loadStyles?.();
  }, [activeTheme.id]);

  // Warn before closing/reloading the tab while a play-server connection is live.
  useBeforeUnloadGuard(gameConn.isConnected);

  const userScriptRuntime = RuntimeSingleton.Instance.GetUserScriptRuntime;
  const terminal = ShatteredArchiveTerminal.Instance;

  React.useEffect(() => {
    applyCssToDom(getAppliedCss());
  }, []);

  // App-lifetime singleton, independent of any one component's mount state (the compass
  // panel, autoleveling's own listeners, etc. all rely on this being bound regardless of
  // what else is currently mounted/unmounted).
  React.useEffect(() => movementTracker.bind(), []);

  const {
    userCssApplied,
    userCssDraft,
    setUserCssDraft,
    isStyleModalOpen,
    openStyleModal,
    closeStyleModal,
    saveUserCss,
    discardDraft,
  } = useUserCssOverrides();

  const [isScriptModalOpen, setIsScriptModalOpen] = React.useState(false);
  const [isPluginsModalOpen, setIsPluginsModalOpen] = React.useState(false);
  const [isAutoLevelingModalOpen, setIsAutoLevelingModalOpen] = React.useState(false);

  // Contribute modals
  const [isIdentifyModalOpen, setIsIdentifyModalOpen] = React.useState(false);
  const [isLoreModalOpen, setIsLoreModalOpen] = React.useState(false);

  const handleOpenCustomStyles = () => openStyleModal();
  const handleOpenScriptSandbox = () => setIsScriptModalOpen(true);
  const handleOpenConnect = () => main.openConnectModal();
  const handleOpenAccount = () => main.openAccountModal();
  const handleOpenPlugins = () => setIsPluginsModalOpen(true);
  const handleOpenLibrary = () => main.openLibraryModal();
  const handleOpenEquipment = () => main.openEquipmentModal();
  const handleOpenAutoLeveling = () => setIsAutoLevelingModalOpen(true);
  const handleOpenIdentifyObject = () => setIsIdentifyModalOpen(true);
  const handleOpenCreatureLore = () => setIsLoreModalOpen(true);

  const [isScriptingHelpOpen, setIsScriptingHelpOpen] = React.useState(false);
  const handleOpenScriptingHelp = () => setIsScriptingHelpOpen(true);

  const connectionId = React.useMemo(() => {
    const host = gameConn.currentHost;
    const port = gameConn.currentPort;

    if (!host || !port) return 'default';
    if (host.includes('dsl-mud')) return 'dsl-mud';
    return `${host}:${port}`;
  }, [gameConn.currentHost, gameConn.currentPort]);

  React.useEffect(() => {
    if (!connectionId) {
      return;
    }
    DispatchEvent('shatteredarchive:connection-changed', {
      connectionId,
      host: gameConn.currentHost,
      port: gameConn.currentPort,
    });
  }, [connectionId, gameConn.currentHost, gameConn.currentPort]);

  const plugins = usePlugins(connectionId);
  useEquipmentCapture(connectionId);
  useEquipmentDeltas(connectionId);

  const auto = useAutoLeveling(connectionId, gameConn.isConnected);

  /**
   * Plugin lifetime is scoped to the CONNECTION, and to nothing else.
   *
   * This deliberately does not depend on `plugins.installed`. It used to, and the
   * cleanup below is a full `pluginHost.shutdown()` — so every change to the
   * installed list (a config edit, a cloud sync, the boot storage migration,
   * toggling any other plugin) destroyed and re-`create()`d EVERY plugin closure.
   * See pluginHost.syncInstalled for why that broke text-to-speech outright.
   */
  React.useEffect(() => {
    pluginHost.setConnection(connectionId);

    for (const p of CORE_PLUGINS) {
      pluginHost.registerModule(p.create());
    }

    return () => {
      pluginHost.shutdown();
    };
  }, [connectionId]);

  /**
   * Which of the registered plugins are running. Diffed, never rebuilt — a plugin
   * that is already enabled and still enabled keeps the exact instance (and so its
   * queues, timers and subscriptions) across every one of these passes.
   *
   * Depends on `connectionId` as well so it re-applies after the effect above has
   * rebuilt the host for a new connection; effects run in declaration order, so
   * registration has already happened by the time this runs.
   */
  React.useEffect(() => {
    pluginHost.syncInstalled(plugins.installed);
  }, [connectionId, plugins.installed]);

  // Theme→plugin auto-enable (e.g. slate-amber turning on
  // world-time-and-identity). Declared AFTER the registration effect above
  // on purpose — effects run in declaration order, and pluginHost.enable()
  // silently no-ops if the plugin isn't registered yet.
  React.useEffect(() => {
    activeTheme.onActivate?.();
  }, [connectionId, activeTheme.id]);

  /**
   * A plugin changing its OWN config (e.g. text-to-speech's floating mode bubble)
   * has to land in the same store the config modal writes, or the effect above
   * reverts it on the next installed-list change. The plugin only sends a patch;
   * the merge onto the saved record happens here, where that record lives.
   */
  React.useEffect(() => {
    return ListenEvent<PluginConfigPersistPayload>(PLUGIN_CONFIG_PERSIST_EVENT, ({ pluginId, patch }) => {
      if (!pluginId || !patch) return;
      const record = plugins.getInstallRecord(pluginId as never);
      if (!record) return;
      plugins.updatePluginConfig(pluginId as never, { ...(record.userConfig ?? {}), ...patch });
    });
  }, [plugins]);

  return (
    <div className={styles.root}>
      <MainMenuBar
        onOpenCustomStyles={handleOpenCustomStyles}
        onOpenScriptSandbox={handleOpenScriptSandbox}
        onOpenConnect={handleOpenConnect}
        onOpenAccount={handleOpenAccount}
        onOpenPlugins={handleOpenPlugins}
        onOpenLibrary={handleOpenLibrary}
        onOpenEquipment={handleOpenEquipment}
        onOpenAutoLeveling={handleOpenAutoLeveling}
        onOpenIdentifyObject={handleOpenIdentifyObject}
        onOpenCreatureLore={handleOpenCreatureLore}
        onOpenScriptingHelp={handleOpenScriptingHelp}
      />

      <FocusBarVitals />

      <React.Suspense fallback={null}>
        <ActiveShell
          isConnected={gameConn.isConnected}
          sendRaw={gameConn.sendRaw}
          onOpenAutoLeveling={handleOpenAutoLeveling}
          autoLevelMode={auto.config.mode}
          autoLevelRunState={auto.runState}
          onSightseeRescan={auto.rescanRoom}
          terminalSlotRef={terminalSlotRef}
        />
      </React.Suspense>

      {createPortal(<Terminal />, terminalHost)}

      <UserStyleOverrideModal
        isOpen={isStyleModalOpen}
        appliedCss={userCssApplied}
        draftCss={userCssDraft}
        onChangeDraft={setUserCssDraft}
        onPreview={(css) => {
          saveUserCss(css);
          closeStyleModal();
        }}
        onSave={(css) => {
          saveUserCss(css);
          closeStyleModal();
        }}
        onDiscardDraft={() => {
          discardDraft();
          closeStyleModal();
        }}
        onClose={closeStyleModal}
      />

      <UserScriptSandboxModal
        isOpen={isScriptModalOpen}
        onClose={() => setIsScriptModalOpen(false)}
        connectionId={connectionId}
      />

      <PluginsModal
        isOpen={isPluginsModalOpen}
        onClose={() => setIsPluginsModalOpen(false)}
        connectionId={connectionId}
      />

      <ConnectModal
        isOpen={main.isConnectModalOpen}
        onClose={main.closeConnectModal}
        isConnected={gameConn.isConnected}
        currentHost={gameConn.currentHost}
        currentPort={gameConn.currentPort}
        onConnect={gameConn.connect}
        onDisconnect={gameConn.disconnect}
      />

      <LibraryModal isOpen={main.isLibraryModalOpen} onClose={main.closeLibraryModal} connectionId={connectionId} />

      <AccountModal isOpen={main.isAccountModalOpen} onClose={main.closeAccountModal} connectionId={connectionId} />

      <EquipmentModal
        isOpen={main.isEquipmentModalOpen}
        onClose={main.closeEquipmentModal}
        connectionId={connectionId}
      />

      {(() => {
        const autoLevelingProps = {
          isOpen: isAutoLevelingModalOpen,
          onClose: () => setIsAutoLevelingModalOpen(false),
          connectionId,
          isConnected: gameConn.isConnected,
          config: auto.config,
          setConfig: auto.setConfig,
          runState: auto.runState,
          xpProgress: auto.xpProgress,
          socketReady: auto.socketReady,
          start: auto.start,
          stop: auto.stop,
          pause: auto.pause,
          resume: auto.resume,
          resetToDefaults: auto.resetToDefaults,
          moveNext: auto.moveNext,
          movePrev: auto.movePrev,
          rescanRoom: auto.rescanRoom,
        };
        return <AutoLevelingWizard {...autoLevelingProps} />;
      })()}

      {/* ✅ CHANGED: pass connectionId to both contribute modals */}
      <ContributeIdentifyModal
        isOpen={isIdentifyModalOpen}
        onClose={() => setIsIdentifyModalOpen(false)}
        connectionId={connectionId}
      />
      <ContributeCreatureLoreModal
        isOpen={isLoreModalOpen}
        onClose={() => setIsLoreModalOpen(false)}
        connectionId={connectionId}
      />

      <ScriptingHelpModal isOpen={isScriptingHelpOpen} onClose={() => setIsScriptingHelpOpen(false)} />
    </div>
  );
};

export default MainContainer;
