// apps\game-client\src\pages\MainContainer.tsx
import React from 'react';
import styles from '../styles/MainContainer.module.scss';
import { useVisualViewportHeight } from '../hooks/useVisualViewportHeight';

import { BottomPane } from '../components/BottomPane';
import { UserStyleOverrideModal } from '../components/UserStyleOverrideModal';
import UserScriptSandboxModal from '../components/UserScriptSandboxModal';
import ConnectModal from '../components/ConnectModal';
import PluginsModal from '../components/PluginsModal';

import { useLayoutSizing, useUserCssOverrides, useMainContainer } from '../hooks/useMainContainer';
import { usePlugins } from '../hooks/usePlugins';

import { MainMenuBar } from '../components/MainMenuBar';
import { LayoutShell } from '../components/LayoutShell';
import { useGameConnection } from '../hooks/useGameConnection';
import { useBeforeUnloadGuard } from '../hooks/useBeforeUnloadGuard';

import { CORE_PLUGINS } from '../features/plugins/registry';
import { pluginHost } from '../features/plugins/pluginHost';

import { applyCssToDom, getAppliedCss } from '../features/userStyles/userStyleOverrideStore';
import LibraryModal from '../components/LibraryModal';
import AccountModal from '../components/AccountModal';

import EquipmentModal from '../components/EquipmentModal';
import { useEquipmentCapture } from '../hooks/useEquipmentCapture';
import { useEquipmentDeltas } from '../hooks/useEquipmentDeltas';

import AutoLevelingModal from '../components/AutoLevelingModal';
import { useAutoLeveling } from '../hooks/useAutoLeveling';
import { RuntimeSingleton } from '../features/userScripts/runtimeSingleton';
import { useTerminal } from '../hooks/useTerminal';
import { ShatteredArchiveTerminal } from '../features/terminal/shatteredArchiveTerminal';
import { DispatchEvent, ListenEvent } from '../features/event-emitter/event-dispatcher';
import { PLUGIN_CONFIG_PERSIST_EVENT, type PluginConfigPersistPayload } from '../features/plugins/pluginConfigPersist';
import FocusBarVitals from '../components/FocusBarVitals';
import ContributeIdentifyModal from '../components/ContributeIdentifyModal';
import ContributeCreatureLoreModal from '../components/ContributeCreatureLoreModal';
import ScriptingHelpModal from '../components/ScriptingHelpModal';
import { useAuthCallback } from '../hooks/useAuthCallback';

// ── AI-METHOD ── regenerated by annotate_methods — do not hand-edit
// @ai-method: MainContainer — (no summary)
// @ai-hash: 66d5b39d
// ── END AI-METHOD ──
export const MainContainer: React.FC = () => {
  useVisualViewportHeight();
  useAuthCallback();
  const main = useMainContainer();
  const gameConn = useGameConnection();

  // Warn before closing/reloading the tab while a play-server connection is live.
  useBeforeUnloadGuard(gameConn.isConnected);

  const userScriptRuntime = RuntimeSingleton.Instance.GetUserScriptRuntime;
  const terminal = ShatteredArchiveTerminal.Instance;

  React.useEffect(() => {
    applyCssToDom(getAppliedCss());
  }, []);

  const { layoutVars, handleVerticalResizeMouseDown, handleHorizontalResizeMouseDown } = useLayoutSizing();

  const {
    userCssApplied,
    userCssDraft,
    setUserCssDraft,
    isStyleModalOpen,
    openStyleModal,
    closeStyleModal,
    saveUserCss,
    discardDraft,
  } = useUserCssOverrides();

  const [isScriptModalOpen, setIsScriptModalOpen] = React.useState(false);
  const [isPluginsModalOpen, setIsPluginsModalOpen] = React.useState(false);
  const [isAutoLevelingModalOpen, setIsAutoLevelingModalOpen] = React.useState(false);

  // Contribute modals
  const [isIdentifyModalOpen, setIsIdentifyModalOpen] = React.useState(false);
  const [isLoreModalOpen, setIsLoreModalOpen] = React.useState(false);

  const handleOpenCustomStyles = () => openStyleModal();
  const handleOpenScriptSandbox = () => setIsScriptModalOpen(true);
  const handleOpenConnect = () => main.openConnectModal();
  const handleOpenAccount = () => main.openAccountModal();
  const handleOpenPlugins = () => setIsPluginsModalOpen(true);
  const handleOpenLibrary = () => main.openLibraryModal();
  const handleOpenEquipment = () => main.openEquipmentModal();
  const handleOpenAutoLeveling = () => setIsAutoLevelingModalOpen(true);
  const handleOpenIdentifyObject = () => setIsIdentifyModalOpen(true);
  const handleOpenCreatureLore = () => setIsLoreModalOpen(true);

  const [isScriptingHelpOpen, setIsScriptingHelpOpen] = React.useState(false);
  const handleOpenScriptingHelp = () => setIsScriptingHelpOpen(true);

  const connectionId = React.useMemo(() => {
    const host = gameConn.currentHost;
    const port = gameConn.currentPort;

    if (!host || !port) return 'default';
    if (host.includes('dsl-mud')) return 'dsl-mud';
    return `${host}:${port}`;
  }, [gameConn.currentHost, gameConn.currentPort]);

  React.useEffect(() => {
    if (!connectionId) {
      return;
    }
    DispatchEvent('shatteredarchive:connection-changed', {
      connectionId,
      host: gameConn.currentHost,
      port: gameConn.currentPort,
    });
  }, [connectionId, gameConn.currentHost, gameConn.currentPort]);

  const plugins = usePlugins(connectionId);
  useEquipmentCapture(connectionId);
  useEquipmentDeltas(connectionId);

  const auto = useAutoLeveling(connectionId, gameConn.isConnected);

  /**
   * Plugin lifetime is scoped to the CONNECTION, and to nothing else.
   *
   * This deliberately does not depend on `plugins.installed`. It used to, and the
   * cleanup below is a full `pluginHost.shutdown()` — so every change to the
   * installed list (a config edit, a cloud sync, the boot storage migration,
   * toggling any other plugin) destroyed and re-`create()`d EVERY plugin closure.
   * See pluginHost.syncInstalled for why that broke text-to-speech outright.
   */
  React.useEffect(() => {
    pluginHost.setConnection(connectionId);

    for (const p of CORE_PLUGINS) {
      pluginHost.registerModule(p.create());
    }

    return () => {
      pluginHost.shutdown();
    };
  }, [connectionId]);

  /**
   * Which of the registered plugins are running. Diffed, never rebuilt — a plugin
   * that is already enabled and still enabled keeps the exact instance (and so its
   * queues, timers and subscriptions) across every one of these passes.
   *
   * Depends on `connectionId` as well so it re-applies after the effect above has
   * rebuilt the host for a new connection; effects run in declaration order, so
   * registration has already happened by the time this runs.
   */
  React.useEffect(() => {
    pluginHost.syncInstalled(plugins.installed);
  }, [connectionId, plugins.installed]);

  /**
   * A plugin changing its OWN config (e.g. text-to-speech's floating mode bubble)
   * has to land in the same store the config modal writes, or the effect above
   * reverts it on the next installed-list change. The plugin only sends a patch;
   * the merge onto the saved record happens here, where that record lives.
   */
  React.useEffect(() => {
    return ListenEvent<PluginConfigPersistPayload>(PLUGIN_CONFIG_PERSIST_EVENT, ({ pluginId, patch }) => {
      if (!pluginId || !patch) return;
      const record = plugins.getInstallRecord(pluginId as never);
      if (!record) return;
      plugins.updatePluginConfig(pluginId as never, { ...(record.userConfig ?? {}), ...patch });
    });
  }, [plugins]);

  return (
    <div className={styles.root}>
      <MainMenuBar
        onOpenCustomStyles={handleOpenCustomStyles}
        onOpenScriptSandbox={handleOpenScriptSandbox}
        onOpenConnect={handleOpenConnect}
        onOpenAccount={handleOpenAccount}
        onOpenPlugins={handleOpenPlugins}
        onOpenLibrary={handleOpenLibrary}
        onOpenEquipment={handleOpenEquipment}
        onOpenAutoLeveling={handleOpenAutoLeveling}
        onOpenIdentifyObject={handleOpenIdentifyObject}
        onOpenCreatureLore={handleOpenCreatureLore}
        onOpenScriptingHelp={handleOpenScriptingHelp}
      />

      <FocusBarVitals />

      <LayoutShell
        layoutVars={layoutVars}
        onVerticalResizeMouseDown={handleVerticalResizeMouseDown}
        onHorizontalResizeMouseDown={handleHorizontalResizeMouseDown}
        BottomPaneComponent={BottomPane}
        isConnected={gameConn.isConnected}
        sendRaw={gameConn.sendRaw}
        autoLevelMode={auto.config.mode}
        autoLevelRunState={auto.runState}
        onSightseeRescan={auto.rescanRoom}
      />

      <UserStyleOverrideModal
        isOpen={isStyleModalOpen}
        appliedCss={userCssApplied}
        draftCss={userCssDraft}
        onChangeDraft={setUserCssDraft}
        onPreview={(css) => {
          saveUserCss(css);
          closeStyleModal();
        }}
        onSave={(css) => {
          saveUserCss(css);
          closeStyleModal();
        }}
        onDiscardDraft={() => {
          discardDraft();
          closeStyleModal();
        }}
        onClose={closeStyleModal}
      />

      <UserScriptSandboxModal
        isOpen={isScriptModalOpen}
        onClose={() => setIsScriptModalOpen(false)}
        connectionId={connectionId}
      />

      <PluginsModal
        isOpen={isPluginsModalOpen}
        onClose={() => setIsPluginsModalOpen(false)}
        connectionId={connectionId}
      />

      <ConnectModal
        isOpen={main.isConnectModalOpen}
        onClose={main.closeConnectModal}
        isConnected={gameConn.isConnected}
        currentHost={gameConn.currentHost}
        currentPort={gameConn.currentPort}
        onConnect={gameConn.connect}
        onDisconnect={gameConn.disconnect}
      />

      <LibraryModal isOpen={main.isLibraryModalOpen} onClose={main.closeLibraryModal} connectionId={connectionId} />

      <AccountModal isOpen={main.isAccountModalOpen} onClose={main.closeAccountModal} connectionId={connectionId} />

      <EquipmentModal
        isOpen={main.isEquipmentModalOpen}
        onClose={main.closeEquipmentModal}
        connectionId={connectionId}
      />

      <AutoLevelingModal
        isOpen={isAutoLevelingModalOpen}
        onClose={() => setIsAutoLevelingModalOpen(false)}
        connectionId={connectionId}
        isConnected={gameConn.isConnected}
        config={auto.config}
        setConfig={auto.setConfig}
        runState={auto.runState}
        socketReady={auto.socketReady}
        start={auto.start}
        stop={auto.stop}
        pause={auto.pause}
        resume={auto.resume}
        resetToDefaults={auto.resetToDefaults}
        moveNext={auto.moveNext}
        movePrev={auto.movePrev}
        rescanRoom={auto.rescanRoom}
      />

      {/* ✅ CHANGED: pass connectionId to both contribute modals */}
      <ContributeIdentifyModal
        isOpen={isIdentifyModalOpen}
        onClose={() => setIsIdentifyModalOpen(false)}
        connectionId={connectionId}
      />
      <ContributeCreatureLoreModal
        isOpen={isLoreModalOpen}
        onClose={() => setIsLoreModalOpen(false)}
        connectionId={connectionId}
      />

      <ScriptingHelpModal isOpen={isScriptingHelpOpen} onClose={() => setIsScriptingHelpOpen(false)} />
    </div>
  );
};

export default MainContainer;
